### ISSUE TITLE
Overview search results not visible after upcoming gnome-shell change

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#1434] opened 2019-08-02 16:48 UTC
I am on Arch Linux using Yaru master and a [custom gnome-shell package](https://aur.archlinux.org/packages/gnome-shell-performance/) that backports a number of in-development patches to gnome-shell 3.32.

After [gnome-shell merge request 110](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/110), when using the Yaru gnome shell theme, app search results no longer appear when searching from the overview. The results are still there (in that hitting enter launches the first search result), but are not visible. The issue is not present when using the regular gnome-shell session, only with Yaru.

Since this merge request has been merged into gnome-shell master, I expect this bug will be present on gnome-shell 3.34 to be released next month.

Here is a screenshot of the invisible search results:

![Screenshot from 2019-08-02 12-43-02](https://user-images.githubusercontent.com/1044087/62385494-42295a80-b523-11e9-9b54-b3c1621f8f77.png)

**Comment by chrisjbillington** [comment] 2019-08-02 16:51
Here is the bug report against gnome-shell:

https://gitlab.gnome.org/GNOME/gnome-shell/issues/1456

**Comment by verdre** [comment] 2019-08-02 17:23
The issue here is that with (this)[https://gitlab.gnome.org/GNOME/gnome-shell/commit/a78527050ada988f30f00adaf8a9a395b381b8a1?merge_request_iid=110] change in gnome-shell, a css class was removed and the style for this class moved to another css class.

This is not a problem with any stable version of gnome-shell nor with the versions shipped in Ubuntu, but only when running gnome-shell from master, so this is not a bug in Yaru.

@chrisjbillington if you want to continue using themes while running a patched shell, please make sure to apply all changes the patches did to Adwaita to your custom theme (ie. Yaru), too.

**Comment by chrisjbillington** [comment] 2019-08-02 17:31
I can do that, but will that need to be done by Yaru developers as well once the next version of gnome shell comes out, or is it an automatic part of the build process? If it requires manual intervention on the part of Yaru developers, then that's why I reported the issue here, as a heads up that this will need to be done at some point due to the change in adwaita. If this is not the case then feel free to close this issue.

**Comment by clobrano** [comment] 2019-08-03 07:55
Hi @chrisjbillington, 
thank you for reporting this. We take care of this kind of upstream changes when they're about to land in Ubuntu, also to avoid the possible fluctuation of changes (remove, add, remove again :))

Closing this now.

**Closed by clobrano** 2019-08-03 07:55 UTC
