### ISSUE TITLE
Wrong color of select background and scrollbar into Firefox

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2115] opened 2020-03-26 12:14 UTC
Tested on 19.10, my VM 20.04 is broken so I can't check this on master.

## Expected Behavior

Select background color and scrollbar are orange.

![Capture d’écran de 2020-03-26 12-49-49](https://user-images.githubusercontent.com/36476595/77644398-3894ad00-6f61-11ea-9b5d-afa6fbb18b82.png)

## Actual Behavior

Select background color and scrollbar of Yaru-dark revert to Adwaita blue.

![Capture d’écran de 2020-03-26 12-53-26](https://user-images.githubusercontent.com/36476595/77644413-3c283400-6f61-11ea-98cd-29cdb4290f85.png)

**Comment by clobrano** [comment] 2020-03-26 12:26
Hey @Jupiter007-43, have you seen this only in Firefox?

**Comment by Jupiter007-43** [comment] 2020-03-26 13:56
Same issue on Firefox nightly.
Opera and Chromium, both snap, aren't affected.

**Comment by Feichtmeier** [comment] 2020-03-26 15:08
Yeah, I noticed this too! Yaru-dark is somehow converted to Adwaita-dark in firefox :(

**Comment by Jupiter007-43** [comment] 2020-03-26 15:41
So it isn't a Yaru bug?

**Comment by Feichtmeier** [comment] 2020-03-26 15:46
- [ ] test

**Comment by Feichtmeier** [comment] 2020-03-26 15:47
Actually Yaru is the only theme where it works

Tried arc and ambiance and both go back to Adwaita checkmarks and scrollsbars

Only Yaru works
Not yaru-dark and yaru-light not arc not ambiance

**Comment by Nilsolm** [comment] 2020-03-26 18:02
I've run into this problem as well. From what I understand, this is intended behaviour in Firefox and serves as a temporary workaround for various theming-related issues until they are fixed properly. See https://bugzilla.mozilla.org/show_bug.cgi?id=1527048

**Comment by Jupiter007-43** [comment] 2020-03-28 17:48
Thanks a lot for the link. 👍
So this isn't a Yaru problem, should I close this issue?

**Comment by clobrano** [comment] 2020-03-29 11:05
Alright, closing this for now then, thanks all

**Closed by clobrano** 2020-03-29 11:05 UTC
