### ISSUE TITLE
Color Problem in Gedit with Yaru Dark Theme

### ISSUE THREAD

**Issue by srueegger** [ubuntu/yaru#2140] opened 2020-04-09 12:46 UTC
## Expected Behavior

First of all I want to apologize. My English is not very good.

The only thing you have to do is open a text file in Gedit. It is important that the Yaru Dark Theme is activated.

## Actual Behavior

The line that is in focus is then no longer legible

## Steps to Reproduce the Problem

  1. Activate Yaru Dark Theme
  2. Open a Text File in Gedit
  3. Focus a line

## Software that presents the issue

- Name: Gedit
- Version: 3.36.1

## Yaru version
I'm not sure. Is the Yaru Theme in the actually Ubuntu 20.04 Beta Repositorys..
![Bildschirmfoto vom 2020-04-09 14-40-42](https://user-images.githubusercontent.com/11472914/78896567-f2673f80-7a70-11ea-9892-2d367e0f8606.png)

**Comment by clobrano** [comment] 2020-04-09 12:53
Hey @srueegger, thanks for taking time to help us.

This is a duplicate of #2090, we can't do much about it, I can suggest you to use a dark-friendly gedit's color scheme under <kbd>Preference</kbd>-><kbd>Font & Colors</kbd>

**Closed by clobrano** 2020-04-09 12:53 UTC
