### ISSUE TITLE
can't select text from the start of a line on a vertically split terminator shell

### ISSUE THREAD

**Issue by tjaalton** [ubuntu/yaru#1243] opened 2019-03-07 08:17 UTC
## Expected Behavior

Selecting text on a vertically split terminator window should work properly.

## Actual Behavior

You can't start the selection from the first character of a line, instead it'll try to resize the split shell.

## Steps to Reproduce the Problem

  1. open terminator
  2. split the window vertically
  3. try to select text from the start of a line
  4. notice you can't include the first character, since the mouse cursor is changed to resize the widget

## Specifications

been there since cosmic, now using disco

**Comment by clobrano** [comment] 2019-03-07 08:47
Hi @tjaalton, thanks for contributing to Yaru :+1: 

Could you confirm that this issue is not reproducible in Adwaita?

**Comment by tjaalton** [comment] 2019-03-07 08:58
hmm adwaita is affected too, ambiance isn't which is what I seem to be using on 18.04

**Comment by clobrano** [comment] 2019-03-07 09:02
I see. Just to clarify, is this what you meant?

![image](https://user-images.githubusercontent.com/2883614/53944660-18791e00-40c0-11e9-902f-51c5968d52a8.png)

**Comment by tjaalton** [comment] 2019-03-07 09:14
try to select from the terminal on right, you can't start the selection from the first character of the line

**Comment by Feichtmeier** [comment] 2019-03-07 09:14
Is that a gtk2 app?

**Comment by clobrano** [comment] 2019-03-07 09:24
The problem is that when the cursor changes functionality from select to drag window when you try to select the first character. 
From the top of my head, I can say that some padding might help, but this looks more an issue in Terminator, that should provide that padding by himself.

Closing this now, unless Terminator maintainer shows it's actually a theming issue.

**Comment by Feichtmeier** [comment] 2019-03-07 09:27
Maybe it's using the dark theme and my ugly wildcard is hitting again because it's a custom style class? @clobrano

**Comment by clobrano** [comment] 2019-03-07 09:30
It doesn't seem, since it's reproducible in Adwaita as well

**Comment by tjaalton** [comment] 2019-03-07 09:45
the "width" of the drag widget seems to be ~10 pixels with adwaita/yaru, whereas on ambiance it's 2

**Comment by clobrano** [comment] 2019-03-07 09:52
This is interesting, I'll investigate on it

**Comment by clobrano** [comment] 2019-03-15 15:57
I noted that on tilix selecting text is perfectly doable in the same condition

**Comment by tjaalton** [comment] 2019-03-15 16:25
not here, exactly the same problem with yaru/ambiance

**Comment by tjaalton** [comment] 2019-03-15 16:28
I mean yaru or adwaita

**Comment by clobrano** [comment] 2019-03-15 16:56
![image](https://user-images.githubusercontent.com/2883614/54448290-a6ea4100-474b-11e9-8c7a-a4e717379e8c.png)

**Comment by tjaalton** [comment] 2019-03-15 17:36
You probably started the selection from the line where it says 'lsusb', right after it? That works of course, but try selecting two lines from the middle of that output, starting from the first character of the line

**Comment by tjaalton** [comment] 2019-03-15 17:38
![Kuvakaappaus - 2019-03-15 19-31-02-2](https://user-images.githubusercontent.com/5273172/54450750-e029ad80-4759-11e9-8086-8a67d23e8ee1.png)

you get something like this

**Comment by clobrano** [comment] 2019-03-15 19:08
> You probably started the selection from the line where it says 'lsusb', right after it? That works of course

of course not

**Comment by clobrano** [comment] 2019-03-15 19:14
![Peek 2019-03-15 20-13](https://user-images.githubusercontent.com/2883614/54456535-dbb3c380-475e-11e9-8999-3e69af7e4bda.gif)

**Comment by tjaalton** [comment] 2019-03-15 20:14
your tilix has something extra between the shells, it doesn't look like that on disco

**Comment by tjaalton** [comment] 2019-03-15 20:14
between terminals I mean, the vertical bar

**Comment by clobrano** [comment] 2019-03-15 21:41
Yes, I noticed that, but I was testing it on disco daily build. It seems like the scrollbar is disabled in your copy, but it should be at the left of the separation line

**Comment by tjaalton** [comment] 2019-03-15 21:52
oh you've enabled "use a wide handle for splitters" from the prefs.. that's cheating? :)

**Comment by clobrano** [comment] 2019-03-22 15:20
> hmm adwaita is affected too, ambiance isn't which is what I seem to be using on 18.04

Indeed, the wide handle was set, but not on purpose for this issue :)
However, we don't have a custom handle and we use Adwaita's one here, so the issue should be reported and fixed upstream

**Comment by clobrano** [comment] 2019-03-22 15:41
here it is https://gitlab.gnome.org/GNOME/gtk/issues/1768

Closing this now, let's reopen it later in case of updates

**Closed by clobrano** 2019-03-22 15:41 UTC

**Comment by iafilius** [comment] 2020-06-25 15:07
Hi, perhaps a workaround available or even better a solution? perhaps any kind of update?
The issue on https://gitlab.gnome.org/GNOME/gtk/issues/1768  is basically pointing back to app (and closed issue too), and meanwhile i feel quite stupid always not copy-ing the first char (on splitted window)
Using Ubuntu 20.04/Yaru Dark/terminator

Thanks

**Comment by clobrano** [comment] 2020-06-25 20:28
https://github.com/ubuntu/yaru/issues/1243#issuecomment-473452784

> oh you've enabled "use a wide handle for splitters" from the prefs.. that's cheating? :)

Does this workaround work?

**Comment by iafilius** [comment] 2020-06-26 06:11
Hi Clobrano, sorry, but looked (multiple times) for "use a wide handle for splitters" in the terminator prefs, but can't find it here.
Also a search on internet only this thread returns.
Would you please so kind to guide me a bit where to find it? thanks a lot!

**Comment by clobrano** [comment] 2020-06-26 06:34
My bad, I thought you were talking about Tilix. Tilix is quite similar to Terminator and does have the "wide handle" setting in Settings>Appearance

**Comment by iafilius** [comment] 2020-06-27 08:45
Hi Clobrano,
In Tilix i can find it, and the wide setting fixes it.
But in Terminator/Preference/Appearance the slider "Terminal Separator size" can be changed from -1 to 20.
(So slightly difference as you wrote, but i guess that is what you mean)
But actually i don't see/notice any difference, so the copy/select of 1st char in right window (on left side) issue is still there for me.
![Screenshot from 2020-06-27 10-36-57](https://user-images.githubusercontent.com/15259647/85918337-3a248880-b862-11ea-8f94-d4476b5177c3.png)

Thanks,

**Comment by clobrano** [comment] 2020-06-29 07:48
Yes, on Terminator the setting seems useless. I know it might seem silly, but when using terminator I simply select from the end of the line to the beginning, so that I can get all the text. I know this workaround might sound questionable, but we do not plan to change the drag widget size anytime soon.

**Comment by iafilius** [comment] 2020-06-30 15:37
Thanks for your feedback and workaround suggestion Clobrano. trying to get used on Tilix for now, and don't mind the extra speed.

**Comment by aaronsuns** [comment] 2021-11-04 16:00
Still no workaround? Using terminator on default ubuntu 20.04,  can't select first char is annoying.

**Comment by aaronsuns** [comment] 2021-11-04 16:02
One work around is that double click the line you want to select and then hold shift to drag for the rest.

**Comment by clobrano** [comment] 2021-11-04 17:16
I'm sorry, but there's still no fix for this. Another workaround is to start selection from the end of the line and then drag to the left. 
Out of cut curiosity, is the problem the same using adwaita, or is yaru specific?

**Comment by aaronsuns** [comment] 2021-11-04 19:18
Only know this behavior with defaults Ubuntu 20.04. Default version from Ubuntu repo.

the problem is that some time you are in the middle of a big log file, you want to select long paragraph from one place,  hard to identify the start point since similar log can be repeated several times.  From bottom right to top left would be pain.  I’d rather manually type the first chat after copy or use triple click + hold shift way.
