### ISSUE TITLE
Looks like clicking on this button will make something dangerous

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#769] opened 2018-09-03 08:21 UTC
Ubuntu 18.04, Yaru from stable snap.

I've opened the update manager app. It showed some apps could be updated. But I see the colour of the text on "Zainstaluj" (Install) button is kinda red. Hmmm... could that mean it is a not recommended operation? 
Obviously as an old user of Ubuntu I know it is save and the colour is probably orange but I believe it could be confusing for some people.

Screenshot:
![zrzut ekranu z 2018-09-03 08-59-44](https://user-images.githubusercontent.com/1629120/44975548-a9790c00-af5a-11e8-9206-14639f14576a.png)

**Comment by Feichtmeier** [comment] 2018-09-03 08:26
It's not the same like suggested action. It's orange because we decided that it looks better than the dark border which we had before for the default button.
It changes btw: tab a little around and you see it

**Comment by mivoligo** [comment] 2018-09-03 09:11
I understand it will change after tabbing around but my wife asked me why this is red, is there a problem this time with updates? She's not a "power user" and she doesn't know about using keyboard to move focus. For her it looked like the colour of the text on the button suggests the action is not recommended.

**Comment by Feichtmeier** [comment] 2018-09-03 09:35
Well, we could also use green but please, for the love of God, let's not go back to the ugly black border

**Comment by madsrh** [comment] 2018-09-03 10:07
That orange text just isn't growing on me, like I hoped it would. I'm still trying to get used to it and I know that @Feichtmeier will cancel my christmas gift 🎁 🎄 for saying this, but I'm +1 for reverting to the old design 🙊 

![image](https://user-images.githubusercontent.com/3986894/44980361-ed2a4080-af6f-11e8-9df3-a3bb0dc89c64.png)

It was a joint decision, so I'm not pushing anything here (I'll leave that to @clobrano 😉 ) I just wanted to share my point of view.

> but my wife asked me why this is red

I guess it depends on the screen, but here it doesn't look red at all.

> For her it looked like the colour of the text on the button suggests the action is not recommended.

I can see why and find the old design much less confusing _(searching for a better word)_

**Comment by Feichtmeier** [comment] 2018-09-03 10:29
Oh no...
The black border destroys all the beauty of the buttons.
Could we have a look at green text please?
How do other themes make this?

**Comment by Feichtmeier** [comment] 2018-09-03 10:34
We use green for everything positive like installed icon in gnome software (the number badge)

**Comment by madsrh** [comment] 2018-09-03 10:45
This is the old issue: https://github.com/ubuntu/yaru/issues/306

> Oh no...

SORRY! 😞 

> The black border destroys all the beauty of the buttons.

The colored text isn't pretty eighter 🤷‍♂️ 

> How do other themes make this?

Most themes ignore this (Adwaita, Arc,...) except Ambiance/Radiance:
![image](https://user-images.githubusercontent.com/3986894/44982640-dd622a80-af76-11e8-8dea-7cf9d2243a37.png)

I'm not sure I want to argue against you here. You seem very determined on only changing the text color. Perhaps it's only mivoligo's wife and me 😆 



> Could we have a look at green text please?

But couldn't the default selection also be for destructive action?

![image](https://user-images.githubusercontent.com/3986894/44982424-3087ad80-af76-11e8-85a5-1952f0746bf8.png)

**Comment by Feichtmeier** [comment] 2018-09-03 10:49
![screenshot-20180903124815-645x508](https://user-images.githubusercontent.com/15329494/44982908-b0624780-af77-11e8-86d8-0f56f8cd2779.png)
![screenshot-20180903124758-645x508](https://user-images.githubusercontent.com/15329494/44982909-b0624780-af77-11e8-80b5-fd3993e8570e.png)
![peek 2018-09-03 12-47](https://user-images.githubusercontent.com/15329494/44982915-b526fb80-af77-11e8-8869-b7cef8ba1593.gif)

That's
$_default_color: if($variant=='light',darken($success_color,10%),$success_color);

**Comment by madsrh** [comment] 2018-09-03 10:55
> I am sure this is nothing personal or any subjective crusade from both of us and we only want the best for the theme 💃

+1 😁

That green is really NOT good. I would rather keep the orange (or revert to the strong border).

**Comment by Feichtmeier** [comment] 2018-09-03 11:01
![screenshot-20180903130046-645x508](https://user-images.githubusercontent.com/15329494/44983428-7003c900-af79-11e8-8f16-b22f99e6ee68.png)
![screenshot-20180903125828-645x508](https://user-images.githubusercontent.com/15329494/44983429-7003c900-af79-11e8-9238-42d57c78825f.png)

What about white and black then

**Comment by madsrh** [comment] 2018-09-03 11:09
> What about white and black

Much better. Is the difference too subtle in the dark theme? I can't tell on my phone here. 
You only changed the color, not the weight, right?

**Comment by Feichtmeier** [comment] 2018-09-03 14:18
It's very subtle in the dark theme yes. No I didn't change the font weight

**Comment by madsrh** [comment] 2018-09-03 14:43
I really like the light theme, but I seriously cannot tell that the text is white in the dark theme. 
What about this or must the light and dark theme be 100% alike? Maybe this will mess up the hover color 🤔 

![image](https://user-images.githubusercontent.com/3986894/44992523-b5cf8a00-af97-11e8-95ec-d7bbd3dfbb05.png)

**Comment by clobrano** [comment] 2018-09-03 20:28
Just and idea, but since Adwaita ignores it, why we don't we as well?

**Comment by Feichtmeier** [comment] 2018-09-03 21:09
The reason why they don't style it is because modern gnome apps don't use it. They have the suggested action button for things like that :)

**Comment by Luxamman** [comment] 2018-09-05 15:47
Also just stumbled over the orange font in the Software Updater and are kind of irritated because of it.

![orange ok](https://user-images.githubusercontent.com/20417555/45105033-a84f0700-b133-11e8-86f6-f28b703a75af.png)
Like the OK is maybe not OK? 

Black and white will make it for me I guess^^

**Comment by clobrano** [comment] 2018-09-06 07:55
> but it shows you which button will be activated if you press return. If it is not styled, you have no idea which button will be activated.

This is often not true, actually. Default button is most of the timed selected as well, the only missing case is when selection goes to a different widget (not button), but that's a consequence of user action and he/she should be able to figure out what happened

> Darkening the font colour seems like the best idea to me.

This won't work in dark variant

**Comment by Feichtmeier** [comment] 2018-09-06 08:06
Mostly the default button is just one button beneath others, for example in the software installer of Ubuntu.
So indicating anything ends in confusion as you can see because this topic exists. It's NOT the same as a suggested action because suggested actions don't jump around. ( In my opinion the install button in the software installer should be the suggested action but unless we don't step up and change this in launchpad I guess this won't change. )
So why do we need it? Does the user really need to know which button he recently pressed? In my opinion: no

**Comment by CDrummond** [comment] 2018-09-06 08:50
Its not what **was** recently pressed - its which button **will** be pressed if return is pressed.

You could argue the same with focus rectangles - why show those? (They 'jump' around too) Because they indicate which widget will be activated with the spacebar. How is that different from indicating which widget will be activated with the return/enter key?

I fail to see how there is any confusion. If there exists a button/widget that **would** be activated by the return/enter key, then it should be indicated in some manner. This topic exists because (some users find) the current indication is sub-optimal (its colour leads to confusion).

Windows (probably not the best example), shows the default button (at least windows 7) with a blue border. Some Gtk2 styles used a small rectangle top/left or bottom/right. Perhaps an underline could be used?

**Comment by clobrano** [comment] 2018-09-06 08:58
Adwaita does not show anything, however

**Comment by CDrummond** [comment] 2018-09-06 09:12
@clobrano Adwaita also does not show mouse-over events for inactive windows.

**Comment by madsrh** [comment] 2018-09-06 09:26
Just adding my point of view to the discussion. I can live with both, but I'm kind of with @CDrummond on this one. I know we don't have a solution for the dark theme, but the black font is a good solution IMO. Not sure if it's bad practise to only style the light theme 🤷‍♂️  

> ...its which button **will** be pressed if return is pressed.

Exactly! 
![image](https://user-images.githubusercontent.com/3986894/45147660-bf3e3980-b1c5-11e8-8476-08789161aaa1.png)

If we decide to do like Adwaita, it's fine - we just follow upstream, but it's a conscious choice that IMO takes away some of the usability - an extra service.

**Comment by Feichtmeier** [comment] 2018-09-06 09:39
> Its not what was recently pressed - its which button will be pressed if return is pressed.

Okay, maybe I misunderstood. But it is also active in some apps "by default" and in other dialogues/windows it is only active if I have pressed it before, like in the rhythmbox setting gif I posted, where you can clearly see that it is orange after I pressed it. Sooo it is used differently. 
In the software installer it is orange WITHOUT pressing anything and thus the user (the reason this issue is opened) thinks there is anything special (negative or positive) about this button. If it would not be colored, you could just decide which button you want to press. If you use a keyboard, there is still the focus ring and you can tab around like you wish. So why should we confuse the user with this button? No matter how you color it, it seems that there is something suggested in there when there is clearly no suggestion and it is only caused by some previous behaviour. 

When you open the ryhthmbox preferences THE FIRST TIME, the default button is colored:
![peek 2018-09-06 11-38](https://user-images.githubusercontent.com/15329494/45149267-6ec8db00-b1c9-11e8-842a-5eb371f0a95d.gif)

It is just confusing, no matter what the technical behavour or intend behind this is, the result is that it looks like either a positive or negative recommendation to press or to not press the button. No matter if you color it black, white, orange, or have an orange box shadow.

**Comment by CDrummond** [comment] 2018-09-06 09:44
What about setting the  font-weight to 500 instead of changing the text colour? I did a quick hack on my system, and it seems to work OK (for me). O perhaps an even less bold, but still bolder than normal, weight? I know on the original report there was some concern about this changing the size of the button, but that does not seem to happen for me (in my very limited testing)

Or, perhaps have a semi-transparent version of the focus ring? This might be confusing though...

_IMVHO_ there should be some indication, but it does not have to be in your face (as per the Ambiance example, which is a bit heaby handed)

**Comment by clobrano** [comment] 2018-09-06 11:48
Let's have some testing with font weight. I am sure I tried something similar, but not sure exactly what

**Comment by Feichtmeier** [comment] 2018-09-06 14:27
![image](https://user-images.githubusercontent.com/15329494/45163935-b4010300-b1f1-11e8-8f64-c417caaa381c.png)

![image](https://user-images.githubusercontent.com/15329494/45163973-c67b3c80-b1f1-11e8-81ab-43f5c8120ffc.png)

**Comment by Feichtmeier** [comment] 2018-09-06 14:30
![peek 2018-09-06 16-29](https://user-images.githubusercontent.com/15329494/45164153-270a7980-b1f2-11e8-8761-aa781b4d7eb1.gif)

**Comment by Feichtmeier** [comment] 2018-09-07 08:07
Bolt font is merged in --edge.... IF the build finishs successfully you can all test it from the edge channel

**Comment by Feichtmeier** [comment] 2018-09-07 17:34
![peek 2018-09-07 19-32_2](https://user-images.githubusercontent.com/15329494/45234074-edf70580-b2d4-11e8-9f86-2212dee552cf.gif)
![peek 2018-09-07 19-32](https://user-images.githubusercontent.com/15329494/45234075-edf70580-b2d4-11e8-88d4-beb22bf1278f.gif)

I don't think this transition looks very sexy, what do you guys think=

**Comment by clobrano** [comment] 2018-09-07 18:16
Have you tried to add a transition effect to font-size change only? Maybe it would be better if smoother

**Comment by Feichtmeier** [comment] 2018-09-07 20:29
Okay guys I tried a transition and it didn't work (maybe I did it wrong).

Now... what about this :see_no_evil: just an idea...
![image](https://user-images.githubusercontent.com/15329494/45241536-20acf800-b2ed-11e8-8daf-dfcb78e2023e.png)
![image](https://user-images.githubusercontent.com/15329494/45241594-476b2e80-b2ed-11e8-8af1-92c2e9ea3811.png)

![peek 2018-09-07 22-29](https://user-images.githubusercontent.com/15329494/45241652-7f727180-b2ed-11e8-9a42-ce20b0b63f6c.gif)

**Comment by madsrh** [comment] 2018-09-07 21:43
I prefer the bold text - even without any transition. This seems too subtle.

**Comment by Feichtmeier** [comment] 2018-09-07 22:49
Ok then no gradient xD!

HOWEVER... the bold does not work, even the buttons increase in size:

![peek 2018-09-08 00-49](https://user-images.githubusercontent.com/15329494/45246339-07ae4200-b301-11e8-8631-cca20e0084c3.gif)

**Comment by madsrh** [comment] 2018-09-07 23:18
> I'd say let's go with black and white

+1

But I'm a bit confused. Why didn't we see that in the earlier peeks: https://user-images.githubusercontent.com/15329494/45234074-edf70580-b2d4-11e8-9f86-2212dee552cf.gif

**Comment by clobrano** [comment] 2018-09-08 05:03
It depends on how much space left is for the label.

**Comment by Feichtmeier** [comment] 2018-09-08 07:29
Yes, I fear we might find other places

**Closed** 2018-09-08 10:39 UTC
Labels: design, discussion
