### ISSUE TITLE
White line under menu bar in Sublime Text 3

### ISSUE THREAD

**Issue by chrisjbillington** [ubuntu/yaru#860] opened 2018-09-24 05:07 UTC
Using the edge snap, I see a white line underneath the menu bar in Sublime Text 3. It was not there in a previous version of the communitheme gtk theme. However, I had not updated in several months (was formerly installed via the ppa and I had removed the ppa from sofware sources), so I don't have a guess for how long ago this was introduced. I do not see the white line under other menu bars, for example gnome-terminal. I think Sublime Text 3 may be using GTK 2, but I am unsure. So that may explain why I don't see it elsewhere.

Here is a screenshot:

![sublime-white-line](https://user-images.githubusercontent.com/1044087/45938201-8360ed80-bf95-11e8-8d55-f7022282d76a.png)

## Specifications

    `$ snap info communitheme`

```
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: today at 00:48 EDT
channels:                    
  stable:    0.1 (1174) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1198) 17MB -
installed:   0.1 (1198) 17MB -
```

Software that presents the issue:
- Name: Sublime text 3
- Version: Build 3175

**Comment by clobrano** [comment] 2018-09-24 21:34
Thanks for reporting this. The problem is due to a white GTK2 assets, but before changing it, we should double check whether it is not necessary to have it white in other applications

**Comment by clobrano** [comment] 2018-09-26 21:34
After checking, I believe this can't be fixed on our side.
SublimeText3 is the only GTK2 I know that uses a "line" asset as bottom border for the menubar, this asset has been changed in July to a brighter color, this is why you saw the change only recently.

Just to explain why I wouldn't change it, this is our test application if "line" was darker

![image](https://user-images.githubusercontent.com/2883614/46110474-05465600-c1e4-11e8-99a5-8c836cf0c8a8.png)

instead of

![image](https://user-images.githubusercontent.com/2883614/46110586-63733900-c1e4-11e8-804b-60b0ddd956d0.png)

**Comment by chrisjbillington** [comment] 2018-09-26 22:47
Fair enough. I suppose I'll report the bug to Sublime instead then.

**Comment by clobrano** [comment] 2018-09-27 05:54
@Paz-it, I have it :) and doesn't fix it. Sublime doesn't prefer dark variant a a used the bright line

**Comment by clobrano** [comment] 2018-09-27 21:00
> Fair enough. I suppose I'll report the bug to Sublime instead then.

that's a good idea, thank you.

**Closed by clobrano** 2018-09-27 21:00 UTC

**Comment by ph03** [comment] 2018-10-20 16:00
@chrisjbillington have you reported the issue with the sublime team already? can't find any report
