### ISSUE TITLE
Gtk-2 theme : suggesting to test  

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#579] opened 2018-06-28 15:34 UTC
Would you guys mind to add these lines to .gtkrc 
 
#set Gtk settings : 
gtk-icon-sizes="gtk-menu=16,16:\
                gtk-button=16,16:\
                gtk-small-toolbar=16,16:\
                gtk-large-toolbar=16,16:\
                gtk-dnd=16,16:\
                gtk-dialog=16,16"
gtk-toolbar-style = GTK_TOOLBAR_ICONS
gtk-menu-images = 0
gtk-menu-popup-delay = 0

Just a test for you to decide if you like it better.

**Comment by clobrano** [comment] 2018-06-30 11:39
Hi @Paz-it, sure we can try it. Could you tell me what's the expected change? What should we check?

Just a note for the future, a bug is not the right way to propose patches, please use a PR instead.

**Comment by Paz-it** [comment] 2018-06-30 21:39
Hi @clobrano , The most visual ones you can see in my example:
Before the change, the toolbar icons are big - a lot of space wasted
![screenshot from 2018-06-30 23-36-35](https://user-images.githubusercontent.com/37431503/42129102-14c1b332-7cc4-11e8-9ee9-ff7b0bd0d3d5.png)
After:
![screenshot from 2018-06-30 23-40-22](https://user-images.githubusercontent.com/37431503/42129118-71b0a954-7cc4-11e8-9f72-69ee40d050a2.png)
Gimp side bar big icons
![screenshot from 2018-06-30 23-55-51](https://user-images.githubusercontent.com/37431503/42129140-0719e0d2-7cc5-11e8-97d8-2e3ab309f292.png)
After:
![screenshot from 2018-06-30 23-53-34](https://user-images.githubusercontent.com/37431503/42129149-1952fdec-7cc5-11e8-9b3e-d69328b9c284.png)

Generally cleaner and more responsive - all type of toolbars and dialog's having  the same smaller icons, and menus responding without delay.
About PR: Don't know how-to yet... mean while I'll use the forum until I'll manage to understand it all .. :smile :man_shrugging:

**Comment by madsrh** [comment] 2018-07-01 14:14
This looks great @Paz-it 👍 
In my GIMP 2.8.22 **preferencess** doesn't use bold text.

Can you a) check how other themes styles this? b) remove the bold font?

![image](https://user-images.githubusercontent.com/3986894/42135286-3da9d70e-7d49-11e8-85ff-6e4c11cfe804.png)

**Comment by Paz-it** [comment] 2018-07-01 19:49
@madsrh , All other official themes like Ambiance,Radiance and Adwaita using the same configs as communitheme. 
I'm using Gimp 2.10. 2 so maybe it uses bold fonts. 
With the same icons you use it looks like that: 
Before:
![screenshot from 2018-07-01 21-24-51](https://user-images.githubusercontent.com/37431503/42138042-94700d20-7d7f-11e8-9553-8fc04b488774.png)
After:
![screenshot from 2018-07-01 21-39-50](https://user-images.githubusercontent.com/37431503/42138045-c23d9b50-7d7f-11e8-9b40-90aba581fcd0.png)
And Adwaita without my change:
![screenshot from 2018-07-01 21-34-48](https://user-images.githubusercontent.com/37431503/42138081-5deadd92-7d80-11e8-80cc-372b01742d61.png)
Those options are part of gtk options. we can decide whether to use them or not.

**Comment by madsrh** [comment] 2018-07-01 21:17
@Paz-it are you saying that the bold font is hardcoded? 😕 

IMHO the icons are too small 🔎 but I like the font size 👍

**Comment by Paz-it** [comment] 2018-07-02 10:56
@madsrh ,
It is not clear to me what exactly you mean when you say bold fonts. font rendering is personal on each machine. I didn't change the theme fonts so  it's out of point. Upstream is a word that gives me the chills so maybe I'm not the right person for this task. The example you gave is great but the sidebar in Setting is not the same as the scrolled window (with expanders )  in Gimp.  Any way, we have different view about it. I don't need the icons be "in my face" I like them symbolic and out the way most of the time. :smile:  there is plenty of room to adjust then though.. the sizes I mean. We can keep some of them bigger in some elements. (like your idea that "it shouldn't" be small. Why not?)

**Comment by clobrano** [comment] 2018-07-14 16:55
What's the status of this? Since it is not a bug and my understanding is that @Paz-it doesn't feel like keep going on, could we close it?

**Comment by Paz-it** [comment] 2018-07-14 18:50
@clobrano , Hi! 
It's not a bug and it was just a suggestion. I do like keep going on(and I do). I don't know why you think otherwise.  You can close it if you don't like it, so I'll not include it in the gtk2 part of the theme.

**Comment by clobrano** [comment] 2018-07-14 20:11
> Upstream is a word that gives me the chills so maybe I'm not the right person for this task 

Happy to have misunderstood. If you need help about doing a PR feel free to ask

**Comment by Feichtmeier** [comment] 2018-07-18 10:32
@Paz-it we can surely add those lines to the gtk2 file you have mentioned. Where exactly? Just at the bottom or rather at some special place?

**Comment by Paz-it** [comment] 2018-07-18 21:09
@Feichtmeier ,
In the gtkrc file : 
Under the " Set Gtk Settings"
 gtk-auto-mnemonics              = 1
gtk-primary-button-warps-slider = 1 
Just add them under the two above that already there..
and save! :sweat_smile: 
Thanks!

**Comment by Feichtmeier** [comment] 2018-07-21 09:05
This is a little bit confusing, in the opening post you mentioned more lines than in your last post. Also a before and after screenshots would be very helpful.

Like

firstchange) change X in line LINENUMBER so that UI-ELEMENT does EXPLANATION-WHAT-CHANGES
Before: screenshot 
After: screenshot

Secondchange) ....

And so on

Sorry for being so picky but the less I understand what happens, the more explanation I need. You want us to change the code which is nice and very helpful, but you need to add more details :)

**Comment by clobrano** [comment] 2018-07-25 15:56
Since this is actually under test, there is no more need of this bug :)
Closing it now

**Closed by clobrano** 2018-07-25 15:56 UTC
