### ISSUE TITLE
Dark/unrecognizable emoji in notifications

### ISSUE THREAD

**Issue by LouisMT** [ubuntu/yaru#922] opened 2018-10-19 20:26 UTC
## Expected Behavior

Emoji in notifications should be recognizable and clear.

## Actual Behavior

Emoji are not recognizable and seem to have a black overlay.

## Steps to Reproduce the Problem

1. Trigger a notification (GNOME) that contains emoji
1. Watch

![yaru-emoji](https://user-images.githubusercontent.com/1782761/47242338-b492d900-d3ee-11e8-9473-c5d619ce6846.png)

## Specifications

Using either the default or dark Yaru theme on Ubuntu 18.10.

Same issue as ubuntu/gnome-shell-communitheme#191. The issue mentions that the only fix is going back to dark notifications or it has to be fixed in GNOME itself. Currently the emoji look really ugly, and I would be happy if at least the dark theme could have dark notifications (if that fixes the issue), or maybe use monochrome emoji in the notifications so they are at least recognizable.

**Comment by clobrano** [comment] 2018-10-23 06:38
Monochrome emoji it's an idea, not sure it is possible though, I need to investigate more

**Comment by Feichtmeier** [comment] 2018-11-13 06:52
@3v1n0 do you have time to took into that notifications and see if you could make monochrome emojis possible?

**Comment by 3v1n0** [comment] 2018-11-14 04:16
Mhmmh, notifications using FDO notifications seem to work here: `notify-send 😭😭😭 🍟🍟🍟🍟🍟
`

**Comment by Feichtmeier** [comment] 2018-11-14 10:14
@3v1n0 
This is when you color the message green -> the emojis become green, too. Like any other "letter"
.message-title { color: green; }
.message-content { color: green; }
![screenshot from 2018-11-14 11-10-24](https://user-images.githubusercontent.com/15329494/48476064-5515c680-e7fe-11e8-981a-735171cd8d48.png)

**Comment by clobrano** [comment] 2018-12-13 14:41
In a smaller way, Fedora shows this problem as well. I opened a bug in gnome -shell

https://gitlab.gnome.org/GNOME/gnome-shell/issues/850

**Comment by clobrano** [comment] 2019-01-23 12:47
I think we can close this, the fix would be on gnome-shell side.

**Closed by clobrano** 2019-01-23 12:47 UTC
Labels: GNOME-shell

**Comment by Snuggle** [comment] 2019-11-03 00:15
I believe this is only an issue with Yaru. If you go to "Gnome Tweaks" > "Appearance" > "Shell" to `Arc Dark`, the emojis become coloured. You can install Arc-Dark with the `sudo apt install arc-theme`.

## With default Yaru shell theme, monochrome!
![image](https://user-images.githubusercontent.com/26250962/68078487-67ea2800-fdce-11e9-853d-e26df6b15f8f.png)

![image](https://user-images.githubusercontent.com/26250962/68078494-9f58d480-fdce-11e9-86b9-cd071fdcab43.png)

## With `arc-dark` shell theme, coloured and pretty!
![image](https://user-images.githubusercontent.com/26250962/68078500-b39cd180-fdce-11e9-8f9d-57821953f87e.png)

![image](https://user-images.githubusercontent.com/26250962/68078503-bf889380-fdce-11e9-8e39-a6471cb90909.png)


Since this seems to be caused by Yaru not providing a shell theme that supports coloured emoji, like the `arc-theme` package does, we can reopen this issue.

**Comment by Snuggle** [comment] 2019-11-03 00:31
## Extra Note

![image](https://user-images.githubusercontent.com/26250962/68078600-227b2a00-fdd1-11e9-9db6-f12ad4ff3a0f.png)

The colours still seem faded in the "Light" Arc shell theme, which is odd. Perhaps it's some kind of rendering issue that only occurs with a light-background notification area.

**Comment by Feichtmeier** [comment] 2019-11-03 00:45
Yeah right because arc dark is...

.. A dark theme. That's why it's named
Arc
Dark

The emojs are colored by colour of the text.
White text -> brightened up
Dark text -> dark text

And so on.

**Comment by clobrano** [comment] 2019-11-03 12:47
> The colours still seem faded, though not as much as Yaru, in the "Light" Arc shell theme, which is odd. Perhaps it's some kind of rendering issue that only occurs with a light-background notification area.

Not odd at all. The problem explained at https://github.com/ubuntu/yaru/issues/922#issuecomment-446991861 is that at gnome-shell level the **text color** is applied to the emoji as well. In dark gnome-shell text color is white and the emoji results fine, in light shell text is dark and emoji looks darker. Arc light has a lighter text color, so the *fade* effect is limited.

**Comment by memeplex** [comment] 2019-12-11 16:03
I think the wording by which this issue was described is very confusing:

> The emojs are colored by colour of the text.
> White text -> brightened up
> Dark text -> dark text

and

> the text color is applied to the emoji as well.

It's only the brightness of the color that is changed.

**Comment by clobrano** [comment] 2019-12-11 16:16
> It's only the brightness of the color that is changed.

It really the color actually. If text color is green, also emoji will be greenish

**Comment by memeplex** [comment] 2019-12-11 16:37
> It is really the color actually. If text color is green, also emoji will be greenish

But why is it colored and not merely bright with a dark theme?

**Comment by clobrano** [comment] 2019-12-11 20:16
I didn't check, but it might be already brighter than with a transparent text color on dark themes

**Comment by memeplex** [comment] 2019-12-12 12:43
Guys, [Florian answer](https://gitlab.gnome.org/GNOME/gnome-shell/issues/850#note_666921) is too categorical:

> This isn't high up the priority list because themes aren't officially supported and there's no issue with white-on-dark fonts as used by upstream GNOME.

Given that Ubuntu is an important Linux desktop shipping a default not supported upstream to the point that a rather gross usability problem won't be a priority (which is understandable, given their policy on themes), I believe this should be reopened to better track down the development downstream, since it is clear that the initiative should start downstream, presumably from Yaru.

**Comment by clobrano** [comment] 2019-12-12 12:54
I understand Florian's answer. This is not a priority for their product. I understood that a light shell was in Adwaita's plans so probably it would be in the future, in the meantime we can try to fix the problem ourselves for the good of Yaru and Gnome.

> Well, that or move to a dark shell theme (?).

#1637 :)

**Comment by Snuggle** [comment] 2020-01-23 12:29
@clobrano With the Ubuntu 20.04 update, wouldn't this be an important fix? It breaks dark themes on Yaru, and 20.04 is supposed to be bringing a dark theme?

**Comment by clobrano** [comment] 2020-01-23 12:33
@Snuggle, I totally agree. This is probably the main drawback for using dark theme for the shell, but the fix is to be done upstream and it's not an easy one, at least for anybody that is not into the stack involved.

**Comment by clobrano** [comment] 2020-01-23 12:33
I mean, it's impossible to fix in in Yaru

**Comment by memeplex** [comment] 2020-01-23 13:18
> @clobrano With the Ubuntu 20.04 update, wouldn't this be an important fix? It breaks dark themes on Yaru, and 20.04 is supposed to be bringing a dark theme?

AFAICS it's completely the opposite: it breaks light shell themes, upstream is supposed to work on dark shell themes.

**Comment by clobrano** [comment] 2020-01-23 13:19
Yes, sorry, I mixed up the state of the problem
