### ISSUE TITLE
gnome-shell: broken dialog box with HiDPI scaling

### ISSUE THREAD

**Issue by barmadrid** [ubuntu/yaru#1971] opened 2020-02-23 00:48 UTC
## Expected Behavior

Logout and WiFi dialog boxes appear broken (cut) with 200% scaling (HiDPI)

## Actual Behavior

See photo

![Screenshot from 2020-02-22 19-36-54](https://user-images.githubusercontent.com/61072940/75101519-a721cc00-55ab-11ea-9a14-8d1d5cbc5dbb.png)

## Software that presents the issue

Archlinux with latest updates

## Yaru version

Git version [yaru-git](https://aur.archlinux.org/pkgbase/yaru-git/)

**Comment by Feichtmeier** [comment] 2020-02-23 00:57
Should be caused by yet the missing gnome shell update. 
For each change in the scss there is mostly a corresponding change in the JavaScript used in the shell. This time we had the scss before the shell update landed in focal daily. Other issues are the stretched font and the missing system menu.

**Comment by Feichtmeier** [comment] 2020-02-23 09:24
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/942/diffs

This code needs to land in Ubuntu daily, then it works.

**Closed by Feichtmeier** 2020-02-23 09:24 UTC
