### ISSUE TITLE
Gparted won't have yaru theme under ubuntu 18.04

### ISSUE THREAD

**Issue by zhangzp9970** [ubuntu/yaru#1297] opened 2019-03-31 15:08 UTC
Hi,I found that gparted looks ugly when using communitheme on Ubuntu 18.04.:disappointed:here is the screenshot.
![Screenshot from 2019-03-31 22-51-42](https://user-images.githubusercontent.com/30102054/55290759-cea6fd80-5409-11e9-9698-a6527c9cc610.png)

**Comment by zhangzp9970** [comment] 2019-03-31 15:09
Besides, I also hope we could have a OneDrive icon!

**Comment by clobrano** [comment] 2019-03-31 17:53
Hi @zhangzp9970, thanks for taking time to contribute to the project.

Since gparted looks fine in 19.04, I think it is a problem with the snap, and probably the same root cause as #1193, since gparted starts as root.

/cc @jhenstridge

**Comment by zhangzp9970** [comment] 2019-04-08 14:42
yeah!, you are correct! It is just because gparted started as root. yaru theme with snap won't support applications started as root. Take gnome-clocks as an example,here is the screenshot

**Comment by zhangzp9970** [comment] 2019-04-08 14:44
![Screenshot from 2019-04-08 22-39-09](https://user-images.githubusercontent.com/30102054/55733025-a5aceb00-5a4f-11e9-8dc6-c6493d1e11ee.png)
this is gnome-clocks started as root. It is apparent that the theme didn't work

**Comment by zhangzp9970** [comment] 2019-04-08 14:47
Besides, applications start much slower when running as root, i don't know why.

**Comment by clobrano** [comment] 2019-04-14 07:37
Okay, let's close this then, since there's already #1193 and it's not Yaru dependent

**Closed by clobrano** 2019-04-14 07:37 UTC
