### ISSUE TITLE
Hover and press effect on tabs looks better in Adwaita

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2109] opened 2020-03-25 09:50 UTC
### Steps to reproduce the problem
1. Install geany (sudo apt install geany)
2. Hover the mouse pointer and press on the left and bottom tabs, including the arrow tabs
3. Change theme between Yaru and Adwaita

![Hover_Press](https://user-images.githubusercontent.com/45657128/77522785-188fbb80-6e85-11ea-8922-f001fccd0d38.gif)

Notice the difference in the hover and press effect, especially on the arrow tabs, between Yaru and Adwaita. In my opinion, Adwaita looks better.

Notice that clicking twice on a tab does not draw a dotted rectangle around it, which indicates that the tab has keyboard focus. Go up, down, left, right; the dotted rectangle moves along. Adwaita does that, Yaru does not.

### Software that presents the issue
- Name: geany
- Version: 1.36

### Yaru version
apt show yaru-theme-gtk
Package: yaru-theme-gtk
Version: 20.04.4

**Comment by Feichtmeier** [comment] 2020-03-25 14:51
This is exactly the hover effect @madsrh and @clobrano wanted by design, so I'll close this

**Closed by Feichtmeier** 2020-03-25 14:51 UTC

**Comment by Amr-Ibra** [comment] 2020-03-25 14:56
But clicking twice on a tab does not draw a dotted rectangle around it, which indicates that the tab has keyboard focus. Go up, down, left, right; the dotted rectangle moves along. Adwaita does that, Yaru does not.

**Comment by clobrano** [comment] 2020-03-25 14:58
If you notice, the tab doesn't really have the outline. Once it is selected, it is on focus

**Comment by Amr-Ibra** [comment] 2020-03-25 17:52
The dotted rectangle is needed for keyboard navigation. If the keyboard focus is somewhere, and you use only the Tab key to switch the focus around the elements, you wouldn't know where the focus stands at the moment.

That also applies to Nautilus:
1. Open many tabs in Nautilus
2. Focus the keyboard in the file area
3. Switch the focus with the Tab key around all Nautilus elements
4. Observe that the tabs do not indicate whether they have keyboard focus or not
5. Now try the same thing with Adwaita

**Comment by clobrano** [comment] 2020-03-25 18:16
What I meant is that, when we discussed this, we observed that the selected tab and the dotted rectangle seems to always go together. Do you observe a different behaviour in adwaita?

**Comment by Amr-Ibra** [comment] 2020-03-25 19:05
> Do you observe a different behaviour in adwaita?

Yes, don't use the mouse and use only the keyboard. Follow the steps I mentioned for nautilus and switch the focus using the `Tab` key.

**Comment by clobrano** [comment] 2020-03-25 19:40
I think there is a misunderstanding. What I meant is that the tab selection and focus ring are always together. There is no way, as far as I can tell, to have the focus ring on an unselected tab

![tab-focus](https://user-images.githubusercontent.com/2883614/77577790-b0b69080-6ed7-11ea-8810-fa19f951aef7.gif)

The dotted rectangle is redundant here.

The same is done for the entry, no dashed rectangle as well
![entry-focus](https://user-images.githubusercontent.com/2883614/77578246-81ecea00-6ed8-11ea-8b98-d20d3e907031.gif)

**Comment by Amr-Ibra** [comment] 2020-03-25 23:38
OK, now:
1. move the focus into the side panel in Nautilus (by clicking on Documents for example)
2. using only the keyboard, rotate the focus ring between all elements and buttons in Nautilus using the `Tab` key (press repeatedly)
3. using only the keyboard, try to get the focus ring on a tab
4. how do you know that the focus ring is on a tab using only the `Tab` key if you don't see it? And you don't know whether the tab is selected or not?

**Comment by clobrano** [comment] 2020-03-26 07:37
What you mean is that there is no evident transition between a tab selected and a tab that "just got the focus"?

**Comment by Feichtmeier** [comment] 2020-03-26 08:00
I guess he means that when you alt+tab out and in again to nautilus, you don't know what widget has the focus if the focus is on the tab because we've made it invisible

**Comment by Amr-Ibra** [comment] 2020-03-26 08:00
> What you mean is that there is no evident transition between a tab selected and a tab that "just got the focus"?

YES.

And now apply the same analogy to file/folder icons in Nautilus using your own screencast. You will see that in there is a transition between a file selected (blue highlight only on the file name) and a file that "just got the focus" (blue highlight on both file name and icon). Adwaita does that, Yaru does not.

**Comment by Feichtmeier** [comment] 2020-03-26 08:03
We can bring back the focus ring to the tab and the nautilus widgets but then please make a new issue for this, we want the hover effect on tabs to only change the "underline", by design. We like this design.
