### ISSUE TITLE
Pixelated icon for "program error"

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#1210] opened 2019-02-25 09:42 UTC
Ubuntu 18.04 Yaru stable snap

I got this dialog after starting Ubuntu. It says something about " reporting system program error".
The icon corresponding to that error dialog looks weird.
![zrzut ekranu z 2019-02-24 22-07-01](https://user-images.githubusercontent.com/1629120/53328331-9fb8db80-38e1-11e9-9ba5-7e6a264c2aaa.png)

**Comment by clobrano** [comment] 2019-02-25 09:48
Thanks @mivoligo! We should check if that icon has committed with all the needed sizes

**Comment by Feichtmeier** [comment] 2019-02-25 13:08
I made a symlink from apt-daemon-download to update-notifier, which is basically only a background process without a UI. I think it was a stupid idea. /selfslap
Now that update-notifier crashes and maybe gnome shell takes the item out of some cache and since it is only a background process it only has that super small icon from the system monitor? Just an idea because I checked the symlinks in the 256 folder and it is there.
I would suggest to just remove the symlink and call it a day since there is no App (frontend) for update-notifier

**Comment by Feichtmeier** [comment] 2019-02-28 11:06
Made a test symlinks to software-updatr just to see if it is caused by something technical but it is not:
![image](https://user-images.githubusercontent.com/15329494/53561852-e5fa7e80-3b1d-11e9-8237-76ce395cc8b1.png)

But when one selected the humanity icon theme, which uses SVGs andnot PNGs it looks fine:
![image](https://user-images.githubusercontent.com/15329494/53561941-222ddf00-3b1e-11e9-9779-35b4a9160b4d.png)

I guess since this program is only a background-process it takes the icon from within the background-process "cache" or something
![image](https://user-images.githubusercontent.com/15329494/53562203-cdd72f00-3b1e-11e9-88a7-a57ea8be00b0.png)

Imho it's quiet a low prio but it surely looks awkward. Either we remove the symlinks thus fallback to humanity and having an old  but properly rendered svg icon, or keep as it is and hope the program does not crash anymore in the future ;D
@clobrano @madsrh  opinions?

**Comment by mivoligo** [comment] 2019-02-28 11:40
It's probably not related to Yaru but I've got this message every day when I start Ubuntu. I've no idea how to find out what is the real problem as the message is not helpful at all.

**Comment by fitojb** [comment] 2019-02-28 12:19
> It's probably not related to Yaru but I've got this message every day when I start Ubuntu. I've no idea how to find out what is the real problem as the message is not helpful at all.

The dialog comes from update-notifier, which calls apport

**Comment by ubuntujaggers** [comment] 2019-03-11 22:14
@feichtmeier Personally I think removing the symlink and falling back to Humanity would be better in this case, I've seen it a few times myself now and IMO an old icon is better than a pixellated one?

**Closed** 2019-03-14 10:34 UTC
