### ISSUE TITLE
Cursors not showing up on 18.04 with snap

### ISSUE THREAD

**Issue by galgalesh** [ubuntu/yaru#886] opened 2018-10-03 09:47 UTC
I was looking into the issues with the Yaru cursors in snaps and I bounced up against some weird stuff. I'd like to get a sanity check from the other Yaru devs.

On my system, 18.04 with the `communitheme` snap, the `communitheme` cursors aren't used. It doesn't matter if I chose `Suru` or `communitheme` as cursor theme in Gnome Tweak.

When I manually copy `/snap/communitheme/current/share/icons/communitheme/` to `/usr/share/icons`, then the `communitheme` cursors suddenly show up.

It's easy to see if you're using the `communitheme` cursors or not: the default is a white cursor, the `communitheme` one is a black cursor.

Is anyone else experiencing this issue? Do we know the cause?

```
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: 2 days ago, at 16:52 CEST
channels:                    
  stable:    0.1 (1226) 17MB -
  candidate: ↑               
  beta:      ↑               
  edge:      0.1 (1226) 17MB -
installed:   0.1 (1226) 17MB -

```

**Comment by Feichtmeier** [comment] 2018-10-03 10:45
I am not facing this issue on neither of my snap installations in our house (3x 18.04 snaps)

Did you try to reinstall it?

**Comment by galgalesh** [comment] 2018-10-03 11:10
@Feichtmeier, just as a sanity check, can you show the output of the following command, to make sure that you don't have a local `communitheme` installation that's being used?

`find / -name "[cC]ommunitheme" 2>&1 | grep -v "Permission denied"`

Output on my system:

```
/usr/share/gnome-shell/theme/communitheme
/snap/gtk-common-themes/733/share/icons/communitheme
/snap/gtk-common-themes/733/share/sounds/communitheme
/snap/gtk-common-themes/733/share/themes/Communitheme
/snap/gtk-common-themes/734/share/icons/communitheme
/snap/gtk-common-themes/734/share/sounds/communitheme
/snap/gtk-common-themes/734/share/themes/Communitheme
/snap/gtk-common-themes/743/share/icons/communitheme
/snap/gtk-common-themes/743/share/sounds/communitheme
/snap/gtk-common-themes/743/share/themes/Communitheme
/snap/communitheme
/snap/communitheme/1208/share/gnome-shell/theme/Communitheme
/snap/communitheme/1208/share/icons/communitheme
/snap/communitheme/1208/share/sounds/communitheme
/snap/communitheme/1208/share/themes/Communitheme
/snap/communitheme/1218/share/gnome-shell/theme/Communitheme
/snap/communitheme/1218/share/icons/communitheme
/snap/communitheme/1218/share/sounds/communitheme
/snap/communitheme/1218/share/themes/Communitheme
/snap/communitheme/1226/share/gnome-shell/theme/Communitheme
/snap/communitheme/1226/share/icons/communitheme
/snap/communitheme/1226/share/sounds/communitheme
/snap/communitheme/1226/share/themes/Communitheme
/var/snap/communitheme
```

**Comment by Feichtmeier** [comment] 2018-10-03 11:19
´´´bash
frederik@xps:~$ find / -name "[cC]ommunitheme" 2>&1 | grep -v "Permission denied"
/home/frederik/no-title-bar/themes/Communitheme
/home/frederik/snap/gnome-calculator/199/.local/share/icons/communitheme
/home/frederik/snap/gnome-calculator/238/.local/share/icons/communitheme
/home/frederik/snap/gnome-calculator/222/.local/share/icons/communitheme
/home/frederik/snap/gnome-contacts/69/.local/share/icons/communitheme
/home/frederik/snap/libreoffice/83/.local/share/icons/communitheme
/home/frederik/snap/libreoffice/84/.local/share/icons/communitheme
/home/frederik/snap/libreoffice/80/.local/share/icons/communitheme
/home/frederik/snap/gnome-logs/19/.local/share/icons/communitheme
/home/frederik/snap/gnome-logs/43/.local/share/icons/communitheme
/home/frederik/snap/gnome-logs/40/.local/share/icons/communitheme
/home/frederik/snap/gnome-calendar/48/.local/share/icons/communitheme
/home/frederik/snap/spotify/21/.local/share/icons/communitheme
/home/frederik/snap/gnome-characters/103/.local/share/icons/communitheme
/home/frederik/snap/gnome-characters/124/.local/share/icons/communitheme
/home/frederik/snap/gnome-characters/117/.local/share/icons/communitheme
/home/frederik/snap/gnome-system-monitor/54/.local/share/icons/communitheme
/home/frederik/snap/gnome-system-monitor/28/.local/share/icons/communitheme
/home/frederik/snap/gnome-system-monitor/57/.local/share/icons/communitheme
/usr/share/icons/communitheme
/var/snap/communitheme
/snap/gtk-common-themes/319/share/icons/communitheme
/snap/gtk-common-themes/319/share/sounds/communitheme
/snap/gtk-common-themes/319/share/themes/Communitheme
/snap/gtk-common-themes/701/share/icons/communitheme
/snap/gtk-common-themes/701/share/sounds/communitheme
/snap/gtk-common-themes/701/share/themes/Communitheme
/snap/communitheme
/snap/communitheme/1227/share/gnome-shell/theme/Communitheme
/snap/communitheme/1227/share/icons/communitheme
/snap/communitheme/1227/share/sounds/communitheme
/snap/communitheme/1227/share/themes/Communitheme
/snap/communitheme/1230/share/gnome-shell/theme/Communitheme
/snap/communitheme/1230/share/icons/communitheme
/snap/communitheme/1230/share/sounds/communitheme
/snap/communitheme/1230/share/themes/Communitheme
/snap/communitheme/1232/share/gnome-shell/theme/Communitheme
/snap/communitheme/1232/share/icons/communitheme
/snap/communitheme/1232/share/sounds/communitheme
/snap/communitheme/1232/share/themes/Communitheme
frederik@xps:~$ 
´´´

**Comment by Feichtmeier** [comment] 2018-10-03 11:39
Still strange though. Could you test if this happens on a fresh 18.04 install in a VM, too?

_(((If you search for the one from 2017 it is not that expensive anymore like the new ones)))_

**Comment by Feichtmeier** [comment] 2018-11-08 10:11
@galgalesh apart from snaps that didn't update their gtk common themes yet (line Spotify) the cursor works everywhere for me.
Could you check again what happens on a fresh install?

**Comment by Feichtmeier** [comment] 2018-11-14 21:09
Closing this now as I can not reproduce this and I use bionic with our communitheme snap since months :) Feel free to reopen it!

**Closed** 2018-11-14 21:09 UTC
