### ISSUE TITLE
Wifi icon reverts to the old one for a second

### ISSUE THREAD

**Issue by diegoparkingdoor** [ubuntu/yaru#787] opened 2018-09-06 09:43 UTC
## Expected Behavior

Swapping from a wifi network to another changes the icon state from fully conected to the "awaiting to connect" status and then back to "fully conected"

## Actual Behavior

The wifi icon sometimes change to the old one (the cone split in bars instead of the solid cone) during a brief lapse of time between less than a second to several seconds.

## Steps to Reproduce the Problem

Change the wifi network.

**Comment by Feichtmeier** [comment] 2018-09-06 09:46
Yes I noticted this too! Very strange indeed. It is also some icon that does not look like suru. Maybe there is an icon missing or something?
Would be cool if we could investigate if this is caused by a missing icon (thus fallbacking to some other icon) or by a bug in gnome shell (which I dont think)
If it's a missing icon this would be something for @snwh 's suru repo

**Comment by eaglersdeveloper** [comment] 2018-09-06 11:42
This is the network-wireless-symbolic icon. I have long created a [issue in snwh's repository](https://github.com/snwh/suru-icon-theme/issues/8).

![](https://camo.githubusercontent.com/d35e64f4b22dba738b3a11966fe7779f22b12f58/68747470733a2f2f692e696d6775722e636f6d2f53505a44336b442e706e67)

**Comment by Feichtmeier** [comment] 2018-09-06 11:47
Okay thanks for the clarification. 
Hm, could you push an icon to our repository? UI Freeze is soon and this is really a bigger issue in my opinion. If snwh likes he you could push it to his repo some day, too

**Comment by eaglersdeveloper** [comment] 2018-09-06 12:31
But we need to choose which icon to use. In the Ubuntu Touch and the network selection window are different icons. In addition, this icon is displayed in the status bar, as mentioned above.

**Comment by Feichtmeier** [comment] 2018-09-07 06:43
But you can confirm that there is an icon missing for the status bar? Because that's what the issue is about.

**Comment by Feichtmeier** [comment] 2018-11-09 09:03
I think you linked the wrong issue
This one seems the correct one: https://github.com/snwh/suru-icon-theme/issues/86
And sams answer is, that the icon is not missing, I'll close this one here - please let's discuss this upstream.

**Closed by Feichtmeier** 2018-11-09 09:03 UTC
Labels: icon theme
