### ISSUE TITLE
I can only see limited applications on ubuntu-dock

### ISSUE THREAD

**Issue by alculete** [ubuntu/yaru#973] opened 2018-11-18 14:40 UTC
## Expected Behavior

Find my opened applications at the end bellow of ubuntu-dock

## Actual Behavior

If I have many applications opened I can't find the applications that are very bellow and not visible primarily on ubuntu docker (docker is not scrolling applications)

## Steps to Reproduce the Problem

  1. open many applications until the applications are not visible on dock when opened 
  2. Go to the end of the dock to see if it starts scrolling 

![image](https://user-images.githubusercontent.com/2129497/48674024-a8ff1300-eb50-11e8-89c9-95848fdb414d.png)

  

## Specifications
OS: Ubuntu 18.10 x86_64 
Host: HP EliteBook 8560w A0001D02 
Kernel: 4.18.0-11-generic 
Packages: 1942 (dpkg), 12 (flatpak), 34 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-2670QM (8) @ 3.100GHz 
GPU: NVIDIA Quadro 1000M 
Memory: 7833MiB / 20022MiB

**Comment by Feichtmeier** [comment] 2018-11-18 15:43
18.04 with the communitheme snap
and I can not reproduce this, works for me:
![peek 2018-11-18 16-42](https://user-images.githubusercontent.com/15329494/48674841-08f5b980-eb51-11e8-8924-078821c76acd.gif)

**Comment by clobrano** [comment] 2018-11-18 16:39
I believe I reproduced this in 18.10, however it's a dash to dock issue, not Yaru's. 
Do you mind open the same bug on its repository?

**Comment by alculete** [comment] 2018-11-19 06:53
> I believe I reproduced this in 18.10, however it's a dash to dock issue, not Yaru's.
> Do you mind open the same bug on its repository?

OK I will open it

**Comment by clobrano** [comment] 2018-11-19 07:09
Thanks! Closing this now

**Closed by clobrano** 2018-11-19 07:09 UTC
