### ISSUE TITLE
 Yaru Dark Theme text invisible in Software's app tiles when in foreground.

### ISSUE THREAD

**Issue by winyl** [ubuntu/yaru#3262] opened 2021-12-11 08:21 UTC
When turning on Yaru Dark theme on Ubuntu 20.04.03(Focal Fossa), if Software app is on top of other windows(in the foreground), the app tiles have text color matching the background of the app tile, hence the text in the app tile is not readable. Please correct!

**Expected Behavior**
I should be able to read the text in app tiles in Ubuntu Software app
**Actual Behavior**
Text is not visible, hence unreadable.

**Steps to Reproduce the Problem**
1. Open Settings app in Ubuntu
2. Click on Appearance
3. Click on Dark
4. Click on Software's window to put it in foreground
5. Click on All Tab. Put Software window fore-, background to see the effect.

**System information**
- Shell version:  GNOME 3.36.8
- OS version: Ubuntu 20.04.3 LTS
- Yaru version: 20.04.11.1
![Zrzut ekranu z 2021-12-11 08-40-24](https://user-images.githubusercontent.com/3908175/145669802-382de17f-8d97-4eea-ae0f-bba99ab4df10.png)

**Comment by Feichtmeier** [comment] 2021-12-11 08:31
Is this due to the reason that both Ubuntu versions share the same theme version in the snap? @Jupi007

**Comment by Jupi007** [comment] 2021-12-11 09:48
I'm installing a VM to see what is happening here. :)

**Comment by Jupi007** [comment] 2021-12-11 11:57
Sorry @winyl but I can't reproduce the problem with a fresh install of 20.04. I tried both gnome-software and snap-store.

Can you try to update your system:

```bash
sudo apt update && sudo apt full-upgrade
```
and also
```bash
sudo snap refresh
```

**Comment by Muqtxdir** [comment] 2022-03-12 18:40
I was on ubuntu-20.04.4 vm the other-day and this issue does not happen. @winyl please follow the instructions shared by @Jupi007 as it's most likely to get resolved by that.

**Closed by Muqtxdir** 2022-03-12 18:40 UTC
Labels: Area: gtk3
