### ISSUE TITLE
Corrupted symbolics in GtkFileChoser 

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/yaru#2630] opened 2021-02-08 18:07 UTC
### Happens when:

Spawned from vscode classic snap
With yaru build locally from master

![grafik](https://user-images.githubusercontent.com/15329494/107261940-400d5980-6a40-11eb-829b-10e14c3be3e4.png)

### Does not happen when:

Spawned from Gedit deb
and/or
With yaru deb in focal
![grafik](https://user-images.githubusercontent.com/15329494/107262340-b7db8400-6a40-11eb-915e-458db9d07488.png)

Edit: does not happen with the Adwaita icon theme, not in groovy not in focal

**Comment by Muqtxdir** [comment] 2021-02-09 07:37
hi, I tried into looking what might be causing the symbolic-svg(s) to look corrupt/distorted and I made the following assumptions and attempts:

tried on: **Ubuntu 20.4.2** and **Ubuntu 20.10**
checked apps: code , Ubuntu-software(snap-store)


### attempt 1: gtk-common-themes snap inspection:
`gtk-common-themes` snap is based on top of `core18` and some of the symbolics from the current `master` branch look corrupted/distorted on **Ubuntu 18.04** and so I snapped `gtk-common-themes` on top of `core20` base so that it uses build-packages of **Ubuntu 20.04** instead of **Ubuntu 18.04** and still the problem-exists even with doing `core20` 

### attempt 2: gtk-common-themes dependencies issue?
Maybe some dependencies for icon-themes used in `gtk-common-themes` snap need to be updated to the ones that might be causing this such as: `librsvg2-dev` (the svg-render, my guess don't know how to verify this)

### attempt 3: code issue?
The yaru icons are only affected in Ubuntu-software (snap-store) but in code even ***Adwaita*** icons are corrupted/distorted

*The **Adwaita** icons are also broken in vscode (see screenshot)*
![adwaita](https://user-images.githubusercontent.com/54065734/107316272-4e9a5600-6abe-11eb-8868-410936f14c1e.png)

### attempt 4: switch to different branch in gtk-common-themes
Wanted to check whether current `master` branch solves the issue caused by `groovy` branch, turns out the `master` branch makes it even worse (see **categories-section** icons in screenshot)
![master-branch](https://user-images.githubusercontent.com/54065734/107330317-67633580-6ad7-11eb-98ca-3783081be6f4.png)

Although I have tried all of this, still can't pinpoint to what is causing this issue on snap-based aplications

**Comment by Feichtmeier** [comment] 2021-02-11 10:51
Thank you very much @Muqtxdir 
The idea with librsvg2-dev sounds reasonable. Maybe @jhenstridge could share this opinion on this? :)

**Comment by jhenstridge** [comment] 2021-02-12 11:06
Are the actual icon files in the gtk-common-themes snap different to those you get from a regular build of the theme?  Or are we instead dealing with how different versions of GTK+friends render the same data?

If it is the first, then perhaps we could fix it by updating the snap to build against a newer base.  If it is the second, then that's probably something that would need to be dealt with in Yaru.

**Comment by Feichtmeier** [comment] 2021-02-15 10:14
> Are the actual icon files in the gtk-common-themes snap different to those you get from a regular build of the theme?

@jhenstridge yes

```
frederik@carbon:~$ snap info gtk-common-themes
name:      gtk-common-themes
summary:   All the (common) themes
publisher: Canonical✓
store-url: https://snapcraft.io/gtk-common-themes
contact:   https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues
license:   unset
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.
snap-id:      jZLfBRzf1cYlYysIjD2bwSzNtngY0qit
tracking:     latest/stable
refresh-date: 2020-11-26
channels:
  latest/stable:    0.1-50-gf7627e4 2020-11-27 (1514) 67MB -
  latest/candidate: 0.1-50-gf7627e4 2020-11-25 (1514) 67MB -
  latest/beta:      0.1-50-gf7627e4 2020-11-25 (1514) 67MB -
  latest/edge:      0.1             2020-04-17 (1503) 58MB -
installed:          0.1-50-gf7627e4            (1514) 67MB -
```

this is some months older than what is in master.

>  Or are we instead dealing with how different versions of GTK+friends render the same data?

I have no idea if gtk changed something with SVGs in the past gtk3 versions.

But I did the folllowing in focal:

- cloned yaru, copied the built Suru icon folder over to /usr/share/icons, and renamed  it to Yaru
- Now I have the exact same problem in the gtkfilechoser spawned from the vscode classic snap that I had in groovy, so it seems more and more clear that we have put  problems into our icons since the last time we've updated them in focal:
![grafik](https://user-images.githubusercontent.com/15329494/107933123-a33a4700-6f7e-11eb-965d-ba071022ade4.png)
Using my back-upped yaru dir from the focal yaru deb removes the issue again
![grafik](https://user-images.githubusercontent.com/15329494/107933289-d8df3000-6f7e-11eb-9be4-aa22e607b8ea.png)

@ubuntujaggers @Jupi007 did we mass-change any symbolics in the past months?

**Comment by Jupi007** [comment] 2021-02-15 10:19
We had rebuilt all symbolics when @clobrano did the new script (#2419 and #2474).

**Comment by Jupi007** [comment] 2021-02-15 10:31
I looked at groovy and focal branches and none of these PRs have been merged into these.

**Comment by jhenstridge** [comment] 2021-02-16 06:29
@Feichtmeier: I kicked off a pipeline build of gtk-common-themes just now, and set it to perform monthly builds even if there are no changes in the repo.  It looks like Ken disabled the CI from publishing to the edge channel some time ago, and I'm not sure why.  So for now, the rebuilt snap is only available as a CI artifact here:

https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/-/jobs/1158138/artifacts/browse

If the icons look okay with that version of the snap, then I'll make sure updating the snap is on the roadmap.  I'll also find out what we can do to allow publishing to edge again.

**Comment by Muqtxdir** [comment] 2021-02-16 07:26
> I looked at groovy and focal branches and none of these PRs have been merged into these.

thinking about this, the **inkscape** version from **focal** (inkscape ver: 0.92) to **groovy**(inkscape ver: 1.0.1) was changed which brought many changes. @Jupi007 maybe we should compare SVG(s) created using from both the versions?

**Comment by Feichtmeier** [comment] 2021-02-16 09:39
> @Feichtmeier: I kicked off a pipeline build of gtk-common-themes just now, and set it to perform monthly builds even if there are no changes in the repo. It looks like Ken disabled the CI from publishing to the edge channel some time ago, and I'm not sure why. So for now, the rebuilt snap is only available as a CI artifact here:
> 
> https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/-/jobs/1158138/artifacts/browse
> 
> If the icons look okay with that version of the snap, then I'll make sure updating the snap is on the roadmap. I'll also find out what we can do to allow publishing to edge again.

After trying the local override of /usr/share/icons/Yaru yesterday my hopes are low that this is connected to gtk-common-themes, but thank you very much for the work!

Yep, this doesn't change anything
![image](https://user-images.githubusercontent.com/15329494/108044611-c5959880-7042-11eb-9f84-86fd1e295321.png)

Aren't classic snaps independent of gtk-common-themes?

Maybe the filechoser populated from vscode has a different gtk version?
Because when I use adwaita, some old adwaita theme pops up
![image](https://user-images.githubusercontent.com/15329494/108044971-33da5b00-7043-11eb-9830-16e8b5c30fd8.png)
Compare to a filechoser spawned from the firefox snap
![image](https://user-images.githubusercontent.com/15329494/108045016-418fe080-7043-11eb-8e9c-2c92ac435d71.png)

**Comment by Feichtmeier** [comment] 2021-02-16 09:42
Ah yes, and the filechoser populated from firefox snap doesn't have this problem with yaru
![image](https://user-images.githubusercontent.com/15329494/108045341-a4817780-7043-11eb-829c-21321e862dc2.png)

So maybe we've updated something in our SVGs which is not compatible with the older gtk3 version used in the filechoser populated from the classic vscode snap

**Comment by jhenstridge** [comment] 2021-02-16 09:51
> Aren't classic snaps independent of gtk-common-themes?

Classic snaps run against the host system mount namespace.  They are often linked using an RPATH to prefer libraries distributed with the snap though, so I would not be surprised if VSCode was running against an older GTK.

I guess one thing to check would be to see if the current version of Yaru renders correctly when installed on an Ubuntu 18.04 system.

**Comment by Jupi007** [comment] 2021-02-16 09:53
If you look at Svg code:
- Master: https://github.com/ubuntu/yaru/blame/master/icons/Suru/scalable/places/user-desktop-symbolic.svg
- And focal: https://github.com/ubuntu/yaru/blame/ubuntu/focal/icons/Suru/scalable/places/user-desktop-symbolic.svg

it is clearly more refined on master ^^

**Comment by Jupi007** [comment] 2021-02-16 12:06
> I guess one thing to check would be to see if the current version of Yaru renders correctly when installed on an Ubuntu 18.04 system.

@jhenstridge 

Bingo, you're right!

18.04 using master icons:

![1](https://user-images.githubusercontent.com/36476595/108060528-48285300-7057-11eb-97f0-19c124502e6d.png)

18.04  using focal or groovy icons:

![2](https://user-images.githubusercontent.com/36476595/108060605-61c99a80-7057-11eb-95cb-c0477b6a7543.png)

Off topic but 18.04 is just like "Back to the Future" ^^

**Comment by jhenstridge** [comment] 2021-02-16 12:49
The master versions of the SVGs have gone to extremes of whitespace removal in the paths (e.g. `c-1.258.015-2.179-.03-2.931.385`).  It might be worth manually editing the spaces back into the path to see if that renders correctly on 18.04 (i.e `c -1.258 .015 -2.179 -.03 -2.931 .385`).

I wouldn't be surprised if there are some bugs in the parsing of run-on decimals in the older versions of librsvg.

**Comment by jhenstridge** [comment] 2021-02-16 13:02
In particular, Bionic has librsvg 2.40.x, which was the last release before the conversion of the library to Rust.  So there is an entirely different path parser in newer releases.  So I'd definitely try less aggressive minification.

**Comment by Jupi007** [comment] 2021-02-16 13:02
I think you're right again @jhenstridge
I tried to add spaces on minimized version and it works.
I think we should configure the script to not extremely remove white spaces.
@clobrano as you did the refresh version of this script, can you have a look to this?

**Comment by clobrano** [comment] 2021-02-16 13:52
I don't remember changing the script except to use inkscape 1.0, so I wonder if the new behaviour is due to inkscape. I'll have a look

**Comment by ubuntujaggers** [comment] 2021-02-16 14:08
Excellent diagnosis, @jhenstridge!!

I don't believe our script is at fault because the same issue affects some Adwaita symbols:

![adwaita](https://user-images.githubusercontent.com/38893390/108073795-5b8bec00-7060-11eb-8d62-a401cbf2de51.png)

So likely to be a change that Inkscape introduced which the SVG libs don't like.

**Comment by jhenstridge** [comment] 2021-02-16 15:21
@clobrano: it looks like the output is customisable in Inkscape's preferences.  Switching the path string format to something other than optimised will probably result in images that librsvg 2.40 can render:

![image](https://user-images.githubusercontent.com/12724165/108082597-3bcee500-70ad-11eb-9471-0c731d64abed.png)

**Comment by clobrano** [comment] 2021-02-16 15:34
That's a good finding. I wonder if we can set this by CLI, because our script use inkscape this way

**Comment by Jupi007** [comment] 2021-02-16 16:21
In fact the script just copy and optimize SVGs. It doesn't use Inkscape at all.
I'm sure it is caused by svgo because source SVG (/src) are not affected while those optimized yes.
It is even visible into nautilus previews:

![1](https://user-images.githubusercontent.com/36476595/108090848-643deb80-707b-11eb-9a23-c3c5a07268f0.png)
![2](https://user-images.githubusercontent.com/36476595/108090853-64d68200-707b-11eb-825d-b27c931e77b1.png)


> I don't remember changing the script except to use inkscape 1.0, so I wonder if the new behaviour is due to inkscape. I'll have a look

@clobrano Remember 😉 #2419

**Comment by clobrano** [comment] 2021-02-16 16:27
I just double checked, the Optimized option is the default, so it might be indeed the case.

> @clobrano Remember wink #2419

I do, but also https://github.com/ubuntu/yaru/pull/2419#issuecomment-711232689 -> do you think the missing trim is the root cause?

**Comment by Jupi007** [comment] 2021-02-16 16:27
There is a bug about this https://github.com/svg/svgo/issues/1317

**Comment by Jupi007** [comment] 2021-02-16 16:45
Using scour instead of svgo:

![1](https://user-images.githubusercontent.com/36476595/108093974-9b61cc00-707e-11eb-9db0-dc652abb504c.png)

I pushed a branch: https://github.com/ubuntu/yaru/tree/svg-scour

**Comment by clobrano** [comment] 2021-02-16 16:48
> There is a bug about this [svg/svgo#1317](https://github.com/svg/svgo/issues/1317)
> 
> > do you think the missing trim is the root cause?
> 
> It don't think so.

I mean, I still didn't change the process :D
Was svgo the problem, then?

**Closed** 2021-02-16 18:11 UTC
Labels: Area: icon theme, Priority: High
