### ISSUE TITLE
Missing icon for Timeshift

### ISSUE THREAD

**Issue by tosziro** [ubuntu/yaru#2517] opened 2020-12-23 11:31 UTC
There are missing icons for Timeshift and Htop. Maybe you could guys in spare time add Yaru versions of them? Right now they look like from other world. :-)

/usr/share/applications/timeshift-gtk.desktop
/usr/share/applications/htop.desktop

Im running Ubuntu 20.04 fully updated.

![missing](https://user-images.githubusercontent.com/41963712/102991814-44c29080-451a-11eb-8304-72c811ffb727.png)

**Comment by Feichtmeier** [comment] 2020-12-23 11:58
Hi @tosziro 
For both: if the creators of those apps give their ack, we can see if our icon designers have time to make something that fits
For htop: a symlink to system monitor should be enough

**Comment by Feichtmeier** [comment] 2021-02-07 15:19
@tosziro htop is merged thanks to @vitalkanev 

If you want this Timeshift icon, you need to ask those developers first, as we do not put icons into yaru that overwrite app icons against the will of their creators

**Comment by Muqtxdir** [comment] 2021-10-21 17:43
Hi @AaronTechnic 

> I believe the Timeshift developer is not against it. Linux Mint comes with timeshift preinstalled, and the dev knows that, and uses a custom icon.

could you share a screenshot of icon that is used in Linux just to confirm it. 

I think a symlink to [`backups-app`](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/apps/backups-app.svg) would be the easy-way if we want to provide an icon for timeshift

**Comment by AaronTechnic** [comment] 2021-12-29 09:21
Hi, sorry for my late response, I have not used GitHub for a while, but i will send the screenshots soon.

**Closed** 2022-03-13 17:30 UTC
Labels: Area: icon theme, Status: info-needed

**Comment by Batwam** [comment] 2022-04-20 04:15
I just installed Ubuntu 22.04 and it looks like the Backup icons is being used for the Yaru theme (HiColor theme has correct red icon). This wasn't the case in 21.10. Is this regression normal?

![image](https://user-images.githubusercontent.com/56710655/164149303-5183d345-ab2d-4b1e-b538-f2f3b78f2879.png)
