### ISSUE TITLE
[Yaru-MATE-Dark] Sticky notes have dark icons for close and resize

### ISSUE THREAD

**Issue by ahayzen** [ubuntu/yaru#2754] opened 2021-03-29 19:47 UTC
**Expected Behavior**

For the close and resize icons to be light.

**Actual Behavior**

The close and resize icons were dark, so cannot be seen easily.

**Steps to Reproduce the Problem**

1) Using Yaru-MATE-Dark right click on the panel, select Add to panel
2) Select sticky notes
3) Right click on the notes icon in the panel, select New note
4) Observe that the note has the wrong close and resize icons

**Software that presents the issue**

`stickynotes-applet`

```
$ apt policy mate-applets
mate-applets:
  Installed: 1.24.1-0ubuntu1
  Candidate: 1.24.1-0ubuntu1
  Version table:
 *** 1.24.1-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Yaru version**

This is from the hirsute/mate branch I believe (i'm using hirsute with mate).

**Screenshots**

![image](https://user-images.githubusercontent.com/3669750/112890728-2054f200-90cf-11eb-9084-47e18f9caa05.png)

With the light theme it is fine.

![image](https://user-images.githubusercontent.com/3669750/112890772-2e0a7780-90cf-11eb-9e71-3b655b84de66.png)

**Upstream check**

The Yaru-MATE-Light works OK, and other MATE themes.

**Comment by Feichtmeier** [comment] 2021-03-30 23:18
hi @ahayzen 
I wonder are those eventually not covered by our icon theme? they look like pngs or something 🤔

**Comment by ahayzen** [comment] 2021-03-30 23:24
@Feichtmeier Hmm right, looking further into this one, using different themes it seems to be always the same icon. So it might be a bug in stickynotes-applet. I'll see if i can find it in their code to see if a theme can override them or if they are fixed.

**Comment by ahayzen** [comment] 2021-03-30 23:29
@Feichtmeier Looks like it is loaded here
```
    gtk_image_set_from_icon_name (note->img_close,
                                  STICKYNOTES_STOCK_CLOSE,
                                  GTK_ICON_SIZE_MENU);
```
https://github.com/mate-desktop/mate-applets/blob/72099d70e5bd11bdd505c8e8728ea22feea79307/stickynotes/stickynotes.c#L228

Which is then defined here
```
#define STICKYNOTES_STOCK_CLOSE       "stickynotes-stock-close"
```
https://github.com/mate-desktop/mate-applets/blob/72099d70e5bd11bdd505c8e8728ea22feea79307/stickynotes/stickynotes_applet.h#L33

Which is just a png
https://github.com/mate-desktop/mate-applets/blob/master/stickynotes/pixmaps/stickynotes-stock-close.png

Note that the UI file just has `<property name="stock">gtk-missing-image</property>`, so assume that the theme cannot do anything here and I should report a bug in mate-applets ?
https://github.com/mate-desktop/mate-applets/blob/72099d70e5bd11bdd505c8e8728ea22feea79307/stickynotes/sticky-notes-note.ui#L69

**Comment by Feichtmeier** [comment] 2021-03-30 23:51
Wow thanks @ahayzen ! Really helpful
I think we could then make a symlink from our existing symbolic icons to that name

**Comment by ahayzen** [comment] 2021-03-30 23:55
@Feichtmeier That's great to hear!

I see there are the following icons
```
#define STICKYNOTES_STOCK_LOCKED      "stickynotes-stock-locked"
#define STICKYNOTES_STOCK_UNLOCKED    "stickynotes-stock-unlocked"
#define STICKYNOTES_STOCK_CLOSE       "stickynotes-stock-close"
#define STICKYNOTES_STOCK_RESIZE_SE   "stickynotes-stock-resize-se"
#define STICKYNOTES_STOCK_RESIZE_SW   "stickynotes-stock-resize-sw"
```

I guess that if possible the close and resize ones can come from the theme, but maybe there isn't an icon for lock/unlocked?

Let me know if it turns out not to be possible and I can report an issue in the applet.

**Comment by ahayzen** [comment] 2021-03-31 00:07
The only other thing to note is that you can pick a custom background and text colour for the notes, so then the yellow that is selected by default when you do a custom colour might not look good with white close icons etc.  But then if you picked a dark colour the same would happen with the built-in icons :shrug:

It feels like a more complete fix for this would be if stickynotes-applet used symbolic icons and then set the colour of the icons to whatever the text colour is - but this would be a stickynotes-applet change then :-)

**Comment by Feichtmeier** [comment] 2021-06-15 07:29
@ahayzen I think the problem is that this app does not use the symbolic icons - full color icons should not be used for those icons - maybe you could report this to the repo of the app instead?

**Comment by ahayzen** [comment] 2021-06-24 23:08
@Feichtmeier I've reported https://github.com/mate-desktop/mate-applets/issues/608 :-)

**Comment by Muqtxdir** [comment] 2022-03-12 19:53
hi @ahayzen 

since you've opened this issue at the correct-place for others to track the progress there and this being not a Yaru-issue per se, closing it.

Thanks!

**Closed by Muqtxdir** 2022-03-12 19:53 UTC
