### ISSUE TITLE
Sofware-Updater - some check buttons are cut-off 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#648] opened 2018-07-23 20:35 UTC
Communietheme : 
![communitheme](https://user-images.githubusercontent.com/37431503/43101348-d77ce4aa-8ed0-11e8-9461-ef5ced34bc62.png)
Adwaita :
![adwaita](https://user-images.githubusercontent.com/37431503/43101375-ecf2d196-8ed0-11e8-840b-c93129f21cd3.png)
Ambiance : 
![ambiance](https://user-images.githubusercontent.com/37431503/43101431-0f42d124-8ed1-11e8-9e9b-a0eed8b5571d.png)
In Cmmunitheme-dark it seems fine : - (or, is it an optic illusion?)
![screenshot from 2018-07-24 08-01-38](https://user-images.githubusercontent.com/37431503/43117947-235f16ee-8f18-11e8-82cf-4c6b946880c7.png)
  

### Icon Request

If you're filing an issue for a missing icon provide the following in your request:

- If it is an application, the file name of the icon used (can be found in the `Icon=` field in an app's `.desktop` file)
- If it is a file type icon, such as "JSON icon" please include its media type (can be found in a file's Properties dialog, e.g. `text/x-css`)
- If possible provide a screenshot, link-to, or copy of a related icon or logo.

Thanks!

**Comment by clobrano** [comment] 2018-07-24 08:06
Thanks for reporting this. I think dark variant works fine because the first icon is way smaller (the triangle) so it has enough space. In fact, playing a little with the css, there is simply not enough space in the treeview cell for big check buttons

In below picture I added a minimum left padding to show left side, but now the right side is cut

![image](https://user-images.githubusercontent.com/2883614/43124920-d464e80a-8f28-11e8-95a8-942add0a9086.png)

I did not find any way to increase the margin instead.

I'll contact update-manager maintainer to propose a change in the code to give more space, which might look this way
![image](https://user-images.githubusercontent.com/2883614/43125033-2edc988c-8f29-11e8-8dc7-d09a35d35693.png)

hopefully it will be accepted or he/she can give me some hints to solve it with css

**Comment by Feichtmeier** [comment] 2018-07-24 10:53
Would width*height work for the check boxes?

**Comment by clobrano** [comment] 2018-07-24 13:54
So far I've been able to style only treeview or treeview.view and then label or button, not  "check" directly

**Comment by Paz-it** [comment] 2018-07-24 17:17
The way I see it, the issue is the column-header that is not really functioning as such. no expanding option like normal column headers.

**Comment by CDrummond** [comment] 2018-07-25 06:45
This is a duplicate of https://github.com/ubuntu/yaru/issues/343

**Comment by clobrano** [comment] 2018-07-25 06:57
> @clobrano, The way I see it, the issue is the column-header that is not really functioning as such

I am unsure about this, since it happens only when there are two categories of updates, that is, when there is a tree inside a update row.

Thanks  @CDrummond , I can MP my change directly on the project from the bug you opened. Closing this one as well

**Closed by clobrano** 2018-07-25 06:57 UTC
