### ISSUE TITLE
top menu bar & lock screen clock's minute number get distorted 

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2802] opened 2021-04-24 07:06 UTC
**Expected Behavior**

**Actual Behavior**

**Steps to Reproduce the Problem**
if u look at units place of minutes(say 0 in 40) in clock in top menu bar & lock screen it shows the distorted number(half part of the number is not visible graphically) only happens sometimes

**System information**

**Yaru version**
yaru used in ubuntu 21.04

**Screenshots**

**Upstream check**

**Comment by Feichtmeier** [comment] 2021-04-24 07:51
Thanks!

Could you check if this also happens in Gnome-Session?
```
sudo apt install gnome-session
```
Reboot
Use the GNOME session by clicking on the white button with the ⚙️ symbol and selecting the GNOME session

**Comment by kothekarswaraj** [comment] 2021-04-24 18:24
checked it didn't happned there
it used to happen in ubuntu 20.10 and also in 21.04

**Comment by Feichtmeier** [comment] 2021-04-24 19:18
Okay this could be caused by the Ubuntu Font

**Comment by Feichtmeier** [comment] 2021-06-15 07:37
@vanvugt could you leave a comment on this one? Is this a bug in gnome shell for other fonts than cantarell?

**Comment by vanvugt** [comment] 2021-06-21 01:41
I've been assuming this is a gnome-shell bug. I had not considered the possibility that it is specific to a font, but indeed I can only find Ubuntu users reporting the issue.

Ubuntu bug: https://bugs.launchpad.net/bugs/1882291
GNOME bug: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2912

**Comment by Feichtmeier** [comment] 2021-06-21 06:41
Thanks @vanvugt !
Then we can close it here :)

**Closed by Feichtmeier** 2021-06-21 06:41 UTC
Labels: Area: GNOME-shell
