### ISSUE TITLE
Suggestion: sidebar legibity improvement

### ISSUE THREAD

**Issue by LinuxLlama** [ubuntu/yaru#2882] opened 2021-06-04 18:07 UTC
I've noticed a few people indicate that the new sidebar design featured in Ubuntu 21.04 is less easy to distinguish between selected and not selected. See the attached screenshot below. This isn't a super huge issue by any means, and I'm fine with the current design. I just wanted to throw the possibility of a refresh out there.

![Screenshot from 2021-06-04 10-40-34](https://user-images.githubusercontent.com/29968331/120843756-55445180-c523-11eb-9128-64c0cfbec00c.png)

From a design standpoint, I think the current design is slick, but it could use some improvements. Here are a couple mock-ups I created to help make the selected menu stand out.

![sidebar](https://user-images.githubusercontent.com/29968331/120843931-8d4b9480-c523-11eb-8bf1-a25c9a31ef64.png)

This first design changes the text color to orange. It also changes the text weight to bold. However, said last change isn't really necessary. The only issue I have with this design is contrast. I'd either make the background a smidge lighter or follow the second design, seen below.

![sidebar_alt](https://user-images.githubusercontent.com/29968331/120844234-f59a7600-c523-11eb-85a5-cdd8b8b80776.png)

This design, in my opinion, looks super clean and also reflects the design language of the flutter applications. While it looks nice, I'm stumped on the actual benefits of this direction. It's also inconsistent from the rest of Yaru — another reason why I'm not sold on it.

If anyone else has any suggestions or feedback regarding this matter, I'd love to hear them!

**Comment by Jupi007** [comment] 2021-06-04 18:33
hi @LinuxLlama thanks a lot for your feedback :)

We dropped the orange background because it was visually too much invasive. Brand colors shouldn't be used for so important things as text.
We previously think about put the text orange, but the problem is the dark theme: it looks very bad in terms of readability.
Our current design has got an excellent readability with both theme.

What do you think of @ubuntu/yaru-team ?

**Comment by Feichtmeier** [comment] 2021-06-04 18:38
I personally do not prefer the orange text

Keep in mind that rows totally change with libadwaita, where we will just use upstream row styling

**Comment by LinuxLlama** [comment] 2021-06-04 18:39
Excellent point, @Jupi007. It appears that the GNOME shell theme uses a lighter variant of the orange accent color — see the search bar for an example.

![Screenshot from 2021-06-04 11-37-15](https://user-images.githubusercontent.com/29968331/120848131-41035300-c529-11eb-879d-33e283b521e2.png)

Would it be possible to substitute this color for the dark theme? It might not even be a bad idea to use it in place of the standard orange color, but I'm getting ahead of myself.

**Comment by Feichtmeier** [comment] 2021-06-04 18:40
That is the "focus orange" for outline focus ring and entries

**Comment by LinuxLlama** [comment] 2021-06-04 18:42
Ah, understood. Thanks for the insight!

**Comment by Feichtmeier** [comment] 2021-06-04 18:48
![Bildschirmfoto von 2021-06-04 20-48-45](https://user-images.githubusercontent.com/15329494/120849345-4470fb80-c576-11eb-893e-c1545d557475.png)

**Comment by Feichtmeier** [comment] 2021-06-04 19:58
@LinuxLlama hi again, sorry for the rough reponse was on the fly 👋 

Do you really think that one can not see which row is selected or is this an edge case to you? 😺

**Comment by LinuxLlama** [comment] 2021-06-04 20:01
It's really an edge case. I do sometimes struggle with the low contrast on the highlight, especially in Nautilus, but that's just my poor eyesight. Honestly, this issue can be closed because the more I look at it, the less of a problem it is.

**Comment by Feichtmeier** [comment] 2021-06-04 20:10
Hm, if you have reduced eyesight do you think this is a accesability problem?
The previous white text on full orange rows is an accesibilty problem too for some people. It is hard to find a middle spot. What do you think about the libadwaita upstream row selection coming to Ubuntu soon

**Comment by LinuxLlama** [comment] 2021-06-04 20:19
It could be. I wear glasses and when I don't wear them, obviously things are blurry. If I'm not directly focused on the sidebar, the gray and white almost blend together and I have to look over to see what I've selected.

I'm not sure what the row selection is. Is it that picture you sent above? If so, the blue border actually does help my eyes see what is selected without having to look all the way over to an orange rectangle stashed on the left

**Comment by madsrh** [comment] 2021-06-04 20:26
I agree with @Feichtmeier that the orange text isn't working. I like your mockups but IMO the colored text isn't easier to distinguish between the selected and not selected.

**Comment by Feichtmeier** [comment] 2021-06-04 20:28
In flutter there is also this nice trick with material icons having always an outline and a filled version. So when you click the row the icon becomes filled, we don't have this luxury in gtk :)

**Comment by madsrh** [comment] 2021-06-06 12:33
@LinuxLlama can we close this issue?

**Comment by LinuxLlama** [comment] 2021-06-06 14:25
Yup, I'll go ahead and do that

**Closed** 2021-06-06 14:25 UTC
