### ISSUE TITLE
The colon in the lockscreen clock is square

### ISSUE THREAD

**Issue by eaglersdeveloper** [ubuntu/yaru#794] opened 2018-09-08 07:25 UTC
The colon in the lockscreen clock is square, but in Ubuntu font it is round.
After installing the `fonts-cantarell` colon is becoming round.

**Comment by eaglersdeveloper** [comment] 2018-09-08 11:30
Without Cantarell fonts in system:
![lockscreen-notification](https://user-images.githubusercontent.com/40228953/45253666-053cfe00-b37c-11e8-8124-ede3a9608cfe.jpg)
With Cantarell fonts:
![gnome-developers-fix-famous-cat-related-lock-screen-bypass-issue-in-gdm-496387-2](https://user-images.githubusercontent.com/40228953/45253671-12f28380-b37c-11e8-9575-8286095b4956.jpg)

**Comment by Feichtmeier** [comment] 2018-09-08 12:01
Very nice catch.
I wonder if this clock is using Ubuntu font at all.
I can't tell from the numbers look alone

**Comment by Feichtmeier** [comment] 2018-09-08 12:30
But as Carlo said, very doubtful that this can be fixed with css

**Comment by Feichtmeier** [comment] 2018-09-08 12:30
Did you check if this also happens in cosmic?

**Comment by eaglersdeveloper** [comment] 2018-09-08 16:14
No, I can't.

**Comment by clobrano** [comment] 2018-09-09 08:43
The problem is that Gnome shell is not using Ubuntu font in the first place.

below is how we define font preferences for Gnome shell

https://github.com/ubuntu/yaru/blob/6fe7f49b345f14bd21fbff29d7dfdef1f16dab26/gnome-shell/src/gnome-shell-sass/_common.scss#L42

The font used seems indeed to be the last one `Sans-Serif` and not Ubuntu, when Cantarell is installed is used, because it is preferred to Sans-Serif. I proved this replacing, in the line above, `Ubuntu` with another font I have installed and this way that font is used instead of Cantarell

**Comment by Feichtmeier** [comment] 2018-09-09 08:52
![image](https://user-images.githubusercontent.com/15329494/45262802-6ddcb700-b41e-11e8-99a5-369cb3dc7e88.png)

This is Ubuntu font for reference

**Comment by clobrano** [comment] 2018-09-09 08:56
Also, colon in Ubuntu font is circular, not squared

![screenshot from 2018-09-09 10-53-48](https://user-images.githubusercontent.com/2883614/45262832-f9eede80-b41e-11e8-97ea-123232ce16d2.png)

**Comment by clobrano** [comment] 2018-09-09 09:03
To me, it seems that the shell is using Ubuntu font in the panel, but not in lockscreen's clock, where it falls back to a different font, unless cantarell is installed

**Comment by Feichtmeier** [comment] 2018-09-09 09:06
what happens if we remove cantarell from the assigment

**Comment by clobrano** [comment] 2018-09-09 09:10
> what happens if we remove cantarell from the assigment

the clock keeps the squared colon

**Comment by eaglersdeveloper** [comment] 2018-09-09 10:59
Digits font is exactly Ubuntu. I recognize it everywhere.

**Comment by taciturasa** [comment] 2018-09-10 05:41
Hang on, hang on, hang on. I think I remember something relevant from the `#gnome-design` irc room; iirc, the clock uses the ratio symbol, and not the colon. Can anyone confirm that this is what's happening here, and if so, the ratio symbol in Ubuntu may be squared?

**Comment by clobrano** [comment] 2018-09-13 07:31
I tried to double check what @taciturasa said and it actually seems that Ubuntu font does not have "ratio" symbol (moreover, colon doesn't seem to be squared in Ubuntu, see below).

I think this is a font issue (missing symbol), so we can close it

![image](https://user-images.githubusercontent.com/2883614/45473103-62e39880-b736-11e8-854b-c5ea14f1b9cd.png)

**Closed by clobrano** 2018-09-13 07:31 UTC
Labels: info-needed

**Comment by eaglersdeveloper** [comment] 2018-09-16 07:06
We can create a bug report in [Ubuntu font repository in Launchpad](https://bugs.launchpad.net/ubuntu-font-family).

**Comment by clobrano** [comment] 2019-01-02 08:37
> I'd suggest try to override the default date time format to replace RATIO with COLON 

This is out of the scope of this project and gnome has a reason to use ratio instead
