### ISSUE TITLE
GTK2 Menu bar

### ISSUE THREAD

**Issue by cavillagomez** [ubuntu/yaru#1539] opened 2019-09-17 22:02 UTC
GTK2 Menu bars are white

**Comment by chrisjbillington** [comment] 2019-09-18 20:30
It's the same in GTK 3, I think it is intentional since everything is white now in the light themes.

**Comment by cavillagomez** [comment] 2019-09-18 20:54
No it isn't the same: in gtk3 is a very light gray, in gtk3 is completely white

**Comment by cavillagomez** [comment] 2019-09-18 21:01
GTK2
![Screenshot from 2019-09-18 14-57-53](https://user-images.githubusercontent.com/52009322/65185498-eceacf00-da24-11e9-8151-d16eea3fafb4.png)

GTK3
![Screenshot from 2019-09-18 14-58-59](https://user-images.githubusercontent.com/52009322/65185563-0ee45180-da25-11e9-95cf-61e2fa955401.png)

**Comment by chrisjbillington** [comment] 2019-09-18 21:22
Oh I see. You are correct.

**Comment by clobrano** [comment] 2019-09-20 14:30
Is there any other gtk2 app where you can reproduce the issue?

**Comment by cavillagomez** [comment] 2019-09-20 15:42
Audacious
![Screenshot from 2019-09-20 09-36-13](https://user-images.githubusercontent.com/52009322/65339877-386abd80-db8a-11e9-9524-c72671d80a02.png)

pgAdmin III
![Screenshot from 2019-09-20 09-36-47](https://user-images.githubusercontent.com/52009322/65339890-40c2f880-db8a-11e9-9c37-3d615c6aced5.png)

Qt5 apps with GTK+ theme support, like virtualbox
![Screenshot from 2019-09-20 09-38-37](https://user-images.githubusercontent.com/52009322/65340179-f1c99300-db8a-11e9-90d5-cbd139dcbd90.png)

**Comment by Amr-Ibra** [comment] 2019-09-28 13:16
It also affects the Bionic snap.

**Comment by Feichtmeier** [comment] 2019-10-31 10:54
Pushed the fix also to bionic @Amr-Ibra 
(edge channel)

**Comment by logix2** [comment] 2019-10-31 14:35
Could you please also fix this for Yaru-dark and GTK2 apps? GTK2 apps have a very dark menubar, while GTK3 apps have a lighter menu. 

Screenshot with Shutter (GTK2): 

![shuttermenu](https://user-images.githubusercontent.com/38005360/67956217-65d06f80-fbfc-11e9-9722-d83ef7803e75.png)

and Nemo (GTK3):
![nemo-menu](https://user-images.githubusercontent.com/38005360/67956247-6e28aa80-fbfc-11e9-8ce4-c8d00c4f3b69.png)

**Closed** 2019-11-04 05:31 UTC
Labels: Milestone: 20.04, Status: confirmed
