### ISSUE TITLE
Heavy Text-Shadows in app-notifications and gnome-shell notifications

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1661] opened 2019-12-13 11:43 UTC
Two ways to reproduce the issue:

Option 1.
Delete a file in Nautilus and look at the font in the in-app notification, that the font is blurry
![Bildschirmfoto von 2019-12-13 12-26-35](https://user-images.githubusercontent.com/45657128/70797615-22ddec00-1da5-11ea-9145-d6b3f3fa3e06.png)

Option 2.
Insert a USB stick, point the mouse to the shell notification and look at the font in the button "Open with Files", the font is blurry
![Bildschirmfoto von 2019-12-13 12-38-21](https://user-images.githubusercontent.com/45657128/70797929-e8288380-1da5-11ea-9660-c61cce3828d6.png)

$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: 12 days ago, at 13:34 CET
channels:
  stable:    0.1    2019-03-13 (1768) 16MB -
  candidate: ↑                             
  beta:      ↑                             
  edge:      29.171 2019-12-01 (1893) 18MB -
installed:   29.171            (1893) 18MB -

**Comment by Feichtmeier** [comment] 2019-12-13 12:22
Indeed thanks - forgot to fix this.

1) is the .osd styling which we dont overrwrite in our app notifications in tweaks, settings text-shadow to none should be enough
2) is the hotplug notification in the shell, we should kill all text shadows in the shell imho

**Comment by clobrano** [comment] 2019-12-17 09:58
> is the hotplug notification in the shell - could be caused by the inherit color, this is an upstream issue as we did not change this part (they just didnt see it because they dont use the light shell yet)

This is also "nice to have" in our dark variant. So any change must be done either upstream or only for the light variant

**Comment by clobrano** [comment] 2019-12-17 10:00
Sorry, I accidentally pushed the change on gtk osd directly on master

https://github.com/ubuntu/yaru/commit/1b1ef25dea8ea31b10379af7c5ad951111ff9f19

could you double check the gtk side of the issue is fixed? Thanks

**Comment by Feichtmeier** [comment] 2019-12-20 08:46
I think he can't because he uses bionic. Could you make a bionic PR for a test snap? :innocent:

**Comment by clobrano** [comment] 2019-12-20 08:52
Ok

**Comment by clobrano** [comment] 2019-12-21 09:34
please test this on bionic #1675

**Comment by Amr-Ibra** [comment] 2019-12-21 12:36
Yes, it's fixed now in nautilus app-notification.

![Bildschirmfoto von 2019-12-21 13-30-17](https://user-images.githubusercontent.com/45657128/71307972-a24b6b00-23f6-11ea-9801-4a18650f9aac.png)

**Comment by clobrano** [comment] 2019-12-26 15:30
closed by #1675

**Closed by clobrano** 2019-12-26 15:30 UTC
Labels: Area: GNOME-shell, Area: gtk3

**Comment by Amr-Ibra** [comment] 2020-01-29 21:55
Please apply the fix to Bionic. I'm using the snap version: 29.179 2020-01-16 (1949), and the fix is not there yet.
