### ISSUE TITLE
Titlebar looks wide on Unity

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ubuntu/yaru#1573] opened 2019-10-14 15:59 UTC
Some examples with Firefox and GNOME Terminal
![image](https://user-images.githubusercontent.com/13153124/66765382-ce3bf480-ee79-11e9-88da-10e5eca7c18a.png)
![image](https://user-images.githubusercontent.com/13153124/66765487-fe839300-ee79-11e9-9060-7dfdc7d2f543.png)

**Comment by clobrano** [comment] 2019-10-16 07:02
Hi @YamiYukiSenpai, thanks for contributing to Yaru. 
I believe this issue is visible in Yaru only, right? Not in Ambiance, I mean

**Comment by YamiYukiSenpai** [comment] 2019-10-16 17:06
It got fixed after I ran the update today and rebooted.

**Comment by Paz-it** [comment] 2019-10-17 04:27
@YamiYukiSenpai I think Arc have an updated metacity theme . Yaru have none and the Ambiance maybe not updated? Just guessing thou... :question:

**Comment by clobrano** [comment] 2019-11-02 21:54
Sorry for the silly question: how do I test this? Install Yaru on Unity and select it with gnome-tweaks?

**Comment by clobrano** [comment] 2019-12-16 11:29
I cannot reproduce this. @YamiYukiSenpai could you tell me if you can reproduce this using Yaru's master branch, please?

**Comment by clobrano** [comment] 2020-01-15 18:18
This is actually fixed now, probably by #1523

**Closed by clobrano** 2020-01-15 18:18 UTC
Labels: Area: Unity, Status: Not reproducible, help wanted
