### ISSUE TITLE
Remmina custom emblems icons not found when using Yaru

### ISSUE THREAD

**Issue by antenore** [ubuntu/yaru#1643] opened 2019-11-29 13:35 UTC
## Actual Behavior

We have a strange behavior with the latest versions of Remmina (see #1180 for remmina discussion).

We install our custom icons under hicolor/scalabale/emblems. (and actions as well)
Using the Yaru icon theme, default on Ubuntu 19.10, those icons are not visible:

![image](https://user-images.githubusercontent.com/5975/69871989-88fe4580-12b4-11ea-8ffb-0b6e79e7b39d.png)

With any other icon theme we don't have issues

![image](https://user-images.githubusercontent.com/5975/69871951-6704c300-12b4-11ea-8e60-585cdad9a749.png)

## Steps to Reproduce the Problem

  1. Install a avanilla ubuntu 19.10
  2. Install latest remmina.

```
sudo add-apt-repository ppa:remmina-ppa-team/remmina-next-daily
sudo apt-get update
```

  3. test with different themes (create new profiles in remmina, all protocol icons are the same)

## Software that presents the issue

- Name: Remmina
- Version: 1.3.6

## Yaru version

Please report the Yaru version in your system using one of the following commands

* If you installed Yaru from PPA

```
Package: yaru-theme-icon
Version: 19.10.4
Priority: optional
Section: misc
Source: yaru-theme
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 67.2 MB
Homepage: https://community.ubuntu.com/c/desktop/theme-refresh
Task: ubuntu-desktop-minimal, ubuntu-desktop
Supported: 9m
Download-Size: 10.9 MB
APT-Manual-Installed: no
APT-Sources: http://ch.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
Description: Yaru icon theme from the Ubuntu Community
 This is the theme that is shaped by the community on the Ubuntu hub.
 .
 This package contains the icon theme
 .
 If you want to follow development, more information here:
 https://community.ubuntu.com/c/desktop/theme-refresh.

```

Thanks!!!

cc: @madsrh @Feichtmeier @giox069

**Comment by antenore** [comment] 2019-11-29 13:59
The list of "missing icons":

```
./scalable/emblems/remmina-spice-ssh-symbolic.svg
./scalable/emblems/remmina-tool-symbolic.svg
./scalable/emblems/remmina-rdp-symbolic.svg
./scalable/emblems/remmina-www-symbolic.svg
./scalable/emblems/remmina-nx-symbolic.svg
./scalable/emblems/remmina-xdmcp-symbolic.svg
./scalable/emblems/remmina-vnc-symbolic.svg
./scalable/emblems/remmina-ssh-symbolic.svg
./scalable/emblems/remmina-sftp-symbolic.svg
./scalable/emblems/remmina-spice-symbolic.svg
./scalable/emblems/remmina-rdp-ssh-symbolic.svg
./scalable/emblems/remmina-xdmcp-ssh-symbolic.svg
./scalable/emblems/remmina-vnc-ssh-symbolic.svg
```

That is really strange, because as you don't provide those icons, Remmina should fallback to the hicolor ones, but it doesn't happen

**Comment by clobrano** [comment] 2019-11-29 14:01
Indeed, this is weird. The other icon sets provide the remmina icon as well as yaru does?

**Comment by antenore** [comment] 2019-11-29 14:08
@clobrano thanks for coming back to me.

Yes, for example the Papirus icon themes. I set it as the main and Yaru as the fallback and everything works as expected.

**Comment by antenore** [comment] 2019-11-29 14:12
The list in Papirus:

```
./Papirus/16x16/panel/remmina-panel.svg
./Papirus/16x16/apps/org.remmina.Remmina.svg
./Papirus/16x16/apps/remmina.svg
./Papirus/22x22/panel/remmina-panel.svg
./Papirus/22x22/apps/org.remmina.Remmina.svg
./Papirus/22x22/apps/remmina.svg
./Papirus/48x48/apps/org.remmina.Remmina.svg
./Papirus/48x48/apps/remmina.svg
./Papirus/24x24/panel/remmina-panel.svg
./Papirus/24x24/apps/org.remmina.Remmina.svg
./Papirus/24x24/apps/remmina.svg
./Papirus/64x64/apps/org.remmina.Remmina.svg
./Papirus/64x64/apps/remmina.svg
./Papirus/32x32/apps/org.remmina.Remmina.svg
./Papirus/32x32/apps/remmina.svg
```

**Comment by Feichtmeier** [comment] 2019-11-29 14:14
Maybe the problem is mixing the themes

The icons from the .Deb are installed into hicolor 
We are not providing a full icon set only two

@antenore did you use the icon from @ubuntujaggers as your default icon now? Or still the transparent one?

Eventually we could just drop the icons in our theme

**Comment by antenore** [comment] 2019-11-29 14:31
@Feichtmeier I'm using the main remmina icon as the default, yes.

The fallback test I've was just a test, on Ubuntu 19.10, vanilla, there's not a fallback theme beside the hicolor one, and we have that behavior.

I was wondering if we do anything wrong or if it doesn't work by design.

Interpreting the freedesktop specification it's quite subjective :-P 

Compared to Yaru we don't have all the sizes , including hidpi

**Comment by antenore** [comment] 2019-11-29 15:13
Ok, so the one icon that causes issues is the remmina-symbolic.svg, removing it form the theme solves the issue. Well I don't know if it's a solution or a workaround

**Comment by ubuntujaggers** [comment] 2019-11-30 14:55
We can stick the custom emblems in Yaru? That would fix the problem too and we get to keep the app symbol...

**Comment by antenore** [comment] 2019-11-30 15:32
@ubuntujaggers you have my blessing if needed ;-) that would fix the issue. But what if in the future we'll add new emblems? 

In any case the fallback remmina-symbolic should be removed.

**Comment by ubuntujaggers** [comment] 2019-11-30 15:41
Good point, adding the custom emblems isn't a good idea. Also if you already supply a symbol then ours is redundant, I'll take it out and do a PR tomorrow night :)

**Comment by ubuntujaggers** [comment] 2019-12-04 16:21
Hmm, this is weird - when I delete the symbolic we don't get a symbol at the top left of the screen, we get a monochrome version of the colour icon.  So we have to work out what to do, so we keep the app symbol when it's wanted but don't replace all the custom emblems with it.

**Comment by Feichtmeier** [comment] 2019-12-04 16:38
I'd say let's remove all remmina icons from yaru. 
Because your full colour icon is @antenore 's default icon now, no? Or isn't it? Sorry, I really don't know :D

**Comment by ubuntujaggers** [comment] 2019-12-04 17:23
Yeah, fair point, let's do it :+1:

**Comment by ubuntujaggers** [comment] 2019-12-04 17:30
Making the branch now - Remmina falls back to the old icon with no background - @antenore, has the version with the new icon landed in Ubuntu yet?  (Do we mind either way?)

**Comment by antenore** [comment] 2019-12-04 18:00
@ubuntujaggers yes, it is

**Closed** 2019-12-07 11:46 UTC
