### ISSUE TITLE
Snap apps (calculator, logs, system monitor) have no background, are transparent

### ISSUE THREAD

**Issue by Jakethethird** [ubuntu/yaru#1212] opened 2019-02-25 17:37 UTC
Some apps like calculator, system monitor and logs (i.e. those installed as snaps in 18.04) have no background and are completely transparent - see image. They are normal when run without communitheme. 

System info below image.

![selection_003](https://user-images.githubusercontent.com/28954472/53356660-2e524a80-392c-11e9-8c2b-f0c246ca4a9d.png)

snap list
Name                  Version           Rev   Tracking  Publisher   Notes
canonical-livepatch   8.2.0             58    stable    canonical✓  -
communitheme          0.1               1593  stable    didrocks    -
core                  16-2.37.2         6405  stable    canonical✓  core
gnome-3-26-1604       3.26.0            78    stable/…  canonical✓  -
gnome-calculator      3.30.1            260   stable/…  canonical✓  -
gnome-characters      3.30.0            139   stable/…  canonical✓  -
gnome-logs            3.30.0            45    stable/…  canonical✓  -
gnome-system-monitor  3.30.0            57    stable/…  canonical✓  -
gtk-common-themes     0.1-7-g1feddba    1122  stable/…  canonical✓  -
nextcloud-client      2.3.3+gitab40efe  10    stable    nextcloud✓  -
qownnotes             19.2.5            1874  stable    pbek        -
skype                 8.34.0.78         66    stable    skype✓      classic

snap    2.37.2
snapd   2.37.2
series  16
ubuntu  18.04
kernel  4.15.0-45-generic

System:    Host: abc-5050 Kernel: 4.15.0-45-generic x86_64 bits: 64 Desktop: Gnome 3.28.3
           Distro: Ubuntu 18.04.2 LTS
Machine:   Device: desktop System: Dell product: OptiPlex 5050 serial: N/A
           Mobo: Dell model: 0FDY5C v: A00 serial: N/A UEFI: Dell v: 1.10.2 date: 08/09/2018
CPU:       Quad core Intel Core i5-7500 (-MCP-) cache: 6144 KB
           clock speeds: max: 3800 MHz 1: 3246 MHz 2: 2882 MHz 3: 2812 MHz 4: 2912 MHz
Graphics:  Card: Intel HD Graphics 630
           Display Server: x11 (X.Org 1.19.6 ) driver: i915 Resolution: 1920x1200@59.95hz, 2560x1440@59.95hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2) version: 4.5 Mesa 18.2.2
Audio:     Card-1 Intel 200 Series PCH HD Audio driver: snd_hda_intel Sound: ALSA v: k4.15.0-45-generic
           Card-2 Logitech Webcam Pro 9000 driver: USB Audio
Network:   Card: Intel Ethernet Connection (5) I219-V driver: e1000e
           IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full mac: d8:9e:f3:47:15:2c
Drives:    HDD Total Size: 2512.5GB (43.5% used)
           ID-1: /dev/sda model: TOSHIBA_KSG60ZSE size: 512.1GB
           ID-2: USB /dev/sdb model: Elements_10B8 size: 2000.4GB
Partition: ID-1: / size: 467G used: 276G (63%) fs: ext4 dev: /dev/dm-1
           ID-2: /boot size: 705M used: 148M (23%) fs: ext4 dev: /dev/sda2
           ID-3: swap-1 size: 1.03GB used: 0.00GB (0%) fs: swap dev: /dev/dm-2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: 29.8C mobo: 27.8C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 322 Uptime: 9:03 Memory: 3560.8/15904.8MB Client: Shell (bash) inxi: 2.3.56

**Comment by Feichtmeier** [comment] 2019-02-25 18:07
try to install gtk-common-themes, reboot and see if that works
snap install gtk-common-themes

**Comment by Jakethethird** [comment] 2019-02-26 09:00
Hello,
It is already installed - see my "snap list" output: 
gtk-common-themes 0.1-7-g1feddba 1122 stable/… canonical✓ -

Thanks,
Jake.

**Comment by Feichtmeier** [comment] 2019-02-26 09:32
Well, there was some fix for that but I don't remember it 🤷‍♂️  Please search the old issues for snap tags, this came and it is def. **fixable** and mostly it does not even occur on most installations. 
@clobrano do you remember the fix for this?

**Comment by Feichtmeier** [comment] 2019-02-26 09:41
Did you log into the communitheme session?

**Comment by clobrano** [comment] 2019-02-26 09:53
The fix was actually install gtk-common-theme. I happen to have the very same installed applications and versions and it works fine :|

**Comment by Jakethethird** [comment] 2019-02-26 09:53
Yes I logged in to the communitheme session and see all the nice theming and icons. All the apps work fine, except the snaps mentioned with their transparencies. Logging out and logging back in with the original session give correctly working snap apps, so it is due to the communitheme. Btw, I am using X and not Wayland.

Thanks,
Jake

**Comment by Feichtmeier** [comment] 2019-02-26 09:57
Hm, try to remove the communitheme snap and reboot, install again and reboot?

**Comment by Jakethethird** [comment] 2019-02-26 10:10
Removed, rebooted, installed, rebooted, logged into Communitheme. Remains transparent. 

I then snap refreshed to --edge, rebooted and it stays transparent.

If I log in via the Wayland session, it is fine. Just X gives this problem.

Jake.

**Comment by Feichtmeier** [comment] 2019-02-26 10:12
What if you refresh or reinstall the transparent snaps?

**Comment by Jakethethird** [comment] 2019-02-26 10:33
Yes, removing and then reinstalling the transparent snaps worked. I guess it was re-making the connnections to the other system snaps (gtk-common-themes?) that gave the solution.

**Comment by Feichtmeier** [comment] 2019-02-26 10:34
Awesome! Thank you for staying so communicative :)

**Comment by marcbone** [comment] 2019-02-26 22:20
Are you sure this should be closed? I have the same issue and it is speciffic to the communitheme. Other themes dont have these problems. And I am not the only one with this issue [(askubuntu)](https://askubuntu.com/questions/1029890/transparent-system-monitor-ubuntu-18-04). Why does this only happen for the communitheme?

**Comment by Feichtmeier** [comment] 2019-02-27 05:41
I think communitheme (i.e. Yaru) is the only theme around which you can install via snap.
To test the theme while we develop it the snap was introduced for 18.04, because the theme was not ready by then.
Since 18.10 it comes just preinstalled as a .deb in every Ubuntu, so no need for the snap.

If this really happens more often we can ask @jhenstridge what to do
The initial issue was fixed some month ago by a connection between gtk-common-themes and the communitheme snap. (I think that's how it was, could be wrong though)

**Comment by clobrano** [comment] 2019-02-27 08:03
> Are you sure this should be closed? I have the same issue and it is speciffic to the communitheme. Other themes dont have these problems. And I am not the only one with this issue [(askubuntu)](https://askubuntu.com/questions/1029890/transparent-system-monitor-ubuntu-18-04). Why does this only happen for the communitheme?

The link you posted is quite old with a solution accepted. As @Feichtmeier said, feel free to reopen this  (or open a new one) if you experience it again and the solution does not work

**Comment by cassianomon** [comment] 2019-02-27 12:25
@Jakethethird what are the commands for reinstalling the snaps?

**Comment by Jakethethird** [comment] 2019-02-27 12:33
`snap remove gnome-calculator`
then
`snap install gnome-calculator`
Each time you are prompted for your password. 
Repeat for gnome-system-monitor, gnome-logs and gnome-characters
Upon reinstallation, the programs connect with the gtk-common-themes package and all is fine afterwards.
Jake.

**Comment by cassianomon** [comment] 2019-02-27 13:21
Worked, thank you!

**Comment by nicorikken** [comment] 2019-03-06 06:49
This solution worked for me initially, but as I switched to the communitheme-dark, the issues reappeared. Reinstalling the application didn't solve this. Switching back to the light theme did.
Could it be that this issue needs a separate fix for the dark theme?

**Comment by Jakethethird** [comment] 2019-03-06 08:13
I also tried the dark theme, then switched back it as it was too buggy. This might be the reason - that it does not integrate well with the gtk-common-themes package. Communitheme as a snap is only for 18.04, so I think the level of refinement is less than for later versions where it is a deb.

**Comment by clobrano** [comment] 2019-03-06 09:51
It's actually the other way around. Snap always takes the latest bits, while 18.10 deb is updated only some times. Could you both please tell me more about the system?

Like:

`$ snap list`
`$ snap info communitheme`
`$ snap info gtk-common-themes`

thank you for contributing :wink:

**Comment by clobrano** [comment] 2019-03-06 10:08
In the meantime, I can confirm that on dark variant the issue is still there

**Comment by Jakethethird** [comment] 2019-03-06 11:39
**snap list**
Name                  Version           Rev   Tracking  Publisher   Notes
canonical-livepatch   8.2.0             58    stable    canonical✓  -
communitheme          0.1               1725  edge      didrocks    -
core                  16-2.37.2         6405  stable    canonical✓  core
gnome-3-26-1604       3.26.0.20190228   82    stable/…  canonical✓  -
gnome-calculator      3.30.1            260   stable    canonical✓  -
gnome-characters      3.30.0            139   stable    canonical✓  -
gnome-logs            3.30.0            45    stable    canonical✓  -
gnome-system-monitor  3.30.0            57    stable    canonical✓  -
gtk-common-themes     0.1-16-g2287c87   1198  stable/…  canonical✓  -
nextcloud-client      2.3.3+gitab40efe  10    stable    nextcloud✓  -
qownnotes             19.3.0            1878  stable    pbek        -
skype                 8.34.0.78         66    stable    skype✓      classic

**snap info communitheme**
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will
  become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on
  Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select
  the "Ubuntu with communitheme snap" session from the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: 2 days ago, at 14:24 CET
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-03-04 (1725) 17MB -
installed:   0.1            (1725) 17MB -

**snap info gtk-common-themes**
name:      gtk-common-themes
summary:   All the (common) themes
publisher: Canonical✓
license:   unset
description: |
  A snap that exports the GTK and icon themes used on various Linux distros.
snap-id:      jZLfBRzf1cYlYysIjD2bwSzNtngY0qit
tracking:     stable/ubuntu-18.04
refresh-date: yesterday at 18:01 CET
channels:
  stable:    0.1-16-g2287c87 2019-03-05 (1198) 37MB -
  candidate: 0.1-16-g2287c87 2019-03-01 (1198) 37MB -
  beta:      0.1-16-g2287c87 2019-03-01 (1198) 37MB -
  edge:      0.1             2019-03-04 (1218) 41MB -
installed:   0.1-16-g2287c87            (1198) 37MB -

**Comment by jhenstridge** [comment] 2019-03-07 08:29
> If this really happens more often we can ask @jhenstridge what to do
> The initial issue was fixed some month ago by a connection between gtk-common-themes and the communitheme snap. (I think that's how it was, could be wrong though)

The communitheme snap shouldn't have any bearing on how snap applications appear: they'd be using the copy of the theme from gtk-common-themes (which is in turn is just symlinked to Yaru).

@Jakethethird: just to help narrow things down further, could you provide the output of the following two commands:

    gsettings get org.gnome.desktop.interface gtk-theme
    gsettings get org.gnome.desktop.interface icon-theme

**Comment by Jakethethird** [comment] 2019-03-07 08:39
jake@jtt-5050:~$ gsettings get org.gnome.desktop.interface gtk-theme
'Communitheme'
jake@jtt-5050:~$ gsettings get org.gnome.desktop.interface icon-theme
'Suru'

As of yesterday, the same issue started on my laptop (Thinkpad, Ubuntu 18.04). Previously it was on my work PC (Dell Optiplex 5050, Ubuntu 18.04) Removal and installation of the snaps fixed it as before.

**Comment by Feichtmeier** [comment] 2019-05-03 07:05
I installed the snap on many apps in the past months and I never encountered this issue again - are we sure this still happens to new installations? If no I would like to close this

**Comment by clobrano** [comment] 2019-05-03 07:12
I have a problem updating `gtk-common-themes` so this might be the reason, but this is how it looks in my  18.04 right now (communitheme rev1789, gtk-common-themes x1)

![image](https://user-images.githubusercontent.com/2883614/57123813-8588f700-6d83-11e9-8458-9b67158a57dc.png)

I'll try to reinstall the VM and update the status

**Comment by clobrano** [comment] 2019-05-03 09:21
Confirm it is reproducible on 18.04.2 (even in communitheme edge, tested later)

![image](https://user-images.githubusercontent.com/2883614/57128980-757a1300-6d95-11e9-97ff-4a88875663b8.png)

**Comment by clobrano** [comment] 2019-05-03 09:25
@jhenstridge, it looks like a permission problem on communitheme-dark. Running from command line I see this log

> carlo@bionic:~$ gnome-calculator 
> 
> (gnome-calculator:2806): Gtk-WARNING **: 11:21:30.446: Theme parsing error: gtk.css:1:0: Failed to import: Error opening file /snap/communitheme/current/share/themes/Communitheme-dark/gtk-3.20/gtk.css: Permission denied
> Fontconfig warning: "/etc/fonts/conf.avail/53-monospace-lcd-filter.conf", line 10: Having multiple values in <test> isn't supported and may not work as expected
> shm_open() failed: Permission denied

that file is a symlink

> carlo@bionic:~$ ll /snap/communitheme/current/share/themes/Communitheme-dark/gtk-3.20/gtk.css 
> lrwxrwxrwx 1 root root 40 mag  3 10:42 /snap/communitheme/current/share/themes/Communitheme-dark/gtk-3.20/gtk.css -> ../../Communitheme/gtk-3.20/gtk-dark.css

**Comment by clobrano** [comment] 2019-05-05 09:50
Opened a bug on gtk-common-themes, closing this for now, we'll reopen if we can do something about it

https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues/12

**Closed by clobrano** 2019-05-05 09:50 UTC
