### ISSUE TITLE
Calendar UI is not perfect. 

### ISSUE THREAD

**Issue by abhichaurasiya2022** [ubuntu/yaru#3615] opened 2022-04-24 10:52 UTC
The UI of calendar section on top bar is not perfect.
It looks good until I select date of next month.
After selecting date of next month the notification centre height gets reduced. 

 
![Screenshot from 2022-04-24 16-18-21](https://user-images.githubusercontent.com/61798241/164972904-860f5861-42ea-4d61-8496-05bb6639605b.png)

**Comment by Jupi007** [comment] 2022-04-30 08:12
Hi @abhichaurasiya2022,
thanks very much for this issue!

Could you try the following things:
- it looks like your using some extensions, maybe this problem is related to them ;
- did you tried the `gnome-session`? You can install it with `sudo apt install gnome-session`, then logout and select `Gnome` when login.

Also which version of Yaru and Ubuntu are you using?

**Comment by LeFloatyPancake** [comment] 2022-05-02 02:45
I tried both the default and yaru shell theme on openSUSE tumbleweed + GNOME 42 and I can reproduce the issue regardless of which shell theme I use. This seems to be a gnome-shell issue.

![image](https://user-images.githubusercontent.com/83509112/166178259-5afeab10-2fe4-4aae-91af-1d58eea6f825.png)

Found a related issue [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5411) and [here](https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1970800)

**Comment by abhichaurasiya2022** [comment] 2022-05-02 17:16
> Hi @abhichaurasiya2022, thanks very much for this issue!
> 
> Could you try the following things:
> 
> * it looks like your using some extensions, maybe this problem is related to them ;
> * did you tried the `gnome-session`? You can install it with `sudo apt install gnome-session`, then logout and select `Gnome` when login.
> 
> Also which version of Yaru and Ubuntu are you using?

I am using Ubuntu 22.04 With custom theme. I checked for the issue on live session of Ubuntu 22.04. On live Session of Ubuntu it was same case. So i think this issue is related to Gnome-Shell not theme.

**Comment by Jupi007** [comment] 2022-05-06 08:21
Okay, so I close this issue as it is not related to this theme.
Thanks @abhichaurasiya2022 and @LeFloatyPancake :+1:

**Closed by Jupi007** 2022-05-06 08:21 UTC
Labels: Status: info-needed, Area: GNOME-shell
