### ISSUE TITLE
Broken rendering on gnome-terminal tabs

### ISSUE THREAD

**Issue by jgabriel98** [ubuntu/yaru#2481] opened 2020-11-12 05:34 UTC
## Expected Behavior

proper rendering/color rendering on aplications, like gnome-terminal and tweaks.

## Actual Behavior
pure black rendering on some parts with specific conditions, for example:

- **gnome-terminal:** wrong rendering on tabs (just black, instead of theme's gray), but renders correctly when in maximized or fullscreen.
![image](https://user-images.githubusercontent.com/37881981/98898188-c808b500-248b-11eb-914e-896a410e8579.png)
![gnome-terminal_yaru-bug](https://user-images.githubusercontent.com/37881981/98898690-f33fd400-248c-11eb-8738-614ce33ff5aa.gif)

    
- **gnome-tweaks:** wrong rendering on header (just a black rectangle, instead of normal UI) on fresh open. After moving the window or resizing it renders correctly.
![tweaks_yaru-bug](https://user-images.githubusercontent.com/37881981/98898818-39953300-248d-11eb-9e1e-6953da63e034.gif)

## Software that presents the issue

- Name: Gnome-terminal
Version: 3.36.2-1ubuntu1~20.04

- Name: gnome-tweak-tool
Version: 3.34.0-2ubuntu1

## Yaru version

* My Yaru is the one provided by default from Ubuntu 20.04, the version shown by `apt-cache policy yaru-theme-gnome-shell` is :
```
yaru-theme-gnome-shell:
  Instaled: 20.04.8
  Candidate: 20.04.8
```

    `$ apt show communitheme`

### Extra info:
- my ubuntu was 19.10 upgraded to 20.04
- this only happens on Yaru. Other themes like Adawaita showed expected behavior.
- i ran `sudo apt reinstall yaru-theme-gtk --purge` and `sudo apt reinstall yaru-theme-gnome-shell --purge`, but it had no effect.

**Comment by Jupiter007-43** [comment] 2020-11-12 09:20
Hi @jgabriel98 and thanks for taking the time of writing this issue.
Strangely, everything is OK on my 20.10 install with Yaru master and on an other computer with 20.04 and default Yaru:

![Capture d’écran du 2020-11-12 10-11-37](https://user-images.githubusercontent.com/36476595/98919734-7c77fa80-24cf-11eb-943b-fcac49f3cb62.png)
![Capture d’écran du 2020-11-12 10-14-03](https://user-images.githubusercontent.com/36476595/98919966-d082df00-24cf-11eb-80e5-a7befd1d3d5a.png)

I see on your screenshot that you are using some extensions, can you give us the list please (the css of an ext is maybe on conflict with Yaru).

**Comment by jgabriel98** [comment] 2020-11-12 15:14
Those are my extension, all where activated before (except for GTK Title Bar).

![Captura de tela de 2020-11-12 12-12-04](https://user-images.githubusercontent.com/37881981/98957794-5a3aa880-24e0-11eb-9f07-88df9d60d6c8.png)


But i don't think the extensions are the problem: even when disabled, the problem still occurs
![Captura de tela de 2020-11-12 12-10-49](https://user-images.githubusercontent.com/37881981/98957916-7c342b00-24e0-11eb-8cab-7e129aaefc21.png)

**Comment by Feichtmeier** [comment] 2020-11-12 16:13
Maybe the transparent terminal window

**Comment by Jupiter007-43** [comment] 2020-11-12 16:48
> Maybe the transparent terminal window

Indeed, I tried to add some transparency on the terminal of my father's computer (20.04 and Yaru default) and there's the same behavior. But the bug is not reproducible on 20.10 with master:

![Capture d’écran du 2020-11-12 17-38-47](https://user-images.githubusercontent.com/36476595/98969083-c7653280-250e-11eb-91b3-0222e931e840.png)

So the question is: it is fixed by Gnome 3.38 or by Yaru master? Is someone has a 20.04 install with Yaru master installed for testing?

**Comment by Muqtxdir** [comment] 2020-11-12 17:09
hi,

### gnome-terminal:
Tried this on my machine running **ubuntu 20.04** with **yaru(20.04.8)** and encounter the terminal issue just like @jgabriel98 

**screenshot:**

![transparent](https://user-images.githubusercontent.com/54065734/98971008-a0225b80-2536-11eb-977c-391a76474ddd.png)

### gnome-tweaks:
regarding gnome-tweaks, i was able to reproduce the black borders just like @jgabriel98 when I changed windows titlebar buttons from right to left

**screenrecording**:

![tweaks](https://user-images.githubusercontent.com/54065734/98971821-ae24ac00-2537-11eb-98c4-8e494f2f0962.gif)

**Comment by Jupiter007-43** [comment] 2020-11-12 17:12
Thanks @Muqtxdir 👍
Can you also test with Yaru master please?

**Comment by Feichtmeier** [comment] 2020-11-12 17:16
The tab issue comes from the transparent tab

We need to re-set the background, but then special case Nautilus as there are the BG and base colours flipped

**Comment by Jupiter007-43** [comment] 2020-11-12 17:20
About the headerbar, there's indeed a bug on Gnome-tweaks when buttons are moved to left (I tested on 20.10).
But as it's also reproducible with Adwaita, I think it's app related.

**Comment by Muqtxdir** [comment] 2020-11-12 17:24
### gnome-terminal:
Yaru-master on ubuntu 20.04
![nottransparent](https://user-images.githubusercontent.com/54065734/98973376-ad8d1500-2539-11eb-8065-15e8d49ca96f.png)
### gnome-tweaks:
![tweaks1](https://user-images.githubusercontent.com/54065734/98973530-df9e7700-2539-11eb-98cf-997186ebcb0f.gif)
still issue is present even with Yaru-master, I think @Jupiter007-43 is right. It happens on adwaita as well, maybe related to the app

**Comment by Jupiter007-43** [comment] 2020-11-12 17:55
Thanks for testing @Muqtxdir,
so as the Terminal problem is already fixed on master and the Tweaks one is app related I think we can close this issue.
@Feichtmeier maybe do a backport to 20.04?

**Comment by jgabriel98** [comment] 2020-11-12 20:51
I see,
thank you all for the fast analysis.

i issue can be closed, but just one question before that.

Does someone recomends a solution for this on ubuntu 20.04, given that Yaru came from apt package?

some solution that would fix this now, but not make me outdated on long term (in case i forget that yaru where manually installed from source, and won't update anymore).

**Comment by Feichtmeier** [comment] 2020-11-12 21:40
Didn't change the transparent tabs from 20.04 to 20.10 
So either it's some change in gnome-terminal, and in 20.10 the terminal has a set background, or I don't know
So there is really nothing to backport. Need to check this all myself though :)

**Comment by Jupiter007-43** [comment] 2020-11-13 09:02
@Feichtmeier As the bug present with Terminal 3.36 and Yaru apt seems to be fixed with master, I think that something has changed in Yaru since the 20.04 release (maybe something not related to Terminal but just to Gtk tabs and that we have get from upstream 🤔).

**Comment by cavillagomez** [comment] 2021-01-11 21:27
Bug affects Terminal in Ubuntu 20.04 (gnome 3.36). Unmaximized windows, with transparency and affects menu bar and tabs

**Comment by broes5** [comment] 2021-04-22 10:12
I've just noticed this bug after I turned on transparent background option. Could someone (please) tell me how I can get my terminal tabs back to their original colour with out having to turn off the transparent background option. If not, how can I help to fix this bug?

**Comment by Feichtmeier** [comment] 2021-04-22 10:15
![grafik](https://user-images.githubusercontent.com/15329494/115697923-569b2f80-a364-11eb-8895-e9a69077da25.png)

it must be something only happening in focal
so the question is rather what we need to backport

**Comment by broes5** [comment] 2021-04-22 10:52
I have my theme set to Yaru-dark and I don't want to change it. 

![Screenshot from 2021-04-22 20-43-22](https://user-images.githubusercontent.com/64825158/115701934-ab15cd80-a3ab-11eb-9d41-ab9d52750f68.png)

Do you know roughly what and where (in the code) the thing is that needs to be backported?

**Comment by Feichtmeier** [comment] 2021-04-22 10:56
yeah, these lines, but when we remove them we need to have one tab styling background for $bg_color and one for $base_color

https://github.com/ubuntu/yaru/blob/53371e06310f15b5d574f084dcd98f59a7aa04e0/gtk/src/default/gtk-3.20/_tweaks.scss#L256-L279

Anyways, they changed something since focal and now transparent tabs are no problem anymore, so it will def. be a backport and not a master change

**Comment by lguenth** [comment] 2021-07-29 11:34
Any updates on this?

**Comment by jgabriel98** [comment] 2022-01-12 00:32
> Any updates on this?

I guess not 😞

**Closed** 2022-01-12 00:32 UTC
Labels: Area: gtk3

**Comment by mikhail-v** [comment] 2022-03-27 09:16
still reproducing

**Comment by Jupi007** [comment] 2022-03-27 19:19
I patched this into this repository and I requested an update of the package with a SRU.
Maybe it is still not yet published into Ubuntu repositories.
