### ISSUE TITLE
Gtk2-light : fixed two issues 

### ISSUE THREAD

**Issue by Paz-it** [ubuntu/yaru#877] opened 2018-09-28 16:10 UTC
1. Treeview_header : 
Before:
![treeviewbefor](https://user-images.githubusercontent.com/37431503/46220186-07c6be00-c352-11e8-860c-90434665899f.png)
 After : including fix for handles
![treeviewafter](https://user-images.githubusercontent.com/37431503/46220237-2af16d80-c352-11e8-828f-f2ccc0d3a375.png)
I changed 1 assets file with minor tweaks to gtkrc + main.rc
If you approve I need to send that asset file (png) and the tweaking details.
Example for treeview before : 
![before](https://user-images.githubusercontent.com/37431503/46220592-40b36280-c353-11e8-9464-df2fa4803aea.png)
After : 
![after](https://user-images.githubusercontent.com/37431503/46220626-5f195e00-c353-11e8-8389-29d9ec15c164.png)

**Comment by Paz-it** [comment] 2018-09-28 18:07
@madsrh , The color is VERY subtle, almost white but no problem to change it to complete white. The most important change is the clean look without extra unnecessary lines on top/bottom/lett/right preventing that clutter look.

**Comment by clobrano** [comment] 2018-09-28 21:12
The problem is that GTK2 must adhere with GTK3

![image](https://user-images.githubusercontent.com/2883614/46233692-e1197f00-c373-11e8-9199-2378d2804e95.png)

moreover, the headerbar in this PR looks outside of the table to me and breaks the notebook view

**Comment by Paz-it** [comment] 2018-09-28 23:56
I understand but the gtk3 looks much cleaner.
in this condition I think it is even more broken. 
look at it again here : 
![before](https://user-images.githubusercontent.com/37431503/46238284-15e8fe80-c393-11e8-9380-44fd5c5b9645.png)

**Comment by clobrano** [comment] 2018-09-29 08:17
That's probably a misuse of treeview headerbar in audacious. The reason why headerbar is white is exactly because sometimes they are inside a notebook tab, which is all white itself. A different color would break the view

**Comment by Paz-it** [comment] 2018-09-29 11:04
Like I said to @madsrh  the color is not the main issue. the most annoying and aesthetic issue is the extra unnecessary lines on top/bottom/lett/right that makes it look cluttered. 
Here you can see the before and after in Gpick: 
![before1](https://user-images.githubusercontent.com/37431503/46244994-e3b9ba00-c3ef-11e8-8a59-6de7ab635cdd.png) 
![after1](https://user-images.githubusercontent.com/37431503/46244998-efa57c00-c3ef-11e8-92f0-62cbbe1ce0f6.png)
and in Gimp : 
![before2](https://user-images.githubusercontent.com/37431503/46245008-0cda4a80-c3f0-11e8-9389-e606b57886a2.png)
![after2](https://user-images.githubusercontent.com/37431503/46245012-18c60c80-c3f0-11e8-841c-2898e1a166c6.png) 
I also changed the scrollbar color and reduced it's size but that's beside point now.

**Comment by madsrh** [comment] 2018-09-29 11:12
@Paz-it We simply disagree here. IMO the before picture looks better.

I do like the scrollbars - is you can open a PR for it, that would be great.

**Comment by Paz-it** [comment] 2018-09-29 17:31
Last try with all white treeview-headerbar and sccrollbar-through white background :+1: 
![screenshot from 2018-09-29 19-51-21](https://user-images.githubusercontent.com/37431503/46248776-8ee56600-c426-11e8-9181-b55c3c872e10.png) :thinking:

**Comment by clobrano** [comment] 2018-09-29 17:38
I would like to see it with the gtk2 test app. Could you open a PR with this change?

**Comment by Paz-it** [comment] 2018-09-29 17:51
Gtk2 test app : 
![screenshot from 2018-09-29 20-45-14](https://user-images.githubusercontent.com/37431503/46248906-cf45e380-c428-11e8-836b-de8dab25b58d.png) 
Can't open a PR , Sorry. there must be some other way,

**Comment by clobrano** [comment] 2018-09-29 21:13
I'm unsure, headerbar in awf is not ideal

**Comment by Paz-it** [comment] 2018-09-30 08:18
@clobrano ,The awf is not giving you the full perspective because it's a kind of stand-alone widget without the window-frame it belongs to but if you feel it's not fit let's close it.

**Comment by clobrano** [comment] 2018-10-10 15:54
Let's close this and continue to #908

**Closed by clobrano** 2018-10-10 15:54 UTC
