### ISSUE TITLE
Icons for "New", "Open" and "Save" are the same in KeepassXC

### ISSUE THREAD

**Issue by marcbone** [ubuntu/yaru#1294] opened 2019-03-26 18:55 UTC
I think [this issue](https://github.com/snwh/suru-icon-theme/issues/108) actually belongs here.
## Expected Behavior
In KeepassXC the icons for New, Open and Save should be different like in the adwaita theme

![](https://user-images.githubusercontent.com/29411952/47286729-3b62d400-d5f0-11e8-9a6d-3e5408a1a9c1.png)
## Actual Behavior
The icons are the same
![](https://user-images.githubusercontent.com/29411952/47286728-3aca3d80-d5f0-11e8-8587-f35ac84435d1.png)

## Specifications

name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 13 days ago, at 19:41 CET
channels:
  stable:    0.1 2019-03-13 (1768) 16MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-03-22 (1775) 16MB -
installed:   0.1            (1768) 16MB -

**Comment by CDrummond** [comment] 2019-03-27 10:16
Yeah, I noticed this and mentioned in issue #831 As stated there, I believe the issue is that Yaru has a `document` icon, but no `document-new` and `document-save` icons. So, when Qt looks for `document-new` it can't find it and fallsback to `document`

**Comment by clobrano** [comment] 2019-03-27 13:26
> Qt looks for document-new it can't find it and fallsback to document

how does this work? Yaru iconset inherits from Humanity and hicolor, so if an icon is not provided directly it should be given by one of the above icon sets

**Comment by CDrummond** [comment] 2019-03-27 14:00
To be honest, I don't really know. But seeing as the Yaru icon set has `document` I _think_ Qt just uses that - ie. finds the closest matching icon within the current set. But, I could be wrong :-)

**Comment by clobrano** [comment] 2019-03-29 16:20
I looked at the code. The application actually looks for document-new while we have document-new-symbolic. If I change the name, removing the -symbolic part, it works. Preparing a fix, but maybe it'd be good to infor Kepassxc that the naming convention is changing in adwaita as well

**Comment by clobrano** [comment] 2019-03-31 14:38
Transmission has the same use case, but it works fine

![image](https://user-images.githubusercontent.com/2883614/55290417-6ccba100-53d3-11e9-8202-f27162d00e76.png)

**Comment by chrisjbillington** [comment] 2019-04-27 20:10
Also seeing this in tortoisehg - it displays a document icon instead of a save icon, because it is looking for 'document-save'.

**Comment by chrisjbillington** [comment] 2019-04-27 20:18
Qt doesn't seem to know about fallback themes in this case:

```python
import sys
from PyQt5 import QtWidgets, QtGui

app = QtWidgets.QApplication(sys.argv)

icon = QtGui.QIcon.fromTheme('document-save')

print("actual icon name:", repr(icon.name()))
print("theme name:", repr(icon.themeName()))
print("fallback theme name:", repr(icon.fallbackThemeName()))

button = QtWidgets.QToolButton()
button.resize(200, 200)
button.setIcon(icon)
button.show()
app.exec()
```

prints:

```
actual icon name: 'document'
theme name: 'Yaru'
fallback theme name: ''
```
and shows the document icon:
![image](https://user-images.githubusercontent.com/1044087/56854642-01a8b800-6908-11e9-9c8a-0be47f070c0b.png)

**Comment by CDrummond** [comment] 2019-04-29 08:02
@chrisjbillington is this not how the icon themes are supposed to work? I _thought_ the convention was to strip off the trailing "-something" until a match was found. So that an icon set could have (e.g.) "input-mouse" which would be used if "input-mouse-usb" was not found.

See https://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html this mentions:

> The dash “-” character is used to separate levels of specificity in icon names, for all contexts other than MimeTypes. For instance, we use “input-mouse” as the generic item for all mouse devices, and we use “input-mouse-usb” for a USB mouse device. However, if the more specific item does not exist in the current theme, and does exist in a parent theme, the generic icon from the current theme is preferred, in order to keep consistent style. 

Seeing as "document" exists, but not "document-new", then "document" is being used - as its the more generic term, and in the current icon theme.

**Comment by chrisjbillington** [comment] 2019-04-30 01:17
@CDrummond, ah, I see! That makes sense. I had no clue how it was *supposed* to work and was just reported how it appears to be working. Good to know Qt appears to be following spec (even though the outcome might be not ideal in this case).

**Comment by leoheck** [comment] 2019-07-31 22:58
Hi guys, what is the status of this issue? 
Do you have any workaround for that? Just let me know cause I want to apply here, please.
I am really interested in fix this https://github.com/ubuntu/yaru/issues/1361

**Comment by clobrano** [comment] 2019-08-01 06:58
Hi @leoheck,

we didn't go deeper on this actually. I should be able to try again today with a VM

**Comment by leoheck** [comment] 2019-08-01 09:07
@clobrano what do you want to try? Why you need a VM?
What should I do to help to move this forward? I thought it was just creating some symbolic links, isn't it?

**Comment by clobrano** [comment] 2019-08-01 09:34
See this for example

> Transmission has the same use case, but it works fine
> 
> ![image](https://user-images.githubusercontent.com/2883614/55290417-6ccba100-53d3-11e9-8202-f27162d00e76.png)

Icon sets have a "fallback" theme, for providing a wider range of icons, Yaru uses Humanity which should have document-new, and according to @chrisjbillington prototype above, the API `QtGui.QIcon.fromTheme` is expected to look for the fallback theme https://srinikom.github.io/pyside-docs/PySide/QtGui/QIcon.html#PySide.QtGui.PySide.QtGui.QIcon.fromTheme

I still wonder why it could not find it and of course what we can do to support it. If you have any idea of solution or testing, I will be glad to discuss it :)

**Comment by clobrano** [comment] 2019-08-01 09:38
> Qt doesn't seem to know about fallback themes in this case:
> 
> ```python
> import sys
> from PyQt5 import QtWidgets, QtGui
> 
> app = QtWidgets.QApplication(sys.argv)
> 
> icon = QtGui.QIcon.fromTheme('document-save')
> 
> print("actual icon name:", repr(icon.name()))
> print("theme name:", repr(icon.themeName()))
> print("fallback theme name:", repr(icon.fallbackThemeName()))
> 
> button = QtWidgets.QToolButton()
> button.resize(200, 200)
> button.setIcon(icon)
> button.show()
> app.exec()
> ```
> 
> prints:
> 
> ```
> actual icon name: 'document'
> theme name: 'Yaru'
> fallback theme name: ''
> ```
> 
> and shows the document icon:
> ![image](https://user-images.githubusercontent.com/1044087/56854642-01a8b800-6908-11e9-9c8a-0be47f070c0b.png)

hi @chrisjbillington, with which pyqt5 version you tested this code? I installed the latest from pip (version 5.13.0) but it gives me errors like *QIcon does not have fallbackThemeName attribute* and the *exec* function is actually *exec_*

**Comment by leoheck** [comment] 2019-08-01 10:41
I see. I tried many things here to test if how to fix this fallback issue but none of them was good.
So, I fixed it with this workaround since now since I dont want to wait more time for a fix.
```
sudo ln -fs /usr/share/icons/Humanity/actions/48/document-new.svg  /usr/share/icons/Yaru/scalable/actions/
sudo ln -fs /usr/share/icons/Humanity/actions/48/document-open.svg /usr/share/icons/Yaru/scalable/actions/
sudo ln -fs /usr/share/icons/Humanity/actions/48/document-save.svg /usr/share/icons/Yaru/scalable/actions/
sudo ln -fs /usr/share/icons/Humanity/actions/48/document-print.svg /usr/share/icons/Yaru/scalable/actions/
```

**Comment by Feichtmeier** [comment] 2019-08-01 10:47
Maybe we have an icon that is symlinked to all these icons
document-new.svg
document-open.svg
document-save.svg
document-print.svg
?

**Comment by Feichtmeier** [comment] 2019-08-01 10:53
Or some error in the index
https://github.com/ubuntu/yaru/blob/master/icons/Suru/index.theme#L8

**Comment by clobrano** [comment] 2019-08-01 13:23
The actual icon name found is "document", so I think that, as per CDrummond [comment](https://github.com/ubuntu/yaru/issues/1294#issuecomment-487484587), we are forced to provide the icons for:

document-new.svg
document-open.svg
document-save.svg
document-print.svg

**Comment by leoheck** [comment] 2019-08-01 16:44
I guess numix does the same with symlinks, I found some there but I am not sure if they were related with these files. We just have to find an icon them with this working so we can ask/or see what are the differences.

I didn't have time to test hundred things this morning, but Freecad works with the default Adwaita theme. It is just a matter of comparing folders/files. The only issue I can see is the folder structure that slows down this process.

https://github.com/numixproject/numix-icon-theme

**Comment by Feichtmeier** [comment] 2019-08-01 18:27
No, it's exactly what @clobrano said. We need that icons and we are done. The thing is: full color action icons where never intended to be part of Suru.
Since we no longer follow the development of Suru, we can for sure pic up that shitload of work. But for modern gnome apps, those full color action icons are not necessary. 
Yet I understand that for those applications which use that legacy toolbars it's relevant.
But those 3 icons are just a tiny potion of the real work, yet stuart could for sure make those 3 icons and we could close this issue... But KDE Apps are really not high on our priority list

**Comment by Amr-Ibra** [comment] 2019-10-13 12:54
Any news here?
I'm also affected by this, using the Qt apps: Kid3-qt and Octave.

**Comment by Amr-Ibra** [comment] 2019-10-16 09:59
Many Qt apps appear broken in Yaru because of this issue.

**Comment by ubuntujaggers** [comment] 2019-10-16 10:48
There's about a trillion of these icons, isn't there? But maybe I could do just the "main ones" and see how we get along with that?

**Comment by clobrano** [comment] 2019-10-16 11:07
Indeed, we can start from the small list [here](https://github.com/ubuntu/yaru/issues/1294#issuecomment-517286273)

**Comment by ubuntujaggers** [comment] 2019-10-20 16:49
![image](https://user-images.githubusercontent.com/38893390/67163006-018eef80-f362-11e9-9b35-fd96d11ae70f.png)

??

**Comment by Amr-Ibra** [comment] 2019-10-20 19:29
OK, the first two show "New" and "Open", good, but unfortunately, the third doesn't show "Save".

**Comment by clobrano** [comment] 2019-10-20 21:14
Adwaita adds an arrow to underline that it's an icon to "save", maybe it can help.
What about using a green dot in the "new" icon, instead that blue?

**Comment by Amr-Ibra** [comment] 2019-10-21 07:35
I suggest the "save" icon to be the same as the "new" icon but replacing the dot with a downward arrow.

**Comment by ubuntujaggers** [comment] 2019-10-21 07:38
I can certainly make the dot green - I just used blue because that's what Adwaita did :)

Document with a down arrow would be very easy to draw, so that gets my vote!

**Comment by Amr-Ibra** [comment] 2019-10-21 07:51
Or follow Adwaita and use the "file-manager" icon with a downward arrow as a "save" icon, as seen in the first comment. It's your choice.

**Comment by ubuntujaggers** [comment] 2019-10-21 17:50
![image](https://user-images.githubusercontent.com/38893390/67229529-66fee100-f433-11e9-8eb7-90232609d395.png)

They also show up in Inkscape, with the document-print icon too:

![image](https://user-images.githubusercontent.com/38893390/67229559-7847ed80-f433-11e9-8736-217a54ef24fb.png)

**Problem:** if I create a new folder in the icons structure for 22x22 icons (which these are) they don't get picked up.  I got it to work by dropping them in the 24x24 full colour apps folder.  Bit messy but it works - does anyone know how to get it to recognise a completely new folder for these legacy full colour icons?  Alternatively: does anyone object to them staying in an existing folder?

**Comment by clobrano** [comment] 2019-10-21 18:18
Nice work @ubuntujaggers!

> I got it to work by dropping them in the 24x24 full colour apps folder. Bit messy but it works 

is it messy, because the icons are not 24px?

**Comment by ubuntujaggers** [comment] 2019-10-21 19:25
@clobrano Yes, and they're not apps either. I don't mind, but it's maybe not very organised.

**Comment by clobrano** [comment] 2019-10-22 07:09
I see. I am not really against leaving it this way, since it's the only way to make it work, but I'll try to find the reason first

**Comment by Amr-Ibra** [comment] 2019-10-22 17:43
Did you try sizing them 24×24 and put them in a legacy folder like Adwaita?
https://gitlab.gnome.org/GNOME/adwaita-icon-theme/tree/master/Adwaita/24x24/legacy

And excuse my ignorance, why not sizing the icons 48×48 for them to scale better?

**Comment by ubuntujaggers** [comment] 2019-10-22 23:47
Hi @Amr-Ibn, the icons render at 22px, so a multiple of 24 wouldn't scale sharply to 22px (which is important for a small button with details like a little "+"). If the icons can be displayed at 44px then we do need to export it at double size.  If the icons can be rendered at multiple different sizes then we need multiple icons.

It may be the new folder didn't follow the right naming convention - I'll copy Adwaita exactly and see if that works, thanks for the tip :)

**Comment by ubuntujaggers** [comment] 2019-10-23 10:49
Okay, looks like Adwaita has these icons at 22px _plus_ all the usual sizes.

Step one: I'll see if I can get the folders to work.

Step two: I'll draw the other sizes.

**Comment by ubuntujaggers** [comment] 2019-10-23 11:09
Okay, copying the 22x22/legacy folder structure doesn't work  :(

Changing the icon size in Ubuntu doesn't seem to make these buttons render at different sizes.  Nor does using the accessibility zoom feature (it just zooms in on the existing image assets, rather than adapting the UI to use any higher res assets that might be available).

Given that these are legacy icons, my suggestion is to only target the default 22px button size (presuming these is the same regardless of monitor size - but we can test that when I push).  However, I will export the icons at 176px ( = 8x size) so they don't become blocky if there are edge cases where the UI renders them larger than 22px.  They won't be 100% sharp in these cases (if they even exist) but at least there won't be visible pixellation.

**Comment by ubuntujaggers** [comment] 2019-10-23 11:20
Okay, frustratingly, that won't work.  If I export a high res png for these buttons, Keepass scales it down to 22px (which is the desired behaviour) but Inkscape shows it at 100%, leading to a comically enormous button.  So, really the only safe thing to do is to have a 22px button at 22px and then create the other sizes **if** they're ever used.

**Comment by clobrano** [comment] 2019-10-23 11:25
Thanks @ubuntujaggers, it seems good to me :)
I can't test right now, but I kinda remember to have found this icons also in some "action" folder, is that possible?

**Comment by ubuntujaggers** [comment] 2019-10-23 11:28
That was my first attempt, but there was no actions folder under full colour so I had to make it  :(

Basically: if I make any new folders in the Yaru structure, the icons in them don't get used.  But if I put them in existing folders they do.

**Comment by clobrano** [comment] 2019-10-23 11:31
Sorry for the silly question, but is there any list of "folders to be installed" that might need to be updated when you create a new one?

**Comment by ubuntujaggers** [comment] 2019-10-23 12:09
Good point, I'll see if I can find one :+1:

**Comment by chrisjbillington** [comment] 2019-10-23 13:34
For what it's worth here in tortoisehg we've got `document-save` in 16x16:

![image](https://user-images.githubusercontent.com/1044087/67397974-ff05e300-f577-11e9-9f23-ec1445c6ad31.png)

**Comment by ubuntujaggers** [comment] 2019-10-23 14:53
Aha, good tip. Then we need to work out how to make new folders and do this properly.

**Comment by Feichtmeier** [comment] 2019-11-07 13:28
Should be fixed by #1600 (even though #1600 produced #1610 )

Could anyone confirm that it is fixed?

**Comment by chrisjbillington** [comment] 2019-11-07 13:57
I can confirm the icon in tortoisehg has been fixed.

**Comment by clobrano** [comment] 2019-11-07 19:23
Thanks!

**Closed by clobrano** 2019-11-07 19:23 UTC
Labels: Area: icon theme, Status: info-needed

**Comment by amavlyanov** [comment] 2019-11-08 08:16
Any chane it'll be ported to 19.04 / 19.10?

**Comment by clobrano** [comment] 2019-11-08 08:19
19.10 for sure

**Comment by mitya57** [comment] 2019-12-24 20:27
> 19.10 for sure

@clobrano Do you have any update for 19.10 backport? If you push the commits somewhere I can sponsor the upload for you. Though per the release policy, first we need to get this fixed in Focal.

**Comment by leoheck** [comment] 2019-12-25 13:40
@mitya57 This issue was fixed for me, I am using 19.10.

Look, Transmission and Freecad

![image](https://user-images.githubusercontent.com/1277920/71446503-d084bf80-2702-11ea-83b4-4e8a4d3903fd.png)

**Comment by mitya57** [comment] 2019-12-25 13:53
Hmm, maybe this was fixed in snaps? I meant the deb package from Ubuntu repository.

**Comment by clobrano** [comment] 2019-12-27 10:19
There isn't any official release yet, but both snap and ppa have the update.

@mitya57, it's usually the desktop team that tell us that the package is about to be updated, then we just tag a commit here so that they can sign it and use it

**Comment by mitya57** [comment] 2019-12-27 10:52
I am not a member of desktop team, but I'm Qt maintainer in Ubuntu. If you tag some commit, I will happily upload it.
