### ISSUE TITLE
Enhancement: Change Icon for "Software & Updates"

### ISSUE THREAD

**Issue by DarkTrick** [ubuntu/yaru#2292] opened 2020-07-28 05:03 UTC
I'm writing here, because I was "forwarded" from [ubuntu discourse](https://discourse.ubuntu.com/t/suggestion-icon-all-application-add-gear-to-software-updates/17544/4) .

Digest of my ubuntu discourse post:

**Current situation:**
Current look of "Software & Updates":  [current situation](https://ubuntucommunity.s3.dualstack.us-east-2.amazonaws.com/original/2X/8/81966fcfee886732f8c048a98b58565586ded3d1.png)

**Problem:**
"Software & updates" and "Software Update" look pretty much the same.

**Suggestion:**
Add a gear to "Software & Updates" because it's for settings
[example image](https://imgur.com/a/XZsdiHT) (this is not a final version; just to get the idea)

**Edit:**
The above is apparently difficult, so I added two other suggestions:
- https://imgur.com/a/eRrfPZI
- https://imgur.com/a/tCauBzo

Base gimp file (just as reference):
https://www.dropbox.com/s/fjp1f0yyi5stwo5/updater_suggestions.xcf?dl=0

**obsolete:**

> Regarding a new design I would suggestion using something cogwheel-like. I feel it is consistent to current systems - internally and externally.
> - Internal: This is already used as Settings icon.
> - External: tablets/smartphones use it (huge user base).

**Comment by madsrh** [comment] 2020-07-28 07:29
Nice idea @DarkTrick 

What do you think @ubuntujaggers ?

https://i.imgur.com/S6zTmja_d.webp?maxwidth=640&shape=thumb&fidelity=medium

**Comment by ubuntujaggers** [comment] 2020-07-28 07:59
Unfortunately we have a policy nowadays of not making a superimposed emblem part of the icons (because emblems can already be superimposed on icons) :(  We eventually settled on the distinction of having a progress bar for the updater and a matching slider for settings (and hopefully the colour makes it easy to distinguish when you know which is which - but half the problem is the fact we have two offerings with almost the same name, rather than one icon to stand for both!).

**Comment by madsrh** [comment] 2020-07-28 08:08
Ahh, I couldn't find the issue where this discussion took place but luckily you have the mind of an elephant 😄

Aren't emblems only/mostly for files and not apps? I've never seen one in the dock (except for the counter batch ofc).

**Comment by DarkTrick** [comment] 2020-07-28 08:43
I'm not entirely certain about the exact meaning of "superimpose".
Also something like this would be not possible? 
https://imgur.com/a/eRrfPZI

**Comment by ubuntujaggers** [comment] 2020-07-28 09:03
Apologies, it means "put on top of".  Gnome already overlay circular emblems onto icons in certain contexts so we try to avoid using them in designs (we still need to come up with a new design for startup disk creator!).

That first linked image is really nice and I'll have a go at incorporating it into the icon for the next release :+1:

**Comment by Feichtmeier** [comment] 2020-07-28 09:16
I still loved eaglers version where the progressbar in the A was replaced by a :gear: :shrug:

**Comment by madsrh** [comment] 2020-07-28 09:23
> I still love eaglers version where the progressbar in the A was replaced by a ⚙️ 🤷

Do you have a link because I can't find it 🙈

**Comment by Feichtmeier** [comment] 2020-07-28 09:51
This thread has nice design ideas https://github.com/ubuntu/yaru/issues/1940

**Comment by madsrh** [comment] 2020-07-28 12:05
Okay, this is pretty poorly executed but you get the idea which is to use a wrench for the line in the A

![image](https://user-images.githubusercontent.com/3986894/88663123-59216f00-d0db-11ea-9b2c-a3a7927daa6b.png)

**Comment by ubuntujaggers** [comment] 2020-07-28 12:11
That's another nice concept!

I can't remember why we didn't go for Eagler's concept. I know he never provided the SVG and I dimly recall it was hard making it clear at small sizes (possibly a reflection of my skill rather than the design).

**Comment by madsrh** [comment] 2020-07-28 12:16
> (possibly a reflection of my skill rather than the design)

I doubt that. Your skills are much improved with every release 🥇 

I know you have other stuff pending, but is this something you would/could take a stab at?

**Comment by Feichtmeier** [comment] 2020-07-28 12:29
Looks cool. 
Additionally I would go away from the purple for this icon so it also is different in colour

**Comment by DarkTrick** [comment] 2020-07-29 08:30
Maybe it's worth running a poll for some designs? 

I personally would vote for something with a cogwheel. I feel it would be more consistent - internally and externally.
Internal: This is already used as `Settings` icon.
External: tablets/smartphones use it (huge user base).

**Comment by Feichtmeier** [comment] 2020-07-29 08:36
We made bad experiences with polls, but we appreciate your opinion and feedback :+1: 
Just reading the issues here is okay to get impressions imo

**Comment by DarkTrick** [comment] 2020-07-29 09:03
Just for reference, here is my base gimp-file. 
https://www.dropbox.com/s/fjp1f0yyi5stwo5/updater_suggestions.xcf?dl=0

I also consolidated my discussion content in the first post.

**Comment by ubuntujaggers** [comment] 2020-07-30 20:14
Needs work to make it clearer:

![image](https://user-images.githubusercontent.com/38893390/88969968-891e6d00-d2a9-11ea-833c-e499ca90be05.png)

...but that's the spanner concept so far.  Personally I'm quite fond of the slider?

**Comment by Feichtmeier** [comment] 2020-07-30 20:34
I think the color is also a problem. Maybe play with the ubuntu orange as a background for software + updates instead? Maybe even drop the A for this one ? :shrug:

**Comment by DarkTrick** [comment] 2020-07-31 06:57
I made the screenshot a little bigger for my initial test-images and the wrench one here:
https://imgur.com/a/EjSyrAY

Tbh... the wrench one looks the best to _me_.

**Comment by Feichtmeier** [comment] 2020-07-31 09:14
> I made the screenshot a little bigger for my initial test-images and the wrench one here:
> https://imgur.com/a/EjSyrAY
> 
> Tbh... the wrench one looks the best to _me_.

Thanks for sharing your idea!

**Comment by Feichtmeier** [comment] 2020-09-25 21:38
@DarkTrick we decided to keep the current icon until these functionalities are merged into the snap store. Thanks for contributing

**Closed by Feichtmeier** 2020-09-25 21:38 UTC
Labels: Area: icon theme
