### ISSUE TITLE
drag-handles aren't visible in dark theme

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#1847] opened 2020-02-02 16:19 UTC
I had some good guidance, but I simply couldn't fix this 😭 

I tried a bounch of variations of `scrolledwindow viewport hdycolumn image.drag-handle`

![image](https://user-images.githubusercontent.com/3986894/73611235-1412f900-45e0-11ea-97bf-87bea77d6499.png)

![image](https://user-images.githubusercontent.com/3986894/73611239-20975180-45e0-11ea-9d68-3454f841544d.png)

**Comment by clobrano** [comment] 2020-02-02 16:55
Consider it might not work out of gtk inspector, let me have a try ;)

**Comment by madsrh** [comment] 2020-02-02 16:58
Ahh, it was just as an example. I did added it to tweaks and build it 😔

**Comment by Feichtmeier** [comment] 2020-02-02 23:31
It looks like they style this themselves

https://gitlab.gnome.org/GNOME/gnome-control-center/blob/master/shell/style.css#L2

If this CSS file gets loaded after the global theme then you should file a bug on their repo I guess
(Tip: don't use yaru screenshots :dancing_men: )

**Comment by clobrano** [comment] 2020-02-03 07:54
> Ahh, it was just as an example. I did added it in tweaks and build it pensive

Yes, what @Feichtmeier said is what I meant. GtkInspector changes are always applied *after* any other CSS, so they always work. Out of gtk inspector, instead, it's the app's CSS to be applied last, so it overwrites anything we put in our CSS

**Comment by clobrano** [comment] 2020-02-03 07:56
The next step could be to double check whether in Adwaita dark the problem is the same, if that so they would probably be more keen to change it

**Comment by madsrh** [comment] 2020-02-03 09:10
Good thinking! and it exist in Adwaita as well. They would probably prefer a patch rather than a bug report. Would any of you mind doing that?

![image](https://user-images.githubusercontent.com/3986894/73639022-cf34a400-466b-11ea-8ad8-705335d3a538.png)

**Comment by clobrano** [comment] 2020-02-03 09:18
I can do that

**Comment by clobrano** [comment] 2020-02-03 15:58
The best I could do so far was to open a [ticket](https://gitlab.gnome.org/GNOME/gnome-control-center/issues/858), since there is a [known problem](https://gitlab.gnome.org/GNOME/gnome-control-center/issues/828) that prevents me to build Settings with gnome-builder

**Comment by clobrano** [comment] 2020-02-09 11:41
Closing this since it is to be solved upstream first

**Closed by clobrano** 2020-02-09 11:41 UTC
Labels: Area: gtk3

**Comment by clobrano** [comment] 2020-04-28 15:51
This is not reproducible in both fedora32 and 20.04 btw :)
![image](https://user-images.githubusercontent.com/2883614/80508895-ea683480-8978-11ea-8bbe-5b6fde9d5a1a.png)

**Comment by madsrh** [comment] 2020-04-28 15:54
Nice, must be fixed upstream 👍
