### ISSUE TITLE
Theme Parsing Error 

### ISSUE THREAD

**Issue by namontalbano** [ubuntu/yaru#2349] opened 2020-09-07 20:44 UTC
## Expected Behavior

Error can be avoided by utilizing background and or background-color. 

## Actual Behavior
Parsing error is thrown in syslogs when loading gtk-3.20 theme. Nautilus paned seperator is throwing,  "Not a valid image" due to the background image being set as a color. 

Line 89 _apps.scss
```   
paned > separator {
     // separator between sidebar and main window view
     background-image: image(if($variant=='light', transparentize($borders_color, 0.6), darken($borders_color, 1%)));  
     &:backdrop { background-image: image(transparentize($borders_color, 0.7)); }
} 
```

![image](https://user-images.githubusercontent.com/22596989/92415799-8d4f6d00-f128-11ea-8d1b-4b7d9eb62f94.png)

## Steps to Reproduce the Problem

N/A

## Software that presents the issue

- Name: Ubuntu 20.04 LTS
- Version: Latest

**Comment by clobrano** [comment] 2020-09-10 08:25
Good catch, thank you!

**Comment by clobrano** [comment] 2020-09-15 16:05
Hi again @namontalbano,
I cannot reproduce the error. Launching Nautilus doesn't return any theme parsing error, in the extracted gtk.css, the line 4815 doesn't belong to Nautilus styling, and moreover in `_apps.scss` we set the background image to `image(<hexcolor>)` which is supported by CSS, as far as I know, and in CSS it results in `background-image: image(rgba(196, 196, 196, 0.4));`

Could you help me understand which "syslog" were you referring to?
Also, please provide actual Yaru version using, for example, `dpkg -l | grep yaru`

Thank you

**Comment by namontalbano** [comment] 2020-09-15 20:38
Hi @clobrano,
I think the error I recieved was from a custom session, I was also unable to reproduce on the default Ubuntu session. The logs posted above are from `/var/log/syslog` however, I don't believe this is an underlying issue with the css `background-image`. 


Version:
yaru-theme-gtk  20.04.8

**Comment by clobrano** [comment] 2020-09-15 21:02
I see. Usually the theme parsing errors are visible directly in a shell when launching an application manually.
Since it is not reproducible in a supported sessions, I close this ticket, but thanks anyway to take time to report a possible problem.

**Closed** 2020-09-15 21:02 UTC
Labels: Area: gtk3, Status: Not reproducible, Status: info-needed
