### ISSUE TITLE
Remove button pressed shadows on soft keyboard during login

### ISSUE THREAD

**Issue by AshtonMartin** [ubuntu/yaru#933] opened 2018-10-25 15:38 UTC
I am using the adwaita light theme
When I press any key on the virtual keyboard in the login screen, all the buttons(keys) have a shadow for the pressed effect. I am trying to remove the shadow.

I tried adding removing the shadow in the main.rc sty;e "button" but that did not change the behavior.
engine "pixmap"
{
    image {
      function = SHADOW
    }
}

any suggestions would be really appreciated!
Thanks!

**Comment by clobrano** [comment] 2018-10-25 16:46
Hi @AshtonMartin, 

> I am using the adwaita light theme

I believe you meant "Yaru light", right?

**Comment by AshtonMartin** [comment] 2018-10-25 21:58
Yes. The code I am trying to modify is in yaru/gtk/src/light/gtk-2.0/main.rc

**Comment by clobrano** [comment] 2018-10-27 10:10
> When I press any key on the virtual keyboard in the login screen, all the buttons(keys) have a shadow for the pressed effect. I am trying to remove the shadow.

screen keyboard style is defined in gnome-shell/.../_common.scss.
What's the reason you want to remove it?

**Comment by godlyranchdressing** [comment] 2018-10-27 16:51
The fix for that won't be in the GTK2 theme files, the virtual keyboard uses SVG assets that are found in the yaru/gnome-shell/src. I think the switch to SVG files were a change that came with a new GNOME release so they actually need to be updated.

**Comment by clobrano** [comment] 2018-10-30 22:52
@godlyranchdressing, I tested the on screen keyboard, but it looks good to me. Could you show me what's the problem?

**Comment by godlyranchdressing** [comment] 2018-11-02 14:16
@clobrano Whoops, I only just saw your post.

![adwaita](https://user-images.githubusercontent.com/27529229/47920377-463b2580-de88-11e8-8903-c12be7276663.png)

**Comment by clobrano** [comment] 2018-11-02 15:04
sorry @godlyranchdressing, I still don't get what the problem is :(

**Comment by godlyranchdressing** [comment] 2018-11-02 16:02
@clobrano that's what the keyboard looks like on Adwaita, it doesn't match the rest of the theme.

**Comment by clobrano** [comment] 2018-11-02 16:13
@godlyranchdressing, I see now, but it doesn't seem the same problem this bug is talking about

**Comment by godlyranchdressing** [comment] 2018-11-08 23:37
@madsrh Yeah, I think so. I thought maybe @AshtonMartin was seeing the shadow from the unstyled Adwaita keyboard but now I'm really lost to be honest. :sweat_smile:

**Comment by Feichtmeier** [comment] 2018-12-03 17:06
I think @godlyranchdressing did a great job and I didn't find any more issues in the new style. Anyone against closing this?

**Closed** 2018-12-03 17:32 UTC
Labels: info-needed
