### ISSUE TITLE
Strange tabs in Yaru

### ISSUE THREAD

**Issue by kcohar** [ubuntu/yaru#1546] opened 2019-09-26 12:37 UTC
Hey guys, so first off, thank you so much for bringing back the mixed Yaru theme to eoan and providing it alongside yaru-dark and yaru-light, it's one of my favorites! That said, there's a problem with tab bars (terminal, chrome etc.). I'm not entirely sure that it is a problem though, might just be a matter of taste?

## Expected Behavior
![image](https://user-images.githubusercontent.com/47360019/65687965-8db33d00-e06a-11e9-8b9a-30ff0992c22b.png)
## Actual Behavior
(What happened instead)
![image](https://user-images.githubusercontent.com/47360019/65688078-bf2c0880-e06a-11e9-8fd1-24959f42800c.png)

## Steps to Reproduce the Problem

  1. Run the terminal and open up a new tab

## Specifications

Software that presents the issue:
- Name: Ubuntu Eoan Ermine (development branch)
- Version: 19.10

I'm sorry I'm totally new to this and didn't know how to put it into words.

**Comment by clobrano** [comment] 2019-09-26 12:43
Hi @kcohar,

thanks for the report, it's actually pretty accurate :+1: 

This is an outcome of our rebase onto Adwaita trying to keep the difference at a minimum, so it is kind of expected behavior. However, I'd try to work on this because I do like the previous version more. 
It won't be ready for 19.10 release unfortunately

**Comment by Feichtmeier** [comment] 2019-09-26 13:15
I know we talked about this before, but wouldn't it make more sense to default the terminal to dark in gsettings?

That's the kind of problems you get when you overwrite what's not intended to be possible :(

**Comment by clobrano** [comment] 2019-09-26 13:36
I have no strong opinion here, both options have pros and cons. Using gsetting seems easier ofc (we don't need to do anything), but we'll force dark terminal even on people that use Yaru-light for example.

**Comment by kcohar** [comment] 2019-09-26 14:09
@Feichtmeier that would fix the Terminal, but not Chrome (or any other application that decides to do this),

@clobrano thanks!

Great job with the themes you guys, they're good but I'm really fond of the mixed theme and I'm hoping it's not going to be ditched (it's very distinguished). As far as it not being ready in time for 19.10, oh well.

There is another problem the rebase caused actually, 
https://www.reddit.com/r/gnome/comments/buj4u5/is_this_a_bug_adwaita_menu_choppier_than_yarus/

The original Yaru didn't suffer from this issue (it's an Adwaita problem - the GNOME devs probably don't pay much attention to it seeing as GNOME focuses on Wayland so much).

Should I open up another github issue thread? I mean it's technically _not_ a Yaru issue...

**Comment by clobrano** [comment] 2019-09-26 14:32
> @Feichtmeier that would fix the Terminal, but not Chrome (or any other application that decides to do this),

Not sure I understood. What do you mean? (consider that Chrome is a special case in GTK stylesheet)

Honestly, I am not sure to see the difference in smoothness for that animation on my machine :thinking:

**Comment by kcohar** [comment] 2019-09-26 15:11
I meant that if an application decided to behave like the terminal (although I can't think of one atm :sweat_smile: ) it would have to be defaulted to dark too - this would have to be done on a case-by-case basis.

Haha I can see the difference because I have a really old/slow computer (that's why I'm so excited about the performance enhancements in 19.10 :laughing: )

**Comment by Feichtmeier** [comment] 2019-09-26 16:29
> @Feichtmeier that would fix the Terminal, but not Chrome (or any other application that decides to do this),
> 
> ![image](https://user-images.githubusercontent.com/47360019/65696004-cce88a80-e078-11e9-86b2-2eb23abe7d58.png)
> 
> @clobrano thanks!
> 
> Great job with the themes you guys, they're good but I'm really fond of the mixed theme and I'm hoping it's not going to be ditched (it's very distinguished). As far as it not being ready in time for 19.10, oh well.
> 
> There is another problem the rebase caused actually,
> https://www.reddit.com/r/gnome/comments/buj4u5/is_this_a_bug_adwaita_menu_choppier_than_yarus/
> 
> The original Yaru didn't suffer from this issue (it's an Adwaita problem - the GNOME devs probably don't pay much attention to it seeing as GNOME's focus is on Wayland).
> 
> Should I open up another github issue thread? I mean it's technically _not_ a Yaru issue...

Chrome tabs can't be changed from our side. It sucks up the base color of the theme and then they do their own stuff with it
But you could disable "use system borders" or whatever it's on english :) sorry for the german
![grafik](https://user-images.githubusercontent.com/15329494/65706731-5f922500-e08b-11e9-901f-403e78649ed5.png)

@clobrano 
> but we'll force dark terminal even on people that use Yaru-light for example.

If the headerbar is dark and the tab is dark, what's left to be light? :) The context menu :D I mean, you need to do all the dedicated terminal styling again like in the previous yaru. I would rather ping the desktop team and ask them for the gsetting

**Comment by kcohar** [comment] 2019-09-26 16:44
Haha no worries

Chrome looking weird (both here and in Plasma) is a Chrome problem I agree. I use system borders because I find that black border that surrounds the window kinda weird. But it's really not that big an issue.

The "tab" thing does occur elsewhere, Transmission for example.

old
![image](https://user-images.githubusercontent.com/47360019/65707239-6a998500-e08c-11e9-9401-9305c1dd0b9c.png)
vs new
![image](https://user-images.githubusercontent.com/47360019/65707279-81d87280-e08c-11e9-9221-68e66a67900e.png)

It's not that big an issue here though, just a matter of taste.

**Comment by memeplex** [comment] 2019-10-19 09:37
Setting terminal theme to dark is not ideal since it turns dark not only tabs but also preferences dialog, confirm dialog, etc.

**Comment by marius311** [comment] 2019-10-21 16:17
I see the same after an upgrade Ubuntu 19.10. Both gnome-terminal and google-chrome tabs are light, while before they used to be a much more readable and consistent dark color. 

I understand that how google-chrome uses the system theme is out of the control of Yaru, but at the very least it *used* to give a better results (ie the tabs were dark), is it not possible to revert back to that behavior without altering other new aspects of Yaru?

**Comment by Feichtmeier** [comment] 2019-10-21 16:47
> Setting terminal theme to dark is not ideal since it turns dark not only tabs but also preferences dialog, confirm dialog, etc.

I understand the problem.
On the other side we would like to keep the maintenance of the "mixed" theme, which is in fact the light theme, with a dedicated headerbar file, as small as possible.

In the old yaru theme at some point there were made so many little aesthetic additions for either some parts of the UI to match the dark headerbar in the light theme (which is still very much unsupported by gtk) but also for specific apps.

For the latter I would like to promote to stop this, because all UI elements should look the same  throughout the toolkit.
For the first I would promote to stop this until there is enough "backbone" for this in GTK (at least more than 0).

So, those tabs come directly from upstream, as anything else, except colors.
I would rather close this issue - don't know what @clobrano thinks about this, though

**Comment by clobrano** [comment] 2019-10-21 18:14
I agree. The only move I can suggest is to default to dark mode for this app only, but it would be a gsetting change, and not in Yaru.

**Closed by clobrano** 2019-10-21 18:14 UTC
Labels: Priority: Low, Status: Design

**Comment by marius311** [comment] 2019-10-21 18:32
Fyi I filed this with gnome-terminal: https://gitlab.gnome.org/GNOME/gnome-terminal/issues/178

For now `gsettings set org.gnome.Terminal.Legacy.Settings theme-variant 'dark'` is an ok workaround for me, although not ideal since it affects the dialog boxes as well, as mentioned above.

**Comment by clobrano** [comment] 2019-10-22 07:17
> Fyi I filed this with gnome-terminal: https://gitlab.gnome.org/GNOME/gnome-terminal/issues/178

I don't think this will live long and please try to be more careful when interpreting our replies :|

**Comment by marius311** [comment] 2019-10-22 19:55
Yes, sorry, I didn't mean to misrepresent what you said. In any case, so that I understand, if the solution is not in gnome-terminal and its not in Yaru, where is it supposed to go?

**Comment by clobrano** [comment] 2019-10-23 19:00
The proposed solution is to use dark for terminal in your system.
Otherwise, since there are currently other priorities and it's a bug prone feature, you can try to propose a PR to implement it and I'll be more than happy to review it.

[carlo - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=7tnue)	[7tnue]

On October 22, 2019 at 19:55 GMT, Marius Millea <notifications@github.com> wrote:

Yes, sorry, I didn't mean to misrepresent what you said. In any case, so that I understand, if the solution is not in gnome-terminal and its not in Yaru, where is it supposed to go?
