### ISSUE TITLE
Libreoffice snap theme broken

### ISSUE THREAD

**Issue by sumeetaras** [ubuntu/yaru#776] opened 2018-09-04 21:38 UTC
## Expected Behavior
Libreoffice should respect the communitheme.

## Actual Behavior
I am seeing dark backgrounds and menu entries seem broken since yesterday or so.
![screenshot](https://user-images.githubusercontent.com/10984081/45059209-3ca06780-b069-11e8-91b5-3075ae592b52.png)

## Steps to Reproduce the Problem
1. Install Libreoffice snap (I have version 6.1.0.3).
2. Communitheme snap session.
3. Open Libreoffice Writer

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    `$ snap info communitheme`

name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the
  community. Yaru will become the default Ubuntu theme in Ubuntu 18.10. This
  package allows you to try out the theme on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart
  your computer and select the "Ubuntu with communitheme snap" session from
  the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 8 days ago, at 18:57 EDT
channels:                   
  stable:    0.1 (848) 10MB -
  candidate: ↑              
  beta:      ↑              
  edge:      0.1 (961) 10MB -
installed:   0.1 (848) 10MB -

Software that presents the issue:
- Name: Libreoffice snap 
- Version: 6.1.0.3

**Comment by clobrano** [comment] 2018-09-05 08:00
Hi @sumeetaras thanks for reporting this. Just to clarify, do you have a communitheme package 8 days old (stable), but the issue on Libreoffice appeared only since a couple of days, right?

**Comment by Feichtmeier** [comment] 2018-09-05 08:53
Hmmm using the LO snap myself, and I can not confirm this.

![image](https://user-images.githubusercontent.com/15329494/45082576-f34c2880-b0f9-11e8-907f-e71578f08736.png)


Do you have gtk-common-themes snap installed?
```bash
sudo snap install gtk-common-themes

**Comment by clobrano** [comment] 2018-09-05 14:34
I can't reproduce it as well with the same libreoffice version. Could you copy the output of this command?

    $ snap interfaces | grep libreoffice

I expect something like

```
:cups-control                              libreoffice
:desktop                                   gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
:gsettings                                 gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
:home                                      gnome-characters,gnome-logs,libreoffice
:network                                   gnome-calculator,gnome-logs,libreoffice
:network-bind                              libreoffice
:opengl                                    libreoffice
:pulseaudio                                libreoffice
:removable-media                           libreoffice
:screen-inhibit-control                    libreoffice
:unity7                                    gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
:wayland                                   gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
gtk-common-themes:gtk-3-themes             gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
gtk-common-themes:icon-themes              gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
gtk-common-themes:sound-themes             gnome-calculator,gnome-characters,gnome-logs,gnome-system-monitor,libreoffice
-                                          libreoffice:bluez
```

**Comment by sumeetaras** [comment] 2018-09-05 16:30
I re-installed the Libreoffice snap again and now the theme is applied as expected. Looks like an issue with my previous install. Strange though.

**Comment by clobrano** [comment] 2018-09-05 16:44
Good :)
Closing then

**Closed by clobrano** 2018-09-05 16:44 UTC

**Comment by sumeetaras** [comment] 2018-09-05 16:53
Yeah. Thanks for taking a look!
