### ISSUE TITLE
hovering on ubuntu dock apps icons, names have uneven bordering issue

### ISSUE THREAD

**Issue by kothekarswaraj** [ubuntu/yaru#2801] opened 2021-04-24 06:44 UTC
**Expected Behavior**
bordering must be on all four sides

**Actual Behavior**
bordering is only on the right & bottom part of the rounded corner rectangle 

**Steps to Reproduce the Problem**
first set wallpaper with the dark background if u r using ubuntu standard appearance because borders are of light colour 
hover on ubuntu dock icons so that u see names of apps & look at borders around naming which is a black rectangle

**System information**

**Yaru version**
yaru used for ubuntu 21.04

**Screenshots**

**Upstream check**

**Comment by Feichtmeier** [comment] 2021-04-24 07:47
Duplicate of #2547 but let's keep this opened. Thanks for reporting since it is obviously not fixed :)

@Jupi007 fixed this for gnome shell 40 though, I think this happens because the dock.scss wrongly overrides the common. Scss radius

**Closed** 2021-04-24 12:46 UTC
Labels: Area: GNOME-shell
