### ISSUE TITLE
Hand cursor revert to Adwaita

### ISSUE THREAD

**Issue by Jupiter007-43** [ubuntu/yaru#2219] opened 2020-06-30 11:41 UTC
## Actual Behavior

Hover:
![Capture d’écran du 2020-06-30 12-55-29](https://user-images.githubusercontent.com/36476595/86118628-5f6afe00-bad1-11ea-9447-609d4ff63797.png)

Click:
![Capture d’écran du 2020-06-30 12-55-52](https://user-images.githubusercontent.com/36476595/86118633-62fe8500-bad1-11ea-8085-24091f1ccef0.png)

On the first screenshot you can that the hand on the minimap is the Adwaita one.

## Steps to Reproduce the Problem

  1. Ensure that minimap package is installed
  1. Hover the minimap on a random file

## Software that presents the issue

- Name: Atom
- Version: 1.48.0 (snap)

**Comment by Jupiter007-43** [comment] 2020-06-30 11:43
It's the hand cursor:

![Capture d’écran du 2020-06-30 13-42-49](https://user-images.githubusercontent.com/36476595/86122184-a956e280-bad7-11ea-9d51-837bc37c7ca4.png)

**Comment by Jupiter007-43** [comment] 2020-06-30 18:40
🤔 Very strange because this cursor exist into Yaru files with the good name.

**Comment by Jupiter007-43** [comment] 2020-06-30 18:43
I accidentally open Gnome-map and look at the cursor:
![Capture d’écran du 2020-06-30 20-41-37](https://user-images.githubusercontent.com/36476595/86164469-1dae7780-bb12-11ea-93f7-271632bcf45d.png)

I don't understand any more...

**Comment by Jupiter007-43** [comment] 2020-07-01 18:06
Same issue into ToDo:

![Capture d’écran du 2020-07-01 20-03-45](https://user-images.githubusercontent.com/36476595/86276965-2d8f8f80-bbd6-11ea-8475-0e075f43b537.png)

**Comment by Feichtmeier** [comment] 2020-07-01 19:28
I think there is something wrong with our cursor set. We had several issues around wrong cursors in the past.
I think in gnome disk space app the wrong spinner is shown all the time :thinking:

**Comment by Jupiter007-43** [comment] 2020-07-02 09:03
Yes, and it make me think about this other issue with Qt: #1996

**Comment by madsrh** [comment] 2020-07-03 10:42
Is this something you could look into @ubuntujaggers ?

**Comment by ubuntujaggers** [comment] 2020-07-03 15:58
Ohhhhh... So the hand sometimes falls back to Adwaita? Yes I will 👍

**Comment by avil25** [comment] 2020-07-10 16:52
Is this issue similar to the one reporter on the paper icon?
[#723](https://github.com/snwh/paper-icon-theme/pull/723)

**Comment by Feichtmeier** [comment] 2020-07-10 17:17
@avil25 thanks for the tip, @Jupiter007-43 could you test this solution?

**Comment by Jupiter007-43** [comment] 2020-07-10 18:49
🤔 But Adwaita isn't into Inherit (Inherits=Humanity,hicolor):
https://github.com/ubuntu/yaru/blob/master/icons/Suru/index.theme#L4

**Comment by ubuntujaggers** [comment] 2020-09-27 10:18
Okay, so basically we still don't understand this one?  We have the open hand cursor in our set but in some apps it shows the Adwaita version, right?

**Comment by madsrh** [comment] 2020-09-27 13:44
> We have the open hand cursor in our set but in some apps it shows the Adwaita version, right?

That is that problem. I wonder if this issue can be recreated with other cursor themes.

**Comment by Feichtmeier** [comment] 2020-09-27 13:55
Baobab also shows the wrong busy cursor

**Comment by ubuntujaggers** [comment] 2020-09-27 14:14
> Same issue into ToDo: 

I can't reproduce this...

To do:

![image](https://user-images.githubusercontent.com/38893390/94367043-d2394480-00d3-11eb-9d40-e5a850d27072.png)

Baobab also has the right "busy" cursor, tried both apps with light and dark theme...

**Comment by Jupiter007-43** [comment] 2020-09-27 14:41
> I can't reproduce this...
>
> Baobab also has the right "busy" cursor, tried both apps with light and dark theme...

Indeed, it seems to be fixed on 20.10 (but not on 20.04).

**Comment by ubuntujaggers** [comment] 2020-09-27 15:36
Do we think this is just a problem with apps then?

**Comment by Jupiter007-43** [comment] 2020-09-27 17:08
> Do we think this is just a problem with apps then?

As the problem cannot be reproduced on 20.10 (with the same build of Yaru) I think yes.

**Comment by Feichtmeier** [comment] 2020-09-29 07:50
If the problem can't be represented with 20.10, let's close it as it seems that it has always been a app problem and not in our cursor theme

**Closed** 2020-09-29 07:50 UTC
Labels: Area: icon theme
