### ISSUE TITLE
network-wireless-connected-symbolic.svg is not monochrome

### ISSUE THREAD

**Issue by fthx** [ubuntu/yaru#2344] opened 2020-09-02 06:44 UTC
Hi,

Ubuntu 20.04 up to date, Yaru 20.04.8, Gnome session

Well, after https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887420 I reported here too, I reached a similar issue with a green wifi symbolic icon in Gnome system menu. It happened few seconds during a restart of my wifi router but I did not have the time to copy the screen.

**Comment by Feichtmeier** [comment] 2020-09-02 07:20
Hello, this should be fixed after you've updated your system (new yaru release)

**Comment by fthx** [comment] 2020-09-02 07:36
Which Yaru version should have fixed that ?

> Ubuntu 20.04 up to date, Yaru 20.04.8, Gnome session

**Comment by Feichtmeier** [comment] 2020-09-02 08:08
This is the PR that fixed it: https://github.com/ubuntu/yaru/pull/2252

This is the PR of the 20.04.8 release: https://github.com/ubuntu/yaru/pull/2239

This is the SRU on launchpad: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1887420

So if you have yaru icon theme 20.04.8 and this is not fixed @ubuntujaggers needs to check again if he missed something

**Comment by Feichtmeier** [comment] 2020-09-02 08:08
Please post a screenshot of your yaru version in the terminal and the green icon

**Comment by ubuntujaggers** [comment] 2020-09-02 08:13
Hi guys, that fix should be for the mobile data ("cellular") symbol rather than wifi, so think this is a different thing. Also sounds like it only lasted a couple of seconds so maybe it's a problem with a symbol that's used during wifi connection. I'll have a look 👍

**Comment by Feichtmeier** [comment] 2020-09-02 08:49
@fthx let's please specify the name of the icon you talk about. This issue says "Wifi" but the launchpad bug says "network-cellular-connected-symbolic"

Since I've never seen a green wifi icon on my machine, I guess you are talking about "network-cellular-connected-symbolic" right? 

https://github.com/ubuntu/yaru/blob/master/icons/Suru/scalable/status/network-cellular-connected-symbolic.svg
It's monochrome. So maybe we've missed a symlink to the name which is actually used?

I think I am going to test this myself on my ubuntu laptop with my phone... brb

**Comment by Feichtmeier** [comment] 2020-09-02 08:55
![nope](https://user-images.githubusercontent.com/15329494/91960888-bc21a980-ed0a-11ea-87ca-f892ca489e60.png)

Nope @fthx it's fixed -> monochrome

Maybe something went wrong with using proposed? Using this proposed channel is sometimes risky

**Comment by fthx** [comment] 2020-09-02 09:01
Here I'm talking about a new issue, not the (solved) old one.
I found the culprit, I guess : 

![image](https://user-images.githubusercontent.com/23138504/91961422-73b6bb80-ed0b-11ea-8174-0db4a43b8877.png)

![image](https://user-images.githubusercontent.com/23138504/91961520-921cb700-ed0b-11ea-8435-3cabde172f38.png)

in : 

![image](https://user-images.githubusercontent.com/23138504/91961580-a496f080-ed0b-11ea-8f4e-d5e7ab6d99f5.png)

**Comment by Feichtmeier** [comment] 2020-09-02 09:03
Aha! Thanks for clarifying!

How can we activate this icon? It's not bluetooth tethering (that's cellular) so what is it?

**Comment by fthx** [comment] 2020-09-02 09:04
Only a wifi stuff, I did not use any other network this morning.

**Comment by Feichtmeier** [comment] 2020-09-02 09:06
Hehe :) Okay, I think everyone here is using a wifi connection. Which is def. monochrome. 
![grafik](https://user-images.githubusercontent.com/15329494/91962097-5f26f300-ed0c-11ea-81d9-47dac2c3ccd9.png)

So with what magic did you use this green icon?

**Comment by fthx** [comment] 2020-09-02 09:12
Here is Adwaita's : 
![image](https://user-images.githubusercontent.com/23138504/91962472-df4d5880-ed0c-11ea-9d54-20676b768e54.png)

Well, this green icon cames to me without I called it. ;-) 
It **only** appeared in the system menu, not the top panel.

> The green wifi icon appeared only in the system menu, not the top panel. I never noticed that before but I rarely open the system menu during an automatic wifi connection.

**Comment by Feichtmeier** [comment] 2020-09-02 09:23
ooook and where exactly in gnome control center?

![grafik](https://user-images.githubusercontent.com/15329494/91963823-ae6e2300-ed0e-11ea-9051-70bb7fd56ad9.png)

**Comment by fthx** [comment] 2020-09-02 09:28
No, in the system menu : 

![image](https://user-images.githubusercontent.com/23138504/91964439-6dc2d980-ed0f-11ea-973d-3da4a0ba9078.png)

**Comment by Feichtmeier** [comment] 2020-09-02 09:30
Okay, also monochrome.

When you figured or we figured out how to reproduce this green icon let's see if a PR is indeed needed. Please try to test this and make a screencast or something (https://extensions.gnome.org/extension/690/easyscreencast/)

**Comment by ubuntujaggers** [comment] 2020-09-02 19:47
Okay, I think I've got it.

I just restarted my wifi and it was monochrome all the way, **but** as fthx points out we do have a green icon called network-wireless-connected-symbolic in our set.

The specific icons for the different connection strengths (excellent, good, etc.) are monochrome and I think those are normally the icons we see.  However, in this case, perhaps it took a moment to work out what the signal strength was, and that's why it showed the generic "connected" icon (which is green) for a few seconds before it caught up with itself and showed the specific icon for the signal strength.  That would result in the behaviour described.

**Comment by fthx** [comment] 2020-09-02 20:48
Yes that's what I think too, because I tried some hours ago, as you did, to just restart my wifi, not my router, and all was monochrome. So I thought it was some undefined wifi state, waiting for my router's complete restarting.
So thanks !! Some more Yaru greenwashing ;-) .

**Closed** 2020-09-03 19:15 UTC
Labels: Area: icon theme, Status: info-needed
