### ISSUE TITLE
Buttons with images badly broken in QGtkStyle apps

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1405] opened 2019-06-12 05:10 UTC
## Expected Behavior

Images in buttons are properly positioned.

## Actual Behavior

![image](https://user-images.githubusercontent.com/2845433/59324784-cd6e3880-8cb6-11e9-954a-ea7ba54525a4.png)

## Steps to Reproduce the Problem

  1. Install qt5-style-plugins
  1. Use the QT_QPA_PLATFORMTHEME=gtk2 or QT_QPA_PLATFORMTHEME=qt5ct with gtk2 theme.
  1. Run qbittorrent to see the buttons in the screenshot above.
  1. Run calibre, go to preferences/plugins, etc. There are plenty of examples

Software that presents the issue:
- Name: qt5-style-plugins
- Version: 5.0.0+git23.g335dbec-2ubuntu5

**Comment by clobrano** [comment] 2019-06-12 07:45
Hi @memeplex,

in Yaru we have no explicit support for qt5 style, that is, there is no code that we can change to fix this issue. Have you contacted the other maintainers to ask if it's something on their side?

**Comment by memeplex** [comment] 2019-06-12 09:08
I'm reporting here because the gtk2 version of yaru may be causing this issue. If not, I may contact the qt plugin team.

**Comment by clobrano** [comment] 2019-06-15 18:28
Our main references are the GTK2 apps here, if they are not affected by this issue, I imagine it's a qt plugin error first. Closing now, but ready to reopen it if the issue is on our side.

**Closed by clobrano** 2019-06-15 18:28 UTC
