### ISSUE TITLE
Dark menu with dark text in electron applications

### ISSUE THREAD

**Issue by paulwellnerbou** [ubuntu/yaru#969] opened 2018-11-16 07:06 UTC
## Actual Behavior

I am using Yaru (not the dark one) on a fresh Ubuntu 18.10 installation. There are some applications not picking up the correct color for menus:

This is gnome-terminal (this is how it is supposed to be, I suppose):

![screenshot from 2018-11-16 08-02-10](https://user-images.githubusercontent.com/1842543/48603190-f8d5b280-e975-11e8-82b0-b5044a3ede03.png)

This is how Slack looks (not as it is expected to be, but readably):

![screenshot from 2018-11-16 08-03-00](https://user-images.githubusercontent.com/1842543/48603217-14d95400-e976-11e8-8a6b-5197b5f9f303.png)

And this is how Skype and Atom beta look like (not readable at all):

![screenshot from 2018-11-16 08-04-04](https://user-images.githubusercontent.com/1842543/48603277-3df9e480-e976-11e8-9d1f-8e89c3c91bea.png)

Atom at least shows the text of the menus when the window does not have the focus, while skype does not show them at all.

Is there a tweak I can do at the theme to change this menu color? Switching to Yaru dark fixes it, alle fonts are bright then and readable. But I'd prefer the light one.

Thanks!

**Comment by Feichtmeier** [comment] 2018-11-16 11:18
Hi there, I believe electron apps have some problems with reading the dark/light gtk themes currently. Could you check how other gtk themes behave? Thanks for reporting

**Comment by fitojb** [comment] 2018-11-17 07:00
There is nothing to do here except waiting for affected applications to update away from the buggy Electron version they’re using. It appears that the problem is fixed in Electron 3.0.1.

**Comment by clobrano** [comment] 2018-11-17 07:16
Thanks @fitojb, closing this then. Feel free to reopen it if there are new info

**Comment by galgalesh** [comment] 2018-11-28 13:11
@fitojb this might not fixed in Electron 3.0.1. according to https://github.com/electron/electron/issues/13381. That issue was fixed in 3.0.1. but it introduced [a new issue](https://github.com/electron/electron/issues/13381#issuecomment-425636296). Can you confirm that the new issue is now also fixed?

That version of electron fixes the menubar background color, but the menubar font color is still incorrect. As a result, the menubar on Yaru is now completely black. See the following screenshots.

# Before "fix"

![image](https://user-images.githubusercontent.com/1492981/49153699-bff2f180-f316-11e8-88cb-b60d4b0df1e1.png)

# After "fix"

![image](https://user-images.githubusercontent.com/1492981/49153717-caad8680-f316-11e8-9c45-ac3b6a2c1b77.png)

For example, this shows in the just released Mattermost desktop clent (4.2.0) https://github.com/snapcrafters/mattermost-desktop/pull/16#event-1992299001

**Comment by fitojb** [comment] 2018-11-28 13:30
@galgalesh No, I can’t confirm. I avoid Electron programs altogether. I was just reporting a finding.

**Comment by Feichtmeier** [comment] 2018-11-28 13:35
I can confirm this using vscode!

**Comment by galgalesh** [comment] 2018-11-29 12:00
Update: proposed patch in electron: https://github.com/electron/electron/pull/15878

It will probably take a while for all the applications to use the updated electron version, so temporarily patching this in Yaru might be a good idea.

**Comment by clobrano** [comment] 2018-11-29 13:31
> We could eventually fix this with the jet menus (not popovers) for the light theme, or by changing our menubar to white

I would prefer the first

**Comment by Feichtmeier** [comment] 2018-12-03 09:17
Ah never mind then if the fix is happening :) Maybe we should close it here? vscode is usally pretty fast with including the upstream code.
Black menus for the dark theme are a lot easier than black menus for the light theme so it would be a lot of hassle just for this issue.

**Comment by clobrano** [comment] 2018-12-03 09:18
> Maybe we should close it here?

Right, closing this now, thanks all!

**Closed by clobrano** 2018-12-03 09:18 UTC
