### ISSUE TITLE
Desktop text color on ubuntu 18.04

### ISSUE THREAD

**Issue by xavier83ar** [ubuntu/yaru#1574] opened 2019-10-15 16:12 UTC
## Expected Behavior
Icon text on desktop should be light with dark shadow, so it's readable on both: dark and light wallpapers.
Screenshot from the old communitheme:
![image](https://user-images.githubusercontent.com/1458700/66848962-686c6d00-ef4c-11e9-8793-2cfdded69f58.png)

## Actual Behavior
Text is dark with no contrast shadow, so it is not readable on dark backgrounds.
Screenshot with Yaru theme:
![image](https://user-images.githubusercontent.com/1458700/66849232-efb9e080-ef4c-11e9-8d07-7046dd88c243.png)

## Specifications
Ubuntu  18.04.3
```
Package: yaru-theme-gtk
Version: 19.10.4+201910110019+7950b7c~ubuntu18.04.1
```

    `$ snap info communitheme`
```
Inspiron-7373:~$ snap info communitheme 
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will
  become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme
  on Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and
  select the "Ubuntu with communitheme snap" session from the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 2019-03-13
channels:
  stable:    0.1    2019-03-13 (1768) 16MB -
  candidate: ↑                             
  beta:      ↑                             
  edge:      29.133 2019-10-10 (1862) 18MB -
installed:   0.1               (1768) 16MB -

```

**Comment by clobrano** [comment] 2019-10-15 16:40
Hi, 
Thanks for contributing to Yaru!
You're report has both Deb package and snap one, which are you using?
For 18.04 I suggest to use the snap one and the edge channel has already the fix for this problem

**Comment by xavier83ar** [comment] 2019-10-15 17:30
Hi, that's correct. How may I know that? 

Honestly, I don't know why I do have installed deb and snap, I have also installed the old communitheme, I guess it's because I've adopted this new theme in early stages of development and I may have installed more than once.

What I can tell is that I've a few session installed:
![image](https://user-images.githubusercontent.com/1458700/66854706-3a8d2580-ef58-11e9-8b06-f61ca63e4ffd.png)

And I'm using ubuntu with snap communitheme on wayland (mostly), and some times on xorg for software compatibility reasons, and in both cases the issue is present.

**Comment by xavier83ar** [comment] 2019-10-15 17:53
I've tried changing the snap to edge (v29.133) (refresh, logout, login) and the bug is still present. 

[off topic] Also, the gnome shell menus are light now, is it what's coming? Please, tell me it doesn't :(   I've already turn it back to stable to stay with dark menus.

**Comment by clobrano** [comment] 2019-10-16 07:08
> I've tried changing the snap to edge (v29.133) (refresh, logout, login) and the bug is still present.

I can't confirm this, here is my desktop with edge channel installed and the issue looks fixed

![image](https://user-images.githubusercontent.com/2883614/66895886-0ebf7d80-eff4-11e9-8720-3007c0d9403f.png)

I could suggest you to uninstall both deb and snap, fallback to something else for a reboot and then reinstall the snap.

> [off topic] Also, the gnome shell menus are light now, is it what's coming? Please, tell me it doesn't :( I've already turn it back to stable to stay with dark menus.

This is "temporary", but not sure how fast we can provide both dark and light gnome shell, you can track the change here #1483

**Comment by Feichtmeier** [comment] 2019-10-19 02:31
Can't confirm this neither on my 18.04 with communitheme from edge channel

**Comment by clobrano** [comment] 2019-10-20 21:17
Closing it now since it's not reproducible, but feel free to reopen it if you have something new to report

**Closed by clobrano** 2019-10-20 21:17 UTC
Labels: Area: snap, Status: Not reproducible
