### ISSUE TITLE
Nautilus list view with expandable folders: selection frame is misaligned.

### ISSUE THREAD

**Issue by jlemonde** [ubuntu/yaru#2860] opened 2021-05-20 16:11 UTC
When folder expansion is enabled for list view in Nautilus, when selecting a folder (or any item), the selection frame is misaligned. Note that I don't know whether "selection frame" is the correct term. It might be "focus frame"

**Steps to Reproduce the Problem**

Enable expandable folders in Nautilus, then select a folder, then after a short delay click a second time on that folder to let the selection frame appear.

Alternatively, try navigating with the up and down keys with expandable folders enabled.

**Software that presents the issue**

GNOME nautilus 3.38.2 in Ubuntu 21.04 x86_64

**Yaru version**

yaru-theme-gtk version 21.04.1

**Screenshots**

Here it is all normally aligned:
![Capture d’écran de 2021-05-20 17-55-38](https://user-images.githubusercontent.com/30623792/119012132-0aa8ce00-b996-11eb-8550-5de7712dd864.png)
Then here, when expandable folders are enabled, it is misaligned:
![Capture d’écran de 2021-05-20 17-54-29](https://user-images.githubusercontent.com/30623792/119012149-0e3c5500-b996-11eb-81cb-827ce28db46b.png)

**Upstream check**

It does not happen in Adwaita. Only in Yaru.

![Capture d’écran de 2021-05-20 18-08-08](https://user-images.githubusercontent.com/30623792/119012538-6b380b00-b996-11eb-95f1-92920cc3d4ba.png)

By the way, when reverting to Yaru, the bug disappeared. Please try to reproduce.

**Additional personal remark**

I dislike the fact that the selection box does not reach the right end in Yaru but only encloses the text. I prefer it much more the way it is in Adwaita.

**Comment by jlemonde** [comment] 2021-05-21 07:41
This is strange! Thank you for testing! My Ubuntu system was fresh-installed with 21.04 a week ahead of release, and now that I think of it, I only tried out the ["Nordic"](https://www.gnome-look.org/p/1267246/) theme before reverting back to Yaru. Now that I try again to switch to Nordic and back to Yaru, the bug is back. And when I switch to Adwaita and back to Yaru, the bug is gone.

I wonder whether it is possible that the Yaru theme lacks a rule somewhere, but relies on what was installed before as a fall-back.

**Comment by jlemonde** [comment] 2021-05-21 07:55
Rectification: the bug does not always disappear when switching to Adwaita and back to Yaru. I managed to remove the bug twice in a dozen of attempts, so there may be something different going on. But Enabling the Nordic theme triggered the bug in Yaru for (almost) sure.

Is there a way for me to reinstall yaru? I tried `sudo apt install --reinstall yaru-theme-gtk` but nothing changed. Note that I don't have GNOME 40.

**Comment by jlemonde** [comment] 2021-05-21 07:59
PS: Now I am getting the bug in Adwaita as well. It may be totally unrelated to Yaru, thus. So strange...

**Comment by Jupi007** [comment] 2021-05-21 09:23
Hi @jlemonde,
I successfully reproduced your issue on my VM. I tested: preinstalled Yaru, Yaru from master, and Adwaita. The problem is always visible.
I think it is related to Nautilus itself because on my own computer I'm using Gnome 40 with Nautilus 40, and the problem is not present at all.
So I close this issue. Thanks anyway for your report, it's very appreciated :)

**Closed** 2021-05-25 09:32 UTC
Labels: Area: gtk3
