### ISSUE TITLE
Yaru-MATE - Incorrect background colour for Caja location text box

### ISSUE THREAD

**Issue by franksmcb** [ubuntu/yaru#2772] opened 2021-04-02 21:37 UTC
Please see bug report https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/74

Per report: In Caja, press CTRL+L to toggle the location bar. On Yaru-MATE-dark, the text box should be a dark background, but it currently is white and clashes with the text colour.

![Screenshot_2021-04-02 -2 21 04  Yaru-MATE-dark Incorrect background colour for Caja location text box · Issue #74 · ubuntu-ma](https://user-images.githubusercontent.com/44311495/113455953-2e558c00-93c9-11eb-90db-55e805ddd2ae.png)

Yaru MATE Light having dark location bar bg. It is happening when we are changing from light to dark or dark to light (but not consistently enough). If we logout and re-login, it gets corrected (for both scenarios). 21.04.6 as well.

Screenshot at 2021-04-02 19-15-30
![Screenshot_2021-04-02  21 04  Yaru-MATE-dark Incorrect background colour for Caja location text box · Issue #74 · ubuntu-ma](https://user-images.githubusercontent.com/44311495/113455961-34e40380-93c9-11eb-8a65-aaa2df4d5d66.png)

**Comment by flexiondotorg** [comment] 2021-04-06 11:37
@Feichtmeier Any chance you could take a look at this?

**Comment by Jupi007** [comment] 2021-04-06 18:29
It is really related with Yaru itself?
I tried that and indeed, it appears only when switching theme variant. Btw running `killall caja` fix the problem.
🤔 Isn't it just Caja which isn't reloading Yaru correctly?

**Comment by Feichtmeier** [comment] 2021-04-06 19:07
Hi @flexiondotorg 
I actually think similar to @Jupi007 here and I am also convinced that this is not caused by our CSS.
Since you made the very wise decision to only ship a full light and a full dark version, we can be sure here that no GtkEntry is somehow overwritten by inverted styling (like in the yaru default styling :cry: ) :smile: 

Can you @flexiondotorg and @franksmcb confirm that this does not happen with other themes?

**Comment by flexiondotorg** [comment] 2022-03-23 17:02
This is a bug in Caja. @Jupi007 please close this issue.

**Closed** 2022-03-23 17:03 UTC
