### ISSUE TITLE
Yaru-dark notification color problem 

### ISSUE THREAD

**Issue by diaper151** [ubuntu/yaru#1023] opened 2018-12-06 18:41 UTC
First, thanks for making such a great theme.
Yaru-dark works fine except for notifications popup. 
![screenshot from 2018-12-07 02-32-23](https://user-images.githubusercontent.com/10728152/49604354-a150c280-f9c8-11e8-9efc-7878854de4b7.png)

I checked /usr/share/themes/Yaru-dark/gtk-3.0/gtk.css, the code seems fine with dark-background.

But somehow it's not working properly, can someone help?

**Comment by Feichtmeier** [comment] 2018-12-06 18:50
Hi there thanks for the nice words :)

The shell theme is sadly not connected to the gtk theme! 
So there is no way currently to change the shell theme when the gtk theme changes to dark :)

Apart from the light/drk gtk themes we ended with a mixed theme for the shell. 
I personally feel comfortable with the mixed theme. The reason for light notifications and dialogues is to give people a chance to notice the notifications and having a friendly color for dialogues. 

How do you currently feel about this @clobrano @madsrh ?

**Comment by Paz-it** [comment] 2018-12-06 20:59
If I may, I'd say I feel comfortable with it and  to you @diaper151  - It's not a bug, it is intentional  .

**Comment by Feichtmeier** [comment] 2018-12-06 21:02
Yeah that mixed style was a hot topic back then and there still pops up issues here and there. :man_shrugging: 
I think they look great and give the best usability, but I can understand that 1) some people might prefer them to look like our shell popups and 2) some people might be iritated

**Comment by diaper151** [comment] 2018-12-06 21:09
I appreciate your replies. Seem that I have to adapt it : )

**Comment by Feichtmeier** [comment] 2018-12-06 21:41
Closing after taking to Carlo

**Closed by Feichtmeier** 2018-12-06 21:41 UTC

**Comment by vdiravka** [comment] 2019-06-01 16:17
I want a dark notification. How to get it?

**Comment by Feichtmeier** [comment] 2019-06-01 16:51
We would need to separate the dark shell version from the light shell version. 
I thought I'd working on this soon but no promises.
The other story is how to activate it... No idea really. Once the variant is set I see no way to change it. I'm going to ask

**Comment by anonsachin** [comment] 2019-06-27 14:23
can someone tell me what are the css selectors are for the notification and other popups so, I can change them my self in the gtk.css

**Comment by clobrano** [comment] 2019-06-28 07:53
As said, this is not the gtk part, so you cannot change it modifying gtk.css
