### ISSUE TITLE
System sounds do not play even when enabled

### ISSUE THREAD

**Issue by chaNcharge** [ubuntu/yaru#968] opened 2018-11-16 01:06 UTC
## Expected Behavior

Doing something like displaying a warning or error should play an error sound.

## Actual Behavior

No sound at all, even though the event-sounds setting is enabled through dconf or Tweaks. The other Yaru system sounds are present in /usr/share/sounds/Yaru yet nothing still plays.

## Steps to Reproduce the Problem

Do something that should produce an error noise, like emptying the trash or quitting terminal with a running process open.

## Specifications

Installed from apt repository, yaru-theme-sound version 18.10.6

Software that presents the issue:
- Name: Ubuntu Cosmic Cuttlefish
- Version: 18.10

**Comment by madsrh** [comment] 2018-11-17 10:34
@Feichtmeier will the fix from [here ](https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/issues/4) also fix this issue?

**Comment by Feichtmeier** [comment] 2018-11-17 12:02
I experienced this on 18.04 with the snap.

This issue is about 18.10 installed from.... apt repository? You mean that you are just using 18.10 default settings and the sounds are missing @chaNcharge ? Or did you install something else?

**Comment by chaNcharge** [comment] 2018-11-17 20:51
I'm using the apt repository on 18.10. I just tried reinstalling yaru-theme-sound and still, no sounds are playing.

**Comment by chaNcharge** [comment] 2018-11-17 21:12
Just tried on a fresh install, realized only some sounds play. For example, the warning that shows when closing multiple tabs in firefox plays the sound, and adding a usb device plays a sound, but nothing much else.

**Comment by madsrh** [comment] 2018-11-17 21:48
These are the sounds that should play: https://github.com/ubuntu/yaru/tree/master/sounds/src/stereo

**Comment by chaNcharge** [comment] 2018-11-18 01:05
Yeah, I noticed that when I looked in /usr/share/sounds/Yaru but not all of them seem to work. Am I setting stuff up wrong? I shouldn't need to install a snap if it's included on 18.10.

**Comment by Feichtmeier** [comment] 2018-11-22 19:07
You should not need anything in 18.10
The sound theme is preinstalled and selected by default

**Comment by chaNcharge** [comment] 2018-11-22 22:47
Strange, if that's the case, shouldn't system sounds be playing?

**Comment by Feichtmeier** [comment] 2018-11-22 23:00
It play on my relatively fresh 18.10 installation :man_shrugging: 
Sure you didn't modify anything? :D

**Comment by Feichtmeier** [comment] 2018-12-02 12:46
Hm I will double check this, thank you! 
That would be a pretty bad/important issue

**Comment by Feichtmeier** [comment] 2018-12-02 13:17
Damn I can confirm this!

Volume Works, but the sound is also a little bit distorted! 
Trash empty and usb insert did not work : /

Even after resetting sound settings to "Yaru" in the dcong editor and switching to "Ubuntu" session

Just checked all your sound files @madsrh and I am honest: I haven't heard most of the sounds while in yaru/communitheme sessions.

But now that I finally installed dconfi-editor (Hooray) when I set the the value to "communitheme" the volume (distorted) sound returns. Also an alert sound is there when I press "emtpy trash" in 18.04 snap installation but not "trash is emtpy now"

![image](https://user-images.githubusercontent.com/15329494/49340188-b7632980-f63c-11e8-90b5-ecf9b9c7c356.png)

**Comment by madsrh** [comment] 2018-12-02 15:47
> Is it because of the snap?

What I mean is that back in 17.10 I stored the files in **usr - share - sounds - comminutheme - stereo** and that seemed to work fine, but I could be wrong.

**Comment by Feichtmeier** [comment] 2018-12-02 16:17
In my 18.04 snap installation they are stored here
/snap/communitheme/current/share/sounds/communitheme/stereo
And the sound is very clear when I play them with totem (gnome video)

I do not receive/hear:
trash-empty, when the trash is emtied
desktop-login (in 18.10)

I hear:
device-added
device-removed
dialoge-question
audio-volume-change (but when I play it via the volume button on my keyboard it sounds distorted or with too much drive)

**Comment by chaNcharge** [comment] 2018-12-02 22:01
I reported the issue on launchpad in case it is an issue with Ubuntu: https://bugs.launchpad.net/ubuntu/+source/libcanberra/+bug/1805523

**Comment by Feichtmeier** [comment] 2018-12-12 09:44
Does anyone has a 18.10 installation which is not in a VM? And if yes, does that one hear a login sound?

Other than that only the "trash just got emptied"-sound is missing: does gnome really support this? Need to check this with the default sound

**Comment by clobrano** [comment] 2018-12-12 10:14
No login sound on my machine

**Comment by Feichtmeier** [comment] 2018-12-12 10:21
Did we ever check if GDM actually supports this? :D

**Comment by madsrh** [comment] 2018-12-12 10:23
> No login sound on my machine

The login sound isn't played by default - you have to added it manually

**Comment by Feichtmeier** [comment] 2018-12-12 10:33
Yes! I watched a youtube video

![image](https://user-images.githubusercontent.com/15329494/49863985-c0ed4e00-fe01-11e8-8ec7-3f8135822109.png)

This works xD Awesome sound - why isnt this enabled by default?

**Comment by Feichtmeier** [comment] 2018-12-12 10:39
/usr/bin/canberra-gtk-play --id="desktop-login" --description="GNOME Login"

**Comment by didrocks** [comment] 2018-12-12 10:55
I think gnome-session has another sound login mechanism? We definitively didn't use an external process to play it.

However, we removed the login sound a while ago. It could be something to revisit. I would suggest either opening a thread on the hub (hoping others than me on the desktop team will have a look/pick it up) or during our weekly meeting on IRC.

**Comment by madsrh** [comment] 2019-01-10 00:04
Slightly off topic: 

> However, we removed the login sound a while ago. It could be something to revisit. I would suggest either opening a thread on the hub (hoping others than me on the desktop team will have a look/pick it up) or during our weekly meeting on IRC.

This is such a huge annoyance for many people, so there has to be an easy way to enable/disable it. Would this be something upstream would be interested in or something we would need to carry a patch for @didrocks ?

![image](https://user-images.githubusercontent.com/3986894/50937062-7f88a680-1472-11e9-9240-377367058edd.png)

**Comment by Feichtmeier** [comment] 2019-01-27 01:02
Is the initial issue actually still happening for anyone?
I didn't find any yaru sound that is not playint when a freedesktop sound would play. So when a freedesktop sound is not played it is the same for yaru. Making me think that everything is "ok" from our side.

**Comment by madsrh** [comment] 2019-01-27 18:51
As I understand it, the bug is that sounds for some actions are missing when comparing 18.04 to 18.10 or 19.04.

>  ...So when a freedesktop sound is not played it is the same for yaru...

Yeah, our files are correctly names, so since this is also happening for the freedesktop sounds, this is IMO an upstream bug and it has [already been reported](https://github.com/ubuntu/yaru/issues/968#issuecomment-443546337). I'll close this issue here for now - let me know if you disagree @chaNcharge or anyone else 😃

**Closed by madsrh** 2019-01-27 18:51 UTC
Labels: Sound-Theme, bug
