### ISSUE TITLE
Firefox tab on hover reaction

### ISSUE THREAD

**Issue by mivoligo** [ubuntu/yaru#717] opened 2018-08-14 17:25 UTC
Not sure if a bug or a feature.

Yaru from stable snap.

When I hover over a nonactive tab in Firefox, the "frame" around that tab does look a bit strange. The vertical lines go higher than the horizontal line. Also their colors seems to be a bit different at least when checked in GIMP. 
Here's the screenshot 400% zoomed in GIMP:
![zrzut ekranu z 2018-08-14 18-20-50](https://user-images.githubusercontent.com/1629120/44107458-59bc3c02-9fef-11e8-9975-65540463f72f.png)

**Comment by clobrano** [comment] 2018-08-14 17:36
could you reproduce this on Yaru only?

**Comment by mivoligo** [comment] 2018-08-14 17:43
This is in Adwaita. Hovering over the first tab:
![zrzut ekranu z 2018-08-14 18-42-41](https://user-images.githubusercontent.com/1629120/44108344-ff9354a6-9ff1-11e8-9bf7-80ad1cd171ae.png)

**Comment by clobrano** [comment] 2018-08-14 17:58
We don't have the separation between titlebar and tabs, but the issue is the same. I don't know if is Firefox doing something wrong or on purpose, but it is not up to Yaru.

Closing this

**Closed by clobrano** 2018-08-14 17:58 UTC
