### ISSUE TITLE
Remove the rounded corners from the top of the windows.

### ISSUE THREAD

**Issue by lvitals** [ubuntu/yaru#1672] opened 2019-12-19 22:22 UTC
## Actual Behavior

Remove the rounded corners from the top of the windows. Designer makes no sense because the rounded corners of the panel have been removed and do not fit the window. Rounded corners cause OSD Panel issue for Firefox and Chrome.

![screenshot_448_1](https://user-images.githubusercontent.com/2145794/71213916-8d09fb80-2293-11ea-8fa3-aae11de0f56b.png)

![2019-12-19_18-10](https://user-images.githubusercontent.com/2145794/71213840-5fbd4d80-2293-11ea-989c-03cbe973ff0d.png)

![Captura de tela de 2019-12-19 17-59-46](https://user-images.githubusercontent.com/2145794/71213803-4ddbaa80-2293-11ea-981b-87b821ce8687.png)

![Captura de tela de 2019-12-19 17-56-37](https://user-images.githubusercontent.com/2145794/71213894-7c598580-2293-11ea-8dff-c554ff71e2bd.png)

## Expected Behavior

![2019-12-19_18-09](https://user-images.githubusercontent.com/2145794/71214022-aa3eca00-2293-11ea-800c-78d751ec4986.png)

![Captura de tela de 2019-12-19 18-05-49](https://user-images.githubusercontent.com/2145794/71214386-ee31cf00-2293-11ea-900c-d6a07c337a04.png)

## Steps to Reproduce the Problem

  1. Install Ubuntu 19.10 vanilla

## Yaru version

Please report the Yaru version in your system using one of the following commands

    `$ apt show yaru-theme-gnome-shell`

```console
Package: yaru-theme-gnome-shell
Version: 19.10.4
Priority: optional
Section: misc
Source: yaru-theme
Origin: Ubuntu
Maintainer: Ubuntu Desktop Team <ubuntu-desktop@lists.ubuntu.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 523 kB
Homepage: https://community.ubuntu.com/c/desktop/theme-refresh
Task: ubuntu-desktop-minimal, ubuntu-desktop, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-minimal-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages, ubuntu-desktop-default-languages
Supported: 9m
Download-Size: 109 kB
APT-Manual-Installed: yes
APT-Sources: http://br.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
Description: Yaru GNOME Shell desktop theme from the Ubuntu Community
 This is the theme that is shaped by the community on the Ubuntu hub.
 .
 This package contains the GNOME Shell theme part
 .
 If you want to follow development, more information here:
 https://community.ubuntu.com/c/desktop/theme-refresh.
```

cc: @madsrh @Feichtmeier @giox069

**Comment by clobrano** [comment] 2019-12-19 22:27
I think the problem is on Firefox side, not on Yaru's one, since the problem is visible only on Firefox tweaks. I didn't notice on chrome, but I can't double check right now. Rounded corners belong to our design regardless the shape of the panel.

**Comment by lvitals** [comment] 2019-12-19 22:44
> I think the problem is on Firefox side, not on Yaru's one, since the problem is visible only on Firefox tweaks. I didn't notice on chrome, but I can't double check right now. Rounded corners belong to our design regardless the shape of the panel.

I also think the problem is on the side of Firefox and Chrome, but I see that other themes like Plasma KDE, Windows 10, Elementary OS and others follow the designer with the top of the windows with straight lines. Only in Adwaita are rounded edges used. It is always harder to handle exceptions.

**Comment by madsrh** [comment] 2019-12-19 22:47
@lvitals Pretty awesome to attach a patch with your issue 👍 Even if we won't merge it, we REALLY appreciate the contribution.

We love the rounded corners and would hate to see them go because of a bug in Firefox.

> I think the problem is on Firefox side, not on Yaru's one, since the problem is visible only on Firefox tweaks. I didn't notice on chrome, but I can't double check right now. Rounded corners belong to our design regardless the shape of the panel.

+1 

Muito obrigado

**Comment by madsrh** [comment] 2019-12-19 22:54
**EDIT:** I've tried both X and Wayland and I can't reproduce this issue 🤷‍♂ 
![image](https://user-images.githubusercontent.com/3986894/71216300-732fdf00-22ba-11ea-90f2-147159769047.png)

**Comment by clobrano** [comment] 2019-12-19 23:04
On Wayland should not be reproducible, on X11 appears with small title bar, but can be disabled as well using a Firefox configuration that I can't remember at the moment, I'll report it tomorrow

**Comment by lvitals** [comment] 2019-12-19 23:33
> **EDIT:** I've tried both X and Wayland and I can't reproduce this issue 
> ![image](https://user-images.githubusercontent.com/3986894/71216300-732fdf00-22ba-11ea-90f2-147159769047.png)

1. Click the menu button and choose Customize.
2. Click the Title Bar buttonCheck the Title Bar checkbox in the lower left.
3. Click the green Exit Customize button.

**Comment by Feichtmeier** [comment] 2019-12-20 08:29
I agree that this issue is pretty annoying and we have an eye on this since... more than a year I think.

But let's rather get Firefox to fix this, currently we agreed that round corners is what we want (even before we full-rebased on adwaita)
I'll close this

**Closed by Feichtmeier** 2019-12-20 08:29 UTC

**Comment by Feichtmeier** [comment] 2019-12-20 08:37
https://bugzilla.mozilla.org/show_bug.cgi?id=1408360
