### ISSUE TITLE
Devel style class seems to be broken/unsupported

### ISSUE THREAD

**Issue by kaimast** [ubuntu/yaru#2526] opened 2021-01-08 05:16 UTC
**Expected Behavior**
I ran a development build of geary which uses the "devel" style class for its main window. It should either render like the regular version or have a style that indicates it is a development build.

**Actual Behavior**
The theme for the header bar seem to be broken. It renders grey/white text on top of a light gray background.

**Steps to Reproduce the Problem**
Install geary from source or run the flatpak nightly version. (Repository is here https://gitlab.gnome.org/GNOME/geary)

**Yaru version**
 20.10.6.1

**Screenshots**
![image](https://user-images.githubusercontent.com/4525445/103977186-4c02b480-513e-11eb-9e12-7ea0438ed3cc.png)

**Upstream check**
Renders fine with adwaita
![image](https://user-images.githubusercontent.com/4525445/103977164-40af8900-513e-11eb-9426-cb6abdb0bfda.png)

**Comment by Feichtmeier** [comment] 2021-01-08 08:13
@kaimast thanks!
Ah yeah the default theme :), right? 
Was just "yaru"? not "yaru-light"?

**Comment by kaimast** [comment] 2021-01-11 22:17
I just tested it on regular Yaru. It looks like it is using the font color of Yaru but the background color of Adwaita.

**Comment by Feichtmeier** [comment] 2021-01-12 16:19
@kaimast would you be able to try if this branch fixes this problem for the default theme with the inverted headerbar?

https://github.com/ubuntu/yaru/tree/GtkTheme_inverted_headerbar_dev_mode

Thanks in advance

**Comment by Feichtmeier** [comment] 2021-02-07 15:24
@clobrano since I know you use flatpak, could you test my branch and see if this fixes this issue? :smile: thanks in advance

**Comment by clobrano** [comment] 2021-02-07 16:30
Time to review how to test flatpak, isn't it?

**Comment by clobrano** [comment] 2021-02-07 17:52
@kaimast, how do you know you're testing Yaru 20.10.6.1? Official Flatpak version is stuck at 20.10.4

https://github.com/flathub/org.gtk.Gtk3theme.Yaru/blob/891cf56dcfcd8c76badeb465357aebaf341a90db/org.gtk.Gtk3theme.Yaru.json#L61

with which I get the following result (it isn't perfect, but the problem is different)

![image](https://user-images.githubusercontent.com/2883614/107154866-81850280-6975-11eb-9dfa-c255c44bd9fc.png)

I'm using this version of Geary
![image](https://user-images.githubusercontent.com/2883614/107154884-9366a580-6975-11eb-92e6-a05051938ebb.png)

**Comment by kaimast** [comment] 2021-02-07 18:42
Sorry for not testing this for so long. I removed the debian package and installed the branch you linked. Yaru-light and yaru-dark now look great, but for some reason yaru itself still has this issue...

@clobrano I am building/installing geary from source. 
![image](https://user-images.githubusercontent.com/4525445/107156097-e1fa4c80-6941-11eb-952a-6a77ed1fa9f6.png)

**Comment by Feichtmeier** [comment] 2021-02-07 19:15
@kaimast woops, fixed something could you try again please?

**Comment by kaimast** [comment] 2021-02-07 19:24
Yes, it looks great now! :smile:

**Comment by Feichtmeier** [comment] 2021-02-07 19:38
Screenshot or it didn't happen ^^

**Comment by kaimast** [comment] 2021-02-07 20:36
This is what it looks like now. 
![image](https://user-images.githubusercontent.com/4525445/107158738-cbf48800-6951-11eb-8059-d049f13ec915.png)

I noticed one more minor issue, though. When the window is not focused, it is still somewhat ugly. 

![image](https://user-images.githubusercontent.com/4525445/107158764-e3337580-6951-11eb-9fbc-26c6933edb14.png)

**Comment by Feichtmeier** [comment] 2021-02-07 20:45
Okay so separators and backdrop are also destroyed in _headerbar.scss

@Jupiter007-43 could you eventually take the devel style class into your headerbar.scss rework?

**Comment by Jupiter007-43** [comment] 2021-02-08 16:37
I fixed the backdrop problem, but the separator one is unfixable: the css selector isn't specific enough to target only headerbar separators:

![1](https://user-images.githubusercontent.com/36476595/107250738-47c70100-6a34-11eb-9fc0-99aa6d1143ed.png)
![2](https://user-images.githubusercontent.com/36476595/107250753-485f9780-6a34-11eb-9919-5e6bee88d437.png)

**Comment by Feichtmeier** [comment] 2021-02-09 07:37
Thanks @Jupiter007-43 !
I remember that the separators are created really weird. I believe it's some background or border-image

**Comment by Jupiter007-43** [comment] 2021-02-09 11:03
Where did you found this code snippet? I can't found it even with a circular search into my yaru clone folder 🤔

**Comment by Jupiter007-43** [comment] 2021-02-09 11:06
In fact the headerbar separator problem in Geary is because there's no _headerbar_ nor _.titlebar_ selector:

![1](https://user-images.githubusercontent.com/36476595/107352857-a2ac3700-6acc-11eb-8fcd-4b828540b895.png)

Even more, all other separators have exactly the same selector so there is no way to differentiate them 😓

**Comment by Feichtmeier** [comment] 2021-02-09 11:12
> In fact the headerbar separator problem in Geary is because there's no _headerbar_ nor _.titlebar_ selector:
> 
> ![1](https://user-images.githubusercontent.com/36476595/107352857-a2ac3700-6acc-11eb-8fcd-4b828540b895.png)
> 
> Even more, all other separators have exactly the same selector so there is no way to differentiate them sweat

oh man :face_with_head_bandage: 
Yeah... def. comes on the "this is why inverting the headerbar is a bad idea"-list

Even this is better than nothing so merge when you feel your PR is read and thank you very much!
This code snipped is from my phone from the yaru_1.0_safe branch

**Comment by Jupiter007-43** [comment] 2021-02-09 17:55
> oh man face_with_head_bandage
> Yeah... def. comes on the "this is why inverting the headerbar is a bad idea"-list

Sadly yes... I begin to think that dropping this inverted headerbar should be a very good time and problem saver 😓 (even if I love it)...

**Comment by Feichtmeier** [comment] 2021-02-09 18:55
Well, you don't need to convince me as you know. I've spent evenings to fix stuff in that headerbar :/
I still think that defaulting to dark would be a good compromise.
Let's get your pr in but don't close this issue. I plan to make a big post about all this dark light stuff.

**Comment by Feichtmeier** [comment] 2021-02-18 23:08
Fixed with #2628 
Except the separators

**Closed by Feichtmeier** 2021-02-18 23:08 UTC
Labels: Area: gtk3
