### ISSUE TITLE
Thunderbird: weird white line between menubar and toolbar

### ISSUE THREAD

**Issue by memeplex** [ubuntu/yaru#1580] opened 2019-10-20 04:20 UTC
Maybe it is intentional, but:

![image](https://user-images.githubusercontent.com/2845433/67154668-c98e9a80-f2d6-11e9-9bb5-6239d6e3c58b.png)

You can see the same white line in both the compose mail and the address book windows.

Also notice the contrast with the subtle dark line between the titlebar and the menubar.

## Expected Behavior

No white line between menubar and toolbar, instead maybe a dark line like the one between the titlebar and the menubar.

Or perhaps light menus, since in the new Yaru other menubars aren't dark (for example, in libreoffice).

## Actual Behavior

The white line you see in the screenshot, between both bars.

## Steps to Reproduce the Problem

  1. Open Thunderbird
  2. Compose a new email or
  3. Open the address book

## Software that presents the issue

- Name: Thunderbird
- Version: 68.1.2

## Yaru version

19.10.04

**Comment by Feichtmeier** [comment] 2019-10-20 05:54
This doesn't happen with thunderbird 60 on my 18.04 yet

We don't have thunderbird / mozilla widget specific styling for this one, so I don't see anything wrong from our side here. 
How does it look with adwaita-dark? If it looks the same, I would close it here and open it on mozilla

**Comment by clobrano** [comment] 2019-10-20 09:34
Thunderbird might take the black menus from Firefox styling, which in turn is needed to support compact headerbar

**Comment by memeplex** [comment] 2019-10-22 04:00
Maybe this is unrelated, but this is how firefox bookmark library looks:

![image](https://user-images.githubusercontent.com/2845433/67258494-56685e00-f467-11e9-9872-532cf38b3879.png)

**Comment by Feichtmeier** [comment] 2019-10-31 11:01
I just set up thunderbird on my 19.10 VM using thundebird 68
And I can not confirm this:
![Screenshot from 2019-10-31 11-59-54](https://user-images.githubusercontent.com/15329494/67941516-0f503a80-fbd6-11e9-9469-359d7023ae52.png)
![Screenshot from 2019-10-31 11-55-53](https://user-images.githubusercontent.com/15329494/67941517-0f503a80-fbd6-11e9-93c3-f17132677081.png)

**Comment by Feichtmeier** [comment] 2019-11-04 13:52
Second 19.10 installation - still can't confirm this issue - closing this for now as I am pretty sure this is not caused by us what happened in your installation :)

**Closed by Feichtmeier** 2019-11-04 13:52 UTC
Labels: Status: Not reproducible
