### ISSUE TITLE
Transparency problem on Tilix terminal windows

### ISSUE THREAD

**Issue by jokx** [ubuntu/yaru#1158] opened 2019-02-07 08:19 UTC
## Expected Behavior

I try to set a bit of transparency on Tilix terminal background.

## Actual Behavior

When a Tilix windows loose focus, the background loose transparency. This only append with Yaru GTK Theme. I tested Adwaita and Arc, without encountering this problem

## Steps to Reproduce the Problem

  1. Choose Yaru GTK Theme in gnome-tweaks
  2. Launch a Tilix terminal and set a background transparency
  3. Clic on another window, so Tilix window loose focus
  4. See how Tilix background transparency disappear

## Specifications

Tested with Cosmic and Disco package (from fr.archive.ubuntu.com)

Software that presents the issue:
- Name: yaru-theme-gtk
- Version: 18.10.6 (cosmic) and 19.04 (disco)

**Comment by clobrano** [comment] 2019-02-07 09:19
Hi @jokx, thanks for taking time to contribute.
I can confirm this on my 18.10 VM, but not on master installed from sources. I will prepare a VM with disco because master branch and disco release are quite close, I wonder why it's reproducible in 19.04 as well.

**Comment by chrisjbillington** [comment] 2019-02-07 15:21
Also get this in Arch linux installing yaru from master using the AUR package. I had assumed it was by design in Tilix, nice to know its not! It does not occur with other GTK themes.

**Comment by Feichtmeier** [comment] 2019-02-07 15:45
Just a wild guess but was"the other window" nautilus for all of you?

**Comment by clobrano** [comment] 2019-02-07 15:50
No, it is independend from Nautilus

**Comment by clobrano** [comment] 2019-03-26 16:54
Short update: this is an issue only on preinstalled or snap, but not when Yaru is installed from source :weary: 

![image](https://user-images.githubusercontent.com/2883614/55017003-24396f80-4ff0-11e9-934d-f2c8c6147413.png)

**Comment by chrisjbillington** [comment] 2019-03-26 19:38
Here on Arch, where the installation is essentially a `ninja -C build install` (see the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yaru)), the issue is still present:

![image](https://user-images.githubusercontent.com/1044087/55027903-c7808980-4fdc-11e9-8b34-f1a195ea0a00.png)

**Comment by Feichtmeier** [comment] 2019-09-08 16:41
As this does not occur any more for the master branch, I'll close this.

**Comment by chrisjbillington** [comment] 2019-09-14 18:18
I'm still seeing this on Yaru 19.10.2 and gnome-shell/mutter 3.34 on Arch Linux using the AUR package\* 

![Peek 2019-09-14 14-09](https://user-images.githubusercontent.com/1044087/64912171-7b93df00-d6f9-11e9-8ed0-95e5ab24a898.gif)

\* I've modified the AUR PKGBUILD myself to build 19.10.2, otherwise the package is being held back until gnome 3.34 officially hits Arch, but I'm using the [testing] repositories to test gnome 3.34 in advance.

**Comment by clobrano** [comment] 2019-09-27 07:34
Confirmed on Eoan :(

**Comment by Feichtmeier** [comment] 2019-09-27 09:02
What happens if you disable our dedicated terminal styling in apps? Maybe these semi transparent scrollbars are somehow causing tilix to follow the transparency

**Comment by clobrano** [comment] 2019-09-27 09:12
Got it, it's due to this specific line

https://github.com/ubuntu/yaru/blob/357752b57d1ffbd01722f2f0ea1139fcb9a0dc0f/gtk/src/default/gtk-3.20/_apps.scss#L27

**Comment by Feichtmeier** [comment] 2019-09-27 11:09
Omg that one! XD

"Every time you use a wildcard a kitten dies"

**Closed** 2019-10-08 09:10 UTC
Labels: Status: confirmed, Status: fix ready
