### ISSUE TITLE
Theme seems incompatible with Libreoffice 6.2 snap.

### ISSUE THREAD

**Issue by dshimer** [ubuntu/yaru#1194] opened 2019-02-17 20:25 UTC
## Expected Behavior
Work with the latest LibreOffice snap version 6.2

## Actual Behavior

The menus and dialogs were unusable.  The theme seemed to switch to a dark theme, the top menus were transparent and unreadable on the background of the working application, the options dialogues (when I could get to them) painted over top of each other and didn't seem to refresh leading to total un-usability.

![libreoffice_6_2_theme](https://user-images.githubusercontent.com/16683881/52918684-d8e0c280-32c7-11e9-816d-3c76ef06c855.png)
## Steps to Reproduce the Problem

1.LibreOffice snap refreshed overnight and was broken on usage.
2.Some systems simply logging in using "Gnome on Ubuntu" fixed it.  On another system I had to use Gnome Tweaks to set default theme.
3.Switching themes always solved it.

## Specifications

If you installed Yaru via Gnome Software or via snap, copy here the output of the following terminal command

    `$ snap info communitheme`
name:      communitheme
summary:   The next Ubuntu theme built by the community.
publisher: Didier Roche (didrocks)
license:   unset
description: |
  Yaru, formerly known as Communitheme, is the new Ubuntu theme built by the community. Yaru will
  become the default Ubuntu theme in Ubuntu 18.10. This package allows you to try out the theme on
  Ubuntu 18.04 LTS.
  
  To try out the theme, install this package on Ubuntu 18.04 LTS, restart your computer and select
  the "Ubuntu with communitheme snap" session from the login screen.
  
  More information is available at
  https://community.ubuntu.com/t/faq-ubuntu-new-theme/1930.
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     stable
refresh-date: 12 days ago, at 09:08 EST
channels:
  stable:    0.1 2019-02-05 (1593) 19MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-02-17 (1666) 19MB -
installed:   0.1            (1593) 19MB -

**Comment by clobrano** [comment] 2019-02-17 21:58
Hi @dshimer, thank you for taking time to contribute and sorry if I edited the bug post, I only removed unnecessary text

**Comment by dshimer** [comment] 2019-02-18 02:28
No worries @clobrano anything I can do to help, I'm a barely technical daily user but I can certainly follow instructions.  When this showed up on 3 different systems I really panicked because LO is critical to my day and it was pretty unusable, I love yaru and want to switch back to it so I'm motivated to do whatever I can to help out.

**Comment by clobrano** [comment] 2019-02-20 16:40
Hi @dshimer, do you still have this issue?
I tested the same versions, but I could not reproduce this error

![image](https://user-images.githubusercontent.com/2883614/53107939-6b869900-3536-11e9-9542-52b95dd1054c.png)


EDIT: also I just noticed that your application looks "Libreoffice 6.1"

**Comment by dshimer** [comment] 2019-02-20 19:54
Yes still have the problem.  I can turn it on and off by toggling the Communitheme in Tweaks.  Don't even  have to exit LO. 
 
Communitheme on
Menus compress and dialogues garble
Default on
Display normal.  

The 6.1 screenshot came from an attempt to roll the snap back on one system but the problem persisted.  All other systems I maintained the 6.2 snap because I realized that even though the problem didn't show up on any system until the LO snap updated itself to 6.2 I could fix it with the theme and thereby maintain the stable LO snap.  One of the systems doesn't have Tweaks so logging in with the appropriate theme (is that what it is still called when at the login) accomplishes the same.    
Systems are Dell Desktop, Lenovo all-in-one, Lenovo laptop, all with straight 18.04 install, LO snap, communitheme snap.  Obviously something else I have done that is causing the problem in 3 unique systems.

![tweaks_yaru](https://user-images.githubusercontent.com/16683881/53120077-feb3d480-351e-11e9-8f55-f801bd7dc5dd.png)
![lo_yaru](https://user-images.githubusercontent.com/16683881/53120082-04111f00-351f-11e9-82bc-8322bd4190b2.png)
![tweaks_default](https://user-images.githubusercontent.com/16683881/53120086-07a4a600-351f-11e9-9782-e96cdaf4dd59.png)
![lo_default](https://user-images.githubusercontent.com/16683881/53120096-0d01f080-351f-11e9-9183-178bf476efb5.png)

**Comment by clobrano** [comment] 2019-02-22 14:10
I was about to suggest you to open a post on snapcraft, but I saw you already did :+1: 
https://forum.snapcraft.io/t/how-can-i-fix-a-broken-dark-theme-and-menus-in-the-libreoffice-6-2-snap/10005

I'm closing this **for now**, feel free to reopen according to how snapcraft forum replies

**Closed** 2019-02-22 14:10 UTC
Labels: not-reproducible

**Comment by IslamAssem** [comment] 2020-03-12 09:45
I don't know if i should post this here but it might help you before this issue happen i was trying to install youtube video downloader and 4k video downloader so i installed both if them and removed them later multiple times
These are versions i installed 
youtube-dlg_0.4-1~webupd8~disco0_all
4kvideodownloader_4.11.3-1_amd64
4kvideodownloader_4.11.2-1_amd64.deb
![image](https://user-images.githubusercontent.com/16445945/76508087-83d59880-6456-11ea-8675-09caf8fa599f.png)

**Comment by clobrano** [comment] 2020-03-12 09:52
Thanks @IslamAssem, but I don't think it's related :)

**Comment by madsrh** [comment] 2020-03-12 10:56
> I tested the same versions, but I could not reproduce this error

@clobrano I believe this is only in the dark theme. I wonder if the same bug exist using Adwaita dark, but as you said it's a snap issue

**Comment by clobrano** [comment] 2020-03-12 14:13
I see, then maybe it's from the times the dark theme wasn't shipped for snaps?
