### ISSUE TITLE
Libreoffice styling issues

### ISSUE THREAD

**Issue by madsrh** [ubuntu/yaru#478] opened 2018-05-25 06:21 UTC
I don't know if this counts as a "individual application fix", but here are two small issues from LibreOffice:

1. The hover effect is off and the padding left for 0.00" is missing
![libreoffice](https://user-images.githubusercontent.com/3986894/40529306-7f19d030-5ff4-11e8-9ef7-f19897c50233.jpg)

2. (Pretty self explanatory)
![libreoffice2](https://user-images.githubusercontent.com/3986894/40529331-932261be-5ff4-11e8-97a5-cc7cc09d633d.jpg)

EDIT: sorry @madsrh if I edit your report. Adding a TODO list with the actions suggested by @fitojb 

TODO:
- [x] forward any individual LibreOffice-specific theming bugs to bugs.documentfoundation.org, and mark each report as blocking https://bugs.documentfoundation.org/show_bug.cgi?id=gtk3-themeing. 
- [x] testing with LO 6.1

Noted issues to be reported upstream
- [ ] spinnbutton loses border in hover state
![screenshot from 2018-07-25 18-20-36](https://user-images.githubusercontent.com/2883614/43213709-94938e9c-9037-11e8-8d81-9579712b51bb.png)

- [ ] selection ring glitch
![image](https://user-images.githubusercontent.com/2883614/43213450-edcb1486-9036-11e8-903c-025cb76963d2.png)

- [ ] selection ring is incomplete in comboboxes 
![image](https://user-images.githubusercontent.com/2883614/43213360-b6a36dc8-9036-11e8-8732-2f13c83c0517.png)

**Comment by fitojb** [comment] 2018-06-11 14:59
Please forward any individual LibreOffice-specific theming bugs to bugs.documentfoundation.org, and mark each report as blocking https://bugs.documentfoundation.org/show_bug.cgi?id=GTK3. Theming improved somewhat in LO 6.1 -- be sure to test that.

**Comment by clobrano** [comment] 2018-07-19 21:35
> Theming improved somewhat in LO 6.1 -- be sure to test that.

@fitojb is the version right? 6.1 version is expected in August

**Comment by Feichtmeier** [comment] 2018-07-19 22:57
@fitojb if you look into this could you also look into the text selection? =) textview.view uses a blue text selection, libreoffice seems to "suck" the style portion from some other style class

**Comment by clobrano** [comment] 2018-07-25 16:12
Tested on LO edge channel, which has version 6.1.0.2 and the issue is still present

**Comment by Feichtmeier** [comment] 2018-07-27 18:13
Hm about those spinbuttons: I had one PR where I wanted to adapt the spin buttons to other buttons, this could "solve" this issue, too. @clobrano should I make a PR?

**Comment by clobrano** [comment] 2018-07-27 18:17
I don't expect it will solve libreoffice issue, but sure go ahead :+1:

**Comment by Feichtmeier** [comment] 2018-12-01 10:33
What really bugs me, is that Adwaita doesnt have these problems
![image](https://user-images.githubusercontent.com/15329494/49327088-801d4b80-f55c-11e8-8c61-7540ea2ad42d.png)

Here you can see that 1px is cut, even in adwaita, but it does not look so bad because adwaita has a 2 pixel outline on entries (with is generally not looking very good, but here it is "effective"
![image](https://user-images.githubusercontent.com/15329494/49327103-cb375e80-f55c-11e8-8867-cd6f5baf5767.png)

**Comment by clobrano** [comment] 2018-12-01 11:08
Could it be that adwaita outline is thicker? The line on the right that is not visible in arc is also thinner in adwaita

**Comment by Feichtmeier** [comment] 2018-12-01 11:13
Yes
But I would not make ours that thick only for that lo bug xD
At first I thought adwaita hasn't that problems but I was wrong. Adwaita, yaru and arc have all their widgets cut or something is missing. I'd say we can't do much about this

**Comment by Feichtmeier** [comment] 2018-12-03 12:09
Uh this one describes the problem with the cut entries good: https://bugs.documentfoundation.org/show_bug.cgi?id=105607

And this one describes the problem with the  cut radios and checks
https://bugs.documentfoundation.org/show_bug.cgi?id=103280

So I'd say we need to report the issue with the focus ring and then we can close this one here because we can't do anything about it

**Closed as completed** 2018-12-03 17:29 UTC
Labels: upstream
