### ISSUE TITLE
VMware Remote Console menu items not spaced apart

### ISSUE THREAD

**Issue by skewty** [ubuntu/yaru#607] opened 2018-07-06 16:18 UTC
VMware Remote Console 10's menu items not spaced apart.  They have 0 margin between entries.
Additionally the text foreground and background colour of the entries doesn't match the grey used in the menu background.

**Comment by Feichtmeier** [comment] 2018-07-06 18:16
VMware? What is this?
Screenshots please

**Comment by clobrano** [comment] 2018-07-08 18:39
@skewty it looks like that to download vmware remote console I have to register first, and registration requires business phone and other things I don't have :D since I am not part of a company (in this specific case). I know that vmware has free apps, but Is this a paid one?

**Comment by skewty** [comment] 2018-07-09 02:55
I'll get you screenshots when I get to work tomorrow :)  Thank you for your hard work on this project.

I don't believe VMware requires a paying account for their downloads; only for licensing. :)  The account creation is more for tracking reasons I believe.

+Scott

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by skewty** [comment] 2018-07-09 17:48
![screenshot from 2018-07-09 10-44-32](https://user-images.githubusercontent.com/9087223/42466955-6013e4e8-8365-11e8-8a2e-21716b3e89f5.png)

**Comment by clobrano** [comment] 2018-07-14 16:18
This is a tricky one. Vmware remote console didn't want to start, so I looked into syslogs for insights and I observed a bunch of gtk-warnings like the one below when vmware starts


    Gtk-WARNING **: Theme parsing error: gtk.css:15:21: '-gtk-outline-radius' is not a valid property name
    Gtk-WARNING **: Theme parsing error: gtk.css:16:28: '-gtk-secondary-caret-color' is not a valid property name


this is a very long list of warnings everywhere in gtk.css. So, even if I can't run the app, I am pretty sure this the root cause: the app is simply *non styled* because of *theme parsing errors*.

First of all, -gtk-outline-radius as well as -gtk-secondary-caret-colors **are** valid property names and at a first glance all the other warnings look false

Secondly, selecting Adwaita from Tweaks (A), I cannot replicate the problem, however if I replace /usr/share/themes/Communitheme/.../gtk.css with Adawita's one (B), the problem **is** reproduced.

The difference in the two use cases is that (A) uses Adwaita css as gresource, while (B) (as far as I know) doesn't.

So, this might be due to how VMWare uses the theme resources, I shall ask upstream if they have any idea

**Comment by clobrano** [comment] 2018-08-11 16:01
I now think this is a problem with how vmware recognize session, hopefully this will be automatically fixed when yaru session will be ubuntu one, otherwise we might need to ask upstream

**Comment by Feichtmeier** [comment] 2018-11-07 10:57
Is this fixed in cosmic? Since the session is only "ubuntu"?

**Comment by clobrano** [comment] 2018-11-07 11:01
I should try again, but maybe @skewty can test it first

**Comment by skewty** [comment] 2018-11-12 00:41
I am busy with other things right now and am then away for 4 weeks without good Internet access.  If this is not closed when I get back, I will check into it.

**Comment by Feichtmeier** [comment] 2018-12-01 10:57
![image](https://user-images.githubusercontent.com/15329494/49327282-e6579d80-f55f-11e8-8174-e465162e6b57.png)

![image](https://user-images.githubusercontent.com/15329494/49327291-05eec600-f560-11e8-9055-82cbad749e8a.png)

The menu is now spaced apart. But.... they somehow placed the menubar without spreading it along the whole window.

CLosing this now, we can not do anything about that anyways

**Closed by Feichtmeier** 2018-12-01 10:57 UTC
Labels: gtk2, help wanted
