### ISSUE TITLE
[Bionic] Check mark (✓) is invisible in Firefox context menu

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#2064] opened 2020-03-14 07:17 UTC
### Steps to see the issue
1. Open Firefox and go to a text field
2. Right-click in a text field and select "Check Spelling"
3. You should see a check mark (✓) beside "Check Spelling"
4. The check mark is invisible

### Software that presents the issue
- OS: Ubuntu 18.04
- App: Firefox
- Version: 74

### Yaru version
$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     latest/edge
refresh-date: 11 days ago, at 19:12 CET
channels:
  stable:    0.1    2019-03-13 (1768) 16MB -
  candidate: ↑                             
  beta:      ↑                             
  edge:      29.180 2020-03-03 (1970) 18MB -
installed:   29.180            (1970) 18MB -

**Comment by Feichtmeier** [comment] 2020-03-26 15:09
@clobrano I think this is the very issue we talked about on telegram :)

**Comment by clobrano** [comment] 2020-03-26 15:51
I guess

**Comment by clobrano** [comment] 2020-09-26 16:46
Not reproducible on 20.04 + Firefox 80.0.1.
18.04 is still affected though.

**Comment by Feichtmeier** [comment] 2020-09-26 19:15
Imo, we should stop to support the snap. It is what it is, it looks okay but personally I have hard times contributing to the newest release plus the latest lts. Bionic on top is too much.

**Comment by clobrano** [comment] 2020-09-26 20:25
I agree that this is a hard time for us contributors. Even more maybe because I have little to no time lately, however the bug tracker is not only for our capacity, but for anyone that passes by and wants to help :smile: 
For this and for all the similar issues, we can add the "help wanted" label, and also try to do our best to bring more people to help us.

**Comment by Muqtxdir** [comment] 2022-01-04 18:23
since no updates are being passed to `communitheme` snap anymore, closing this issue seems rerasonable (_see #3154_)

**Closed by Muqtxdir** 2022-01-04 18:23 UTC
Labels: help wanted, Area: gtk3
