### ISSUE TITLE
Yaru light: indistinguishable focus in MATE window switcher

### ISSUE THREAD

**Issue by andrewshadura** [ubuntu/yaru#2813] opened 2021-04-29 10:09 UTC
The focus in the window switcher is very difficult to see because there’s no border and the contrast is very low:
![image](https://user-images.githubusercontent.com/309253/116535110-aab58f00-a8e3-11eb-8a59-d6ef31dc58cf.png)

**Comment by Feichtmeier** [comment] 2021-04-29 10:19
confirmed issue, thank you!

**Comment by Feichtmeier** [comment] 2021-12-20 08:29
@andrewshadura after feeled one million years I had the time to create a mate VM 

I can not reproduce this issue with ALT + TAB
![grafik](https://user-images.githubusercontent.com/15329494/146736149-719e8cd4-7b31-422c-b16f-71cc4e515473.png)

WHat's the key combo to tigger this focus switcher screen?

**Comment by andrewshadura** [comment] 2021-12-20 08:41
On my system it’s Alt-Tab.

**Comment by Feichtmeier** [comment] 2021-12-20 08:51
Weird - which version are you running?
I installed a fresh 21.10 (which also has an outdated yaru, as we've just unified the mate and master branches... btw... @Muqtxdir @Jupi007 how do I build the mate themes now? xD)

**Comment by andrewshadura** [comment] 2021-12-20 08:54
If I remember correctly there are multiple switcher types, maybe you have a different one selected?

**Comment by andrewshadura** [comment] 2021-12-20 08:56
Oh, I’m using Marco as the WM, do you maybe have Compiz instead?

**Comment by Feichtmeier** [comment] 2021-12-20 09:08
i use the default ubuntu mate - no idea :D

**Comment by andrewshadura** [comment] 2021-12-20 09:10
The setting is in the MATE Tweak — but I have to say I use the default too, but then I didn’t install with MATE initially, so that could have had an influence.

**Comment by Jupi007** [comment] 2021-12-20 10:09
> Weird - which version are you running? I installed a fresh 21.10 (which also has an outdated yaru, as we've just unified the mate and master branches... btw... @Muqtxdir @Jupi007 how do I build the mate themes now? xD)

You need to set **mate** and **mate-dark** options to `true` in `meson_options.txt`.

**Comment by Jupi007** [comment] 2021-12-20 10:23
Oh, important thing, you need to remove the `build` folder when disabling **mate** flavours.

**Comment by andrewshadura** [comment] 2022-02-09 11:52
I guess I figured out why we’re seeing different results. In MATE Tweak, in Windows tab, select *Marco (Compton GPU compositor)*. Then you should see the same window switcher as I do.

**Comment by flexiondotorg** [comment] 2022-03-24 16:47
Ubuntu MATE 22.04 supports `picom` as an alternative compositor. `picom` is a fork of  `compton` and replaces it.

@Jupi007 If you have the time, please take a look at this one.

- You need to be running a Yaru light theme, such as Yaru MATE Light.
- You need to enable *Marco (picom: Xrender)* via MATE Tweak

![image](https://user-images.githubusercontent.com/304639/159966607-77d6a3c5-179f-461e-bd29-c66a63c46f3e.png)

Then <kbd>Alt</kbd> + <kbd>Tab</kbd> with some applications open. In light themes only, the background used the highlight the selected app is indistinguishable from the base color.

![image](https://user-images.githubusercontent.com/304639/159967825-739777a4-06ca-41bc-a4f7-c27738ff5bc7.png)

**Comment by Jupi007** [comment] 2022-03-24 17:34
I can reproduce the problem, but is this a Gtk window/widget?
If so, do you know where I could find some selector for this?

I'm asking this because I can't open the Gtk widget inspector because this popup is gone once I release the `Alt` key.
And I need to press `Ctrl+Maj+D` to open the inspector.

**Comment by flexiondotorg** [comment] 2022-03-25 01:13
Well, it is Gtk. The code for the tab switcher is here:

- https://github.com/mate-desktop/marco/blob/master/src/ui/tabpopup.c

Not sure is that is revealing enough to expose what colours it derives from.

**Comment by Jupi007** [comment] 2022-03-25 12:57
Thanks @flexiondotorg,
sadly, I can't found the correct selector for this.
I navigated into the code ... but honestly, I never used Gtk in my life so I don't know what I should search 😅

Maybe can you ask somebody who worked on the tab switcher?

**Comment by Feichtmeier** [comment] 2022-03-25 13:01
maybe this line?

https://github.com/mate-desktop/marco/blob/0e517d0fe102296e4b44253c1673cb767b5f444c/src/ui/tabpopup.c#L291

**Comment by Feichtmeier** [comment] 2022-03-25 13:10
Also those lines are super weird
https://github.com/mate-desktop/marco/blob/0e517d0fe102296e4b44253c1673cb767b5f444c/src/ui/tabpopup.c#L1126-L1135

**Comment by Feichtmeier** [comment] 2022-03-25 13:36
@flexiondotorg in theory, you should use the "osd" style class of gtk which is always dark in yaru. So if I think correctly, we should not need to fix this in yaru

**Comment by Jupi007** [comment] 2022-03-25 13:40
Thanks for the investigation @Feichtmeier

After a lot (and a lot) of trying, I found a selector: `image:selected` (which is logical).

![Capture d’écran du 2022-03-25 14-40-04](https://user-images.githubusercontent.com/36476595/160131612-9c3c9ca0-eece-4c21-8fe0-f85f83e894a0.png)

**Comment by Feichtmeier** [comment] 2022-03-25 13:41
That's nice @Jupi007 

I still think this pop-up needs to be dark just like in gnome shell.

**Comment by Jupi007** [comment] 2022-03-25 13:47
> I still think this pop-up needs to be dark just like in gnome shell.

Yeah maybe, but I can't style the window around at all as I didn't found a working selector.
I tried many things like: `window`, `window.osd`, `.osd`, ... 😅

Btw, Adwaita have the same issue, so maybe this should be fixed in a custom stylesheet inside the marco project 🤔

**Comment by Jupi007** [comment] 2022-03-25 13:52
**Little note:** it seems doesn't support transparent colors, on the screenshot I had to darken the `bg_color`.
If I use `transparentize` the color is still opaque.

**Comment by Jupi007** [comment] 2022-03-25 13:57
> Btw, Adwaita have the same issue, so maybe this should be fixed in a custom stylesheet inside the marco project thinking

**Note 2:** Adwaita looks like this:

![Capture d’écran du 2022-03-25 14-54-20](https://user-images.githubusercontent.com/36476595/160134125-89272395-a949-4e9f-8e3b-5ad1324340ec.png)

It is not perfect, but we can see which item is selected.
Imo, the issue comes from the Yaru side after all: as we use a lighter bg, the white selected background is low contrast.

I think we should just add a fix for `image:selected`, like in my screenshot.
What do you think of @Feichtmeier ?

**Comment by Feichtmeier** [comment] 2022-03-25 13:59
> > Btw, Adwaita have the same issue, so maybe this should be fixed in a custom stylesheet inside the marco project thinking
> 
> **Note 2:** Adwaita looks like this:
> 
> ![Capture d’écran du 2022-03-25 14-54-20](https://user-images.githubusercontent.com/36476595/160134125-89272395-a949-4e9f-8e3b-5ad1324340ec.png)
> 
> It is not perfect, but we can see which item is selected.
> Imo, the issue comes from the Yaru side after all: as we use a lighter bg, the white selected background is low contrasted with the background.
> 
> I think we should just add a fix for `image:selected`, like in my screenshot.
> What do you think of @Feichtmeier ?

Sure. Just in the long run I don't think this osd pop-up should look any different than the other osd pop-ups. And this needs to be fixed by the mate guys in that C code

**Comment by Jupi007** [comment] 2022-03-25 14:03
> Sure. Just in the long run I don't think this osd pop-up should look any different than the other osd pop-ups. And this needs to be fixed by the mate guys in that C code

I agree with you.

So I'll send a patch for selected images, because this issue could affect some other apps.

**Comment by flexiondotorg** [comment] 2022-03-25 15:17
So, MATE does use the OSD styling when Marco's own compositor is enabled. But, when people use 3rd party compositors then Marco doesn't use the OSD styling, since it is now running with its own compositor disabled and assumes there is no compositor.

And that is the issue you have fixed :smiley: 

I'm very grateful because it is common for MATE uses to use compton/picom compositors, and I've even improved support for picom in 22.04. So this is an important fix for Ubuntu MATE 😍

**Closed** 2022-03-26 08:49 UTC
Labels: Area: MATE
