### ISSUE TITLE
"Today" and "Tomorrow" buttons in gnome-weather look the same

### ISSUE THREAD

**Issue by Amr-Ibra** [ubuntu/yaru#1559] opened 2019-10-04 09:03 UTC
## Expected Behaviour
"Today" and "Tomorrow" buttons in gnome-weather look different

## Actual Behaviour
"Today" and "Tomorrow" buttons in gnome-weather look the same

## Steps to Reproduce the Problem
1. Install gnome-weather (sudo apt install gnome-weather)
2. Start gnome-weather
3. Look at the "Today" and "Tomorrow" buttons

## Specifications
$ snap info communitheme
snap-id:      Yd6CISPIf6tEf3ZEJ0cqSoEg9rG2VkRi
tracking:     edge
refresh-date: gestern um 15:05 CEST
channels:
  stable:    0.1 2019-03-13 (1768) 16MB -
  candidate: ↑                          
  beta:      ↑                          
  edge:      0.1 2019-09-29 (1855) 18MB -
installed:   0.1            (1855) 18MB -

Software that presents the issue:
- Name: gnome-weather
- Version: 3.26.0

![gnome-weather_buttons](https://user-images.githubusercontent.com/45657128/66195256-89080d80-e696-11e9-9176-28d6688864bc.png)

**Comment by clobrano** [comment] 2019-10-04 09:23
This is tough. These are standard buttons of the dark variant, which usually have dark background, which helps. I would avoid add specific style for the application and upstream the problem is very similar

![image](https://user-images.githubusercontent.com/2883614/66196694-45fb6980-e699-11e9-954b-712f50c6b3b0.png)

**Comment by Feichtmeier** [comment] 2019-10-04 12:11
Totally agreed with @clobrano 

The problem is the app design with a stackswitcher in the middle of the screen (they are mostly inside headerbars), not us painting it with our colors
We didn't change anything there, except the height of the buttons in the whole toolkit, the roundings and the colors. 
Thus closing this, I would report this on the gnome weather repo if needed

**Closed by Feichtmeier** 2019-10-04 12:11 UTC
