### ISSUE TITLE
Gedit text is unreadable under Yaru dark theme

### ISSUE THREAD

**Issue by lekegf** [ubuntu/yaru#2473] opened 2020-11-04 02:17 UTC
## Expected Behavior

See the text you're writing in Gedit in the current line.

## Actual Behavior

There's a white highlight in the current line (where the font is white as well), making it unreadable. 

## Steps to Reproduce the Problem

  1. Set Yaru theme to dark
  2. Open Gedit (Text Editor)
  3. Start typing 

## Software that presents the issue

- Name: gedit
- Version: 3.36.2

## Yaru version

The default in Ubuntu 20.04 up to the date 2020 November 3th
Important note: The same issue is present in the Adwaita dark as well.

![Captura de tela de 2020-11-03 23-03-21](https://user-images.githubusercontent.com/62917388/98061598-fd2d5b80-1e2a-11eb-9cf8-805627958c8c.png)

**Comment by madsrh** [comment] 2020-11-04 06:37
Hi. Thanks for reporting this issue

> Important note: The same issue is present in the Adwaita dark as well.

Since Yaru is based on Adwaita, this bug should be reported there (and it already is), so the fix is upstream.

https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/29 you can see that it is marked as low level, or non-issue upstream. 

Closing the issue here

**Closed by madsrh** 2020-11-04 06:37 UTC

**Comment by clobrano** [comment] 2020-11-04 22:09
Also duplicate of #2090 and #2444

**Comment by lekegf** [comment] 2020-11-07 02:52
Since probably there's not going to be a upstream fix anytime soon, wouldn't it make sense disable the option "Highlight current line" in gedit by default in Ubuntu?

**Comment by clobrano** [comment] 2020-11-07 07:58
As yaru project, we have no way to decide gedit defaults. I think that the best option is just to select a different dark gedit colorscheme.
