### ISSUE TITLE
Bad contrast in awesomebar in Firefox dark theme 

### ISSUE THREAD

**Issue by yoasif** [ubuntu/yaru#1065] opened 2018-12-28 23:56 UTC
## Expected Behavior
I am using Firefox on Ubuntu Cosmic with the built in Firefox theme. Awesomebar (address bar) entries show up with a blue background and black text, whereas Adwaita shows this as white on blue. 

## Actual Behavior

I expect to see better contrast in address bar entries in Firefox while using its dark theme. 

## Steps to Reproduce the Problem

- Open Firefox menu
- click customize
- Select "Dark" from Themes menu
- Click Done
- type anything into awesomebar

## Specifications

Using Yaru 18.10.6 on Cosmic. 

Software that presents the issue:
- Name: Firefox 
- Version: 64

![screenshot from 2018-12-28 18-55-58](https://user-images.githubusercontent.com/152493/50531038-421b3500-0ad2-11e9-832b-c625f8f2ed28.png)

**Comment by clobrano** [comment] 2018-12-30 11:46
Hi @yoasif, thanks for taking time to report this!

I can't reproduce this issue. So if the issue is confirmed, we have already the fix in master branch.

![image](https://user-images.githubusercontent.com/2883614/50546912-74db3f80-0c30-11e9-9d2f-1ac95c8d2d36.png)

Does anyone have a pure Cosmic to test this? At least to see if we can reproduce it and identify the fix that solved it in master.

**Comment by clobrano** [comment] 2019-01-03 16:34
I confirm the issue is present in Cosmic using the deb package

**Comment by Feichtmeier** [comment] 2019-01-03 16:45
I think that is the foreground of the soon legacy text selection, maybe the orange/white fixes that

**Comment by clobrano** [comment] 2019-01-03 16:56
I'm unsure it's only due to text selection, since on yaru master is not
reproducible

**Comment by yoasif** [comment] 2019-01-12 06:46
Just got an update in Disco and the contrast seems to be fixed.

**Comment by clobrano** [comment] 2019-01-12 17:46
I confirm, we just released master in Disco.

**Comment by Feichtmeier** [comment] 2019-01-27 01:02
If it's fixed, can we close it? :dancer:

**Closed** 2019-01-27 19:36 UTC
